```{r Load Gene OE and Compound data, eval=TRUE, warning=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(reshape2)
library(htmlTable)
library(foreach)
library(doMC)
library(magrittr)
library(readr)

registerDoMC(cores = 3)
#
source("rep.corr.func.R")
use.repurp.annots <- F
permute.moas <- F
random.shuffle <- F
N.run <- 10
seed.moa <- -8     ## ignore, if permute.moas is False
LUAD <- F
LUAD.mut <- F
just.bioactives <- F
no.top.matches <- 15
cor.thr <- 0.35
p.val.thr <- 0.05
N <- 200                     ## number of Monte-carlo simulations to estimate expected random matches
genes.to.remove <- c()        ## remove these genes before making matches

base.dir <- "2016-07-20_90b7bb86"
use.feat.selected.in.TA.ORF.in.common <- F
corr.type <- "pearson"

if (LUAD) {
  load("../input/LUAD/LUAD.RData")
  Pf.ta <- list(data = Px, factor_cols = "Metadata_x_mutation_status", feat_cols = setdiff(colnames(Px), "Metadata_x_mutation_status"))
  Pf.ta.all <- Pf
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "Treatment")
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta.all$factor_cols <- c(Pf.ta.all$factor_cols, "Treatment")

  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta.all$data$Treatment <- lapply(Pf.ta.all$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta$data <- Pf.ta$data %>% dplyr::group_by(Treatment) %>% slice(1) %>% dplyr::ungroup()
} else if (LUAD.mut) {
  load("../input/LUAD/LUAD.RData")
  Pf.ta <- list(data = Px, factor_cols = "Metadata_x_mutation_status", feat_cols = setdiff(colnames(Px), "Metadata_x_mutation_status"))
  Pf.ta.all <- Pf
  a <- read.csv("../input/LUAD/allele_classification.csv")
  GOF <- a$Allele[which(a$Benchmark.activity == "GOF" | a$eVIP_prediction %in% c("GOF", "Neutral"))]
  s <- Pf.ta$data$Metadata_x_mutation_status %>% unique
  s <- s[which(str_detect(s, "_WT"))]
  GOF <- c(as.character(GOF), as.character(s))
  
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Metadata_x_mutation_status %in% GOF) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "Treatment")
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta.all$factor_cols <- c(Pf.ta.all$factor_cols, "Treatment")

  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta.all$data$Treatment <- lapply(Pf.ta.all$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta$data <- dplyr::left_join(Pf.ta$data, uu, by = "Metadata_x_mutation_status")
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "strn")
  Pf.ta$data <- Pf.ta$data %>% dplyr::group_by(Treatment) %>% arrange(-strn) %>% slice(1) %>% dplyr::ungroup()
  Pf.ta$data %>% dplyr::select(Treatment, Metadata_x_mutation_status, strn) %>% unique %>% knitr::kable()
} else {
  load("../input/TA/Initial_analysis_workspace_new.RData")
  Pf.ta <- Pf_org.org.collapsed
  Pf.ta.all <- Pf_org.org
  strong.trt <- Pf.trt.strong.collapsed$data$Treatment
  r.cor <- rep.cor(Pf = Pf.trt, grp.var = "Treatment", feat.var = Pf.trt$feat_cols)
  
  data.annot <- Pf.strong %>% 
    dplyr::filter(Treatment %in% strong.trt) %>% 
    dplyr::left_join(., r.cor, by = "Treatment") %>%
    dplyr::select(one_of(c("Treatment", "Pathway", "Gene", "AlleleDesc", "cr"))) %>% 
    dplyr::mutate(Pathway = str_replace(Pathway, "Canonical ", "")) %>% 
    dplyr::mutate(AlleleDesc = str_sub(AlleleDesc, 1, 2)) %>%
    dplyr::arrange(-cr) %>%
    dplyr::group_by(Gene) %>% 
    dplyr::ungroup() 
  
  data.annot %>% htmlTable::htmlTable()
  
  desired.ta <- data.annot$Treatment
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(Treatment %in% c(as.character(desired.ta), "EMPTY_")) 
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
  
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
}

Pf.gene <- Pf.ta
Pf.gene.all <- Pf.ta.all
Pf.gene$data <- Pf.gene$data %>% dplyr::filter(! Treatment %in% genes.to.remove)


############

Pf.cmpd <- readRDS("../results/master/2017-04-20_64917c8b/Pf_annotated.rds")
Pf.cmpd$data %<>% mutate(CPD_NAME = ifelse(CPD_NAME != "", CPD_NAME, Metadata_broad_sample))

source("rep.corr.func.R")
Pf.1 <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")
if (!just.bioactives) {
  Pf.2 <- readRDS("../results/master/2017-04-20_425d653/Pf_DOS_new.rds")
  Pf <- rbind(Pf.1, Pf.2)
} else {
  Pf <- Pf.1 
}

u <- rep.cor(list(data = Pf, feat_cols = Pf.cmpd$feat_cols, factor_cols = Pf.cmpd$factor_cols), grp.var = "Metadata_broad_sample", feat.var = Pf.cmpd$feat_cols)
up <- readr::read_csv("../results/master/2017-04-21_425d6537/Cell_counts.csv")

x <- Pf %>% 
  left_join(., u, by = "Metadata_broad_sample") %>%
  left_join(., up, by = c("Metadata_Plate" = "Image_Metadata_Plate", "Metadata_Well" = "Image_Metadata_Well")) %>%
  dplyr::select(Metadata_broad_sample, cr, Image_Count_Cells) %>%
  dplyr::group_by(Metadata_broad_sample) %>%
  summarise_each(funs(mean))
  
Pf.cmpd$data %<>% 
  right_join(., x, by = "Metadata_broad_sample") %>%
  mutate(rep.corr = round(cr, 2), Mean_Cells_Count = round(Image_Count_Cells, 2)) %>%
  select(-cr, -Image_Count_Cells) 

Pf.cmpd$factor_cols <- c(Pf.cmpd$factor_cols, "rep.corr", "Mean_Cells_Count")
Pf.cmpd$data$Mean_Cells_Count <- round(scale(Pf.cmpd$data$Mean_Cells_Count), 2)

```

```{r Align the features in Compound and Gene OE data, eval=TRUE}

f1 <- Pf.cmpd$feat_cols
f2 <- Pf.gene$feat_cols
f <- intersect(f1, f2)

Pf.cmpd$feat_cols <- f
Pf.gene$feat_cols <- f

Pf.cmpd$data <- Pf.cmpd$data[,c(Pf.cmpd$factor_cols, Pf.cmpd$feat_cols)]
Pf.gene$data <- Pf.gene$data[,c(Pf.gene$factor_cols, Pf.gene$feat_cols)]

if (use.feat.selected.in.TA.ORF.in.common) {
  feats <- Pf_org$feat_cols
  feats <- intersect(feats, Pf.cmpd$feat_cols)
  Pf.cmpd$feat_cols <- feats
  Pf.cmpd$data <- Pf.cmpd$data[,c(feats, Pf.cmpd$factor_cols)]
  Pf.gene$feat_cols <- feats
  Pf.gene$data <- Pf.gene$data[,c(feats, Pf.gene$factor_cols)]
}

print(length(Pf.cmpd$feat_cols))
print(NROW(Pf.cmpd$data))

print(length(Pf.gene$feat_cols))
print(NROW(Pf.gene$data))

```

```{r some aux. func.}

get.interacting.proteins <- function(protein.name) {
  dr <- "../results/manual/ppis"
  if (!dir.exists(dr)) {
    system(sprintf("mkdir -p %s", dr))
  }
  f.name <- sprintf("%s/%s.rds", dr, protein.name)
  if (file.exists(f.name)) {
    return(readRDS(f.name))
  }
  
  tbl <- read.table(sprintf("http://webservice.thebiogrid.org/interactions/?searchNames=true&geneList=%s&taxId=9606&includeHeader=true&accesskey=ca950b072394ce1897811022f7757222", protein.name), sep="\t", header = FALSE, fill = T)
  tbl <- tbl[, c(8, 9, 12, 13, 14)] 
  colnames(tbl) <- c("Protein.1", "Protein.2", "Method", "Type", "Evidence")
  saveRDS(tbl, f.name)
  return(tbl)
}

get.all.interacting.proteins <- function(protein.name) {
  res <- c()
  for (p in protein.name) {
    ppi <- tryCatch(get.interacting.proteins(p), error = function(e) {})
    res <- rbind(res, ppi)
  }
  return(res)
}

connectivity <- function(pathway, MOA.q) {
  pathway.genes <- Pf.gene$data %>% 
    dplyr::filter(str_detect(Pathway, pathway)) %>%
    dplyr::select(Treatment) %>%
    dplyr::group_by(Treatment) %>%
    dplyr::summarise(gene = str_split(Treatment, "_")[[1]][1]) %>%
    dplyr::select(gene) %>%
    as.matrix() %>%
    as.vector() %>%
    unique
  
  MOA.genes <- Pf.cmpd$data %>%
    dplyr::ungroup() %>%
    dplyr::filter(str_detect(MOA, MOA.q)) %>%
    dplyr::select(Target) %>%
    as.matrix() %>%
    as.vector() %>%
    paste(., collapse = ", ") %>%
    str_split(., ", ") %>%
    unlist %>%
    setdiff(., "") %>%
    unique()
  
  ppi <- get.all.interacting.proteins(pathway.genes)
  intr <- c(ppi$Protein.1 %>% as.character(),
    ppi$Protein.2 %>% as.character()) %>%
    unique
  a <- (which(MOA.genes %in% intr) %>% length())/min(length(intr), length(MOA.genes))

  ppi <- get.all.interacting.proteins(MOA.genes)
  intr <- c(ppi$Protein.1 %>% as.character(),
    ppi$Protein.2 %>% as.character()) %>%
    unique
  b <- (which(pathway.genes %in% intr) %>% length())/min(length(intr), length(pathway.genes))
  return((a + b)/2)
}

connectivity <- Vectorize(connectivity)

```

```{r save the data put together, results="asis"}
sm.avg <- 0

if (random.shuffle) {
	n.run <- N.run
} else {
	n.run <- 1
}

for (i in 1:n.run) {

Pf.cmpd.res <- Pf.cmpd
#Pf.cmpd.res$data %<>% filter(!is.na(MOA) & MOA != "")
data <- rbind(Pf.gene$data[,Pf.gene$feat_cols], Pf.cmpd.res$data[,Pf.cmpd$feat_cols])

if (random.shuffle) {
  a <- Pf.gene$data[,c("Treatment", "Pathway")] %>% as.matrix()
  b <- Pf.cmpd.res$data[,c("CPD_NAME", "MOA")] %>% as.matrix()
  a <- a[permute::shuffle(NROW(a)), ]
  b <- b[permute::shuffle(NROW(b)), ]
  annot <- rbind(a, b)
} else {
  annot <- rbind(Pf.gene$data[,c("Treatment", "Pathway")] %>% as.matrix(),
               Pf.cmpd.res$data[,c("CPD_NAME", "MOA")] %>% as.matrix())
}
annot %<>% as.data.frame 
colnames(annot) <- c("Treatment", "Pathway")
annot <- cbind(annot, data.frame(Type = c(rep("gene", NROW(Pf.gene$data)),
                                          rep("compound", NROW(Pf.cmpd.res$data)))))
data.all <- cbind(annot, data)
data.all %<>% 
  dplyr::group_by(Treatment) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup(.)
write.table(data.all, 
            file = "gene_compound.txt",
            sep = "\t", 
            row.names = F)

cr <- data.all[,4:NCOL(data.all)] %>%
  t %>%
  cor %>%
  abs

write.table(cr, 
            file = "cr.txt",
            sep = "\t", 
            row.names = T)

rownames(cr) <- data.all$Treatment
colnames(cr) <- data.all$Treatment

hcl <- hclust(as.dist(1 - cr), method = "complete")
ct <- cutree(hcl, h = 1 - 0.45)

genes <- Pf.gene$data$Treatment
cmpds <- Pf.cmpd$data$CPD_NAME
sm <- 0
for (i in 1:max(ct)) {
  cl <- which(ct == i) %>% names  
  w <- which(genes %in% cl)
  y <- which(cmpds %in% cl)
  if (length(w) > 0 && length(y) > 0) {
    annot.cls <- annot %>% 
	    dplyr::filter(Treatment %in% cl) %>%
	    dplyr::select(Treatment, Pathway)  
    
    if (!random.shuffle) {
    	annot.cls %>%
	    htmlTable::htmlTable(.) %>%
	    print
    }
    
    cr.d <- cr[annot.cls$Treatment, ]
    rownames(cr.d) <- NULL
    colnames(cr.d) <- NULL
    corrplot::corrplot(cr.d)
#     
#     pathways <- Pf.gene$data$Pathway[Pf.gene$data$Treatment %in% genes[w]] %>% unique
#     pathways <- lapply(pathways, function(x) str_replace_all(x, "Canonical ", "")) %>% unlist
#     MOAs <- annot.cls$Pathway[which(!annot.cls$Treatment %in% genes[w])] %>% unique
#     MOAs <- setdiff(MOAs, "")
#     
#     mn <- mean(outer(pathways, MOAs, connectivity), na.rm = T)
#     if (!is.na(mn) && mn > 0.03) {
#       sm <- sm + 1
#     }
#     if (!random.shuffle) {
# 	    cat(sprintf("score is : %f", round(mn, 2)))
# 	    cat("<hr>")
# 	    cat("<br>")
#     }
  }
}

sm.avg <- sm.avg + sm

}

cat(sprintf("Total sig. clusters %d", (sm.avg)/n.run))

```

```{r Find the correlation matrix, eval=T}

cr <- cor(Pf.cmpd$data[,Pf.cmpd$feat_cols] %>% t, Pf.gene$data[,Pf.gene$feat_cols] %>% t)
rownames(cr) <- Pf.cmpd$data$CPD_NAME
colnames(cr) <- Pf.gene$data$Treatment
cr.melt <- melt(cr)
saveRDS(cr.melt, "cr_melt_cp.rds")

```

```{r, eval = T}

source("../l1ktools/R/cmap/io.R")
ds <- parse.gctx("../results/manual/cmap.compound.score/result_WTCS.LM.COMBINED_n328x22962.gctx", set_annot_rownames = F)
cmpd.gene.score.cmap <- attr(ds, "mat")
rn <- rownames(cmpd.gene.score.cmap)
rn <- sapply(str_split(rn, ":"), "[[", 2)
rownames(cmpd.gene.score.cmap) <- rn
rn.cmap <- rn

cn <- colnames(cmpd.gene.score.cmap)
cn <- sapply(str_split(cn, ":"), "[[", 2)
colnames(cmpd.gene.score.cmap) <- cn


meta.ta.cmap <- read.csv("../input/TA-OE-L1000-B1/TA.OE005_U2OS_72H_COMPZ.MODZ_SCORE_LM_n323x978.gctx.gct.csv") %>% t
colnames(meta.ta.cmap) <- meta.ta.cmap[1,]
meta.ta.cmap <- meta.ta.cmap[-1,]
meta.ta.cmap <- meta.ta.cmap %>% as.data.frame()
genes.ta.cmap <- meta.ta.cmap$x_genesymbol_mutation
ids.ta.cmap <- meta.ta.cmap$pert_id
meta.ta.cmap[, "det_well"] <- tolower(meta.ta.cmap$det_well)
treatment.meta <- Pf_org$data %>% 
  dplyr::filter(Type == "Treated") %>%
  dplyr::select(Well, Treatment) %>%
  unique %>% 
  dplyr::left_join(., meta.ta.cmap, by = c("Well" = "det_well"))

treatment.meta <- treatment.meta %>% dplyr::filter(!Treatment %in% c("CYLD_WT", "ERG_truncated"))

treatment.to.id <- data.frame(treatment.meta$pert_id)
rownames(treatment.to.id) <- treatment.meta$Treatment
id.to.treatment <- data.frame(treatment.meta$Treatment)
ix <- which(is.na(treatment.meta$pert_id))
treatment.meta$pert_id <- treatment.meta$pert_id %>% as.character()
treatment.meta$pert_id[ix] <- 1:length(ix)
rownames(id.to.treatment) <- treatment.meta$pert_id

colnames(cmpd.gene.score.cmap) <- id.to.treatment[cn, ]
cmpd.gene.score.cmap <- cmpd.gene.score.cmap[,intersect(desired.ta, colnames(cmpd.gene.score.cmap))]
u <- apply(cmpd.gene.score.cmap, 2, function(x) ecdf(x)(x))
cr.l1000 <- u
rownames(cr.l1000) <- rownames(cmpd.gene.score.cmap)

```

```{r, eval = T}

moas <- read.csv("../input/moas.txt", sep = "\t")

V <- matrix(0, 2, 2)

sample.tot <- function(Pf.cmpd, Pf.gene, random.shuffle = F, random.shuffle.genes = F, random.shuffle.cmpds = F, verbose = F, cor.thr = 0.5, how.many = 5, specificity.data) {
  gn.list <- c()
  gn.map <- Pf.gene$data$Treatment %>% as.matrix() %>% as.vector()
  if (random.shuffle.genes) {
    names(gn.map) <- gn.map[permute::shuffle(length(gn.map))]
    while(F) {
      names(gn.map) <- gn.map[permute::shuffle(length(gn.map))]
      flag <- T
      for (i in 1:length(cls.gene)) {
        if (any(gn.map[cls.gene[[i]]] %in% cls.gene[[i]])) {
          flag <- F
          break
        }
      }
      if (flag) {
        break
      }
    }
  } else {
    names(gn.map) <- gn.map
  }
  
  if (random.shuffle.cmpds) {
    Pf.cmpd$data[,"CPD_NAME"] <- Pf.cmpd$data[permute::shuffle(NROW(Pf.cmpd$data)), "CPD_NAME"]
  }
  
  all.targ <- lapply(Pf.cmpd$data$Target %>% unique, function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) %>% unique
  path <- sprintf("../results/manual/ppis")
  if (!dir.exists(path)) {
    system(sprintf("mkdir -p %s", path))
  }
  if (file.exists(sprintf("%s/all.rds", path))) {
    ppi.all <- readRDS(sprintf("%s/all.rds", path))
  } else {
    ppi.all <- tryCatch(get.all.interacting.proteins(all.targ), error = function(e) {})
    saveRDS(ppi.all, sprintf("%s/all.rds", path))
  }
  
  pb <- progress::progress_bar$new(total = length(Pf.gene$data$Treatment))
  res.all <- data.frame()
  
  for (gene in Pf.gene$data$Treatment) {
    if (verbose) {
      pb$tick()  
    }
    gn <- gn.map[gene] %>% as.matrix() %>% as.vector()
    if (!random.shuffle) {
      u.res <- cr.melt %>% 
        dplyr::filter(Var2 == gn) %>%
        dplyr::arrange(-value) %>%
        #dplyr::mutate(value = round(value, 2)) %>%
        dplyr::filter(abs(value) > cor.thr) 
        
        up.reg <- u.res %>% left_join(., specificity.data, by = c("Var1", "Var2")) %>% 
          dplyr::filter(!is.na(spec.)) %>%
          head(., how.many) %>% dplyr::filter(value > 0) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()
        down.reg <- u.res %>% left_join(., specificity.data, by = c("Var1", "Var2")) %>% 
          dplyr::filter(!is.na(spec.)) %>% tail(., how.many) %>% dplyr::filter(value < 0) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()

    } else {
      u.res <- cr.melt %>% 
        dplyr::filter(Var2 == gn) %>%
        sample_n(NROW(.)) %>%
        #dplyr::mutate(value = round(value, 2))
      up.reg <- u.res %>% left_join(., specificity.data, by = c("Var1", "Var2")) %>% 
          dplyr::filter(!is.na(spec.)) %>% head(., how.many) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()
      down.reg <- u.res %>% left_join(., specificity.data, by = c("Var1", "Var2")) %>% 
          dplyr::filter(!is.na(spec.)) %>% tail(., how.many) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()
    }
    
    reg <- c(up.reg, down.reg) %>% unique
    reg <- setdiff(reg, "")
    
    u.res.lim <- u.res %>% dplyr::filter(Var1 %in% reg) %>% dplyr::mutate(CPD_NAME = Var1) %>% dplyr::mutate(Corr. = value) %>% dplyr::select(one_of(c("CPD_NAME", "Corr.")))
    
    rest <- setdiff(Pf.cmpd$data$CPD_NAME %>% unique, reg)
    v <- lapply(Pf.cmpd$data$Target[Pf.cmpd$data$CPD_NAME %in% reg], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) 
    if (length(v) == 0) {
      next
    }
    u <- lapply(Pf.cmpd$data$Target[Pf.cmpd$data$CPD_NAME %in% rest], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) 
    
    main.targ <- data.frame(gene = v) %>% dplyr::group_by(gene) %>% tally() %>% dplyr::filter(gene != "") %>% dplyr::arrange(-n) %>% dplyr::select(gene) %>% as.matrix() %>% as.vector()
    rest.targ <- data.frame(gene = u) %>% dplyr::group_by(gene) %>% tally() %>% dplyr::filter(gene != "") %>% dplyr::arrange(-n) %>% dplyr::select(gene) %>% as.matrix() %>% as.vector()
    
    ppi <- ppi.all %>% dplyr::filter(Protein.1 %in% main.targ | Protein.2 %in% main.targ)
    ppi2 <- ppi.all %>% dplyr::filter(Protein.1 %in% rest.targ | Protein.2 %in% rest.targ)
    
    id <- ppi %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% NROW
    id0 <- ppi2 %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% NROW
    Vi <- rbind(c(id, NROW(ppi %>% unique) - id), c(id0, NROW(ppi2 %>% unique) - id0))
    V <- V + Vi
    
    fsh <- fisher.test(Vi, alternative = "greater")
    if (fsh$p.value < p.val.thr/length(Pf.gene$data$Treatment)) {
      gn.list <- c(gn.list, gene)
      if (verbose) {
        treatment <- data.annot$Treatment[which(data.annot$Gene == gene)]
        cat(gene)
        cat("<br>")
        cat(treatment)
        cat("<br>")
        colnames(Vi) <- c("gene in relevant ppi", "otherwise")
        rownames(Vi) <- c("compound matches", "rest of compounds")
        Vi %>% htmlTable::htmlTable() %>% cat
        cat("<br>")
        fsh %>% print
        cat("<br>")
        #(Pf.cmpd$data %>% dplyr::filter(Name %in% reg) %>% dplyr::select(one_of(c("Name", "MOA", "Target")))) %>% plyr::join(., u.res.lim, by = "Name") %>% dplyr::arrange(Corr.) %>% htmlTable::htmlTable() %>% cat
        Pf.cmpd$data %>% dplyr::filter(CPD_NAME %in% reg) %>% dplyr::select(one_of(c("CPD_NAME", "MOA", "Target", "rep.corr", "Mean_Cells_Count"))) %>% dplyr::inner_join(., u.res.lim, by = "CPD_NAME") %>% arrange(Corr.) %>% htmlTable::htmlTable() %>% cat
        (ppi %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% head(., 20)) %>% htmlTable::htmlTable() %>% cat
        cat("<br> <hr>")
      }
    } 
    
    if (verbose) {
      cr.l1000.melt <- cr.l1000 %>% reshape2::melt(.) %>% dplyr::filter(Var2 == gene)
      cat(gene, file = "predictions.html", append = T)
      cat("<br>", file = "predictions.html", append = T)
      
      res.out <- Pf.cmpd$data %>% 
        dplyr::filter(CPD_NAME %in% reg) %>% 
        dplyr::select(one_of(c("CPD_NAME", "MOA", "Target", 
                               "rep.corr", "Mean_Cells_Count"))) %>% 
        dplyr::inner_join(., u.res.lim, by = "CPD_NAME") %>% 
        dplyr::mutate(Var2 = gene) %>%
        dplyr::left_join(., specificity.data, by = c("CPD_NAME" = "Var1", 
                                                     "Var2" = "Var2")) %>%
        dplyr::left_join(., cr.l1000.melt, by = c("Metadata_broad_sample" = "Var1")) %>%
        arrange(Corr.) %>% 
        dplyr::mutate(value = round(value, 3)) %>% 
        dplyr::rename(l1000.score = value) %>% 
        dplyr::rename(specificity = spec.) %>% 
        dplyr::select(-Var2.x, -Var2.y) %>%
        unique
      
      res.all <- res.out %>% mutate(gene = gene) %>% as.data.frame() %>% rbind(res.all, .)
      
      res.out %>% htmlTable::htmlTable() %>% cat(., file = "predictions.html", append = T)
      cat("<br> <hr>", file = "predictions.html", append = T)
    }
  }
  
  return(list(genes = gn.list, V = V, res.all = res.all))
}

```

```{r, eval = T}

gene.to.cluster <- matrix(0, NROW(Pf.gene$data), 1)
rownames(gene.to.cluster) <- Pf.gene$data$Treatment
for (i in 1:length(cls)) {
  cl <- intersect(Pf.gene$data$Treatment, cls[[i]])
  gene.to.cluster[cl, 1] <- i 
}

singletons <- gene.to.cluster[,1] == 0
mx <- max(gene.to.cluster[,1] + 1)
gene.to.cluster[which(singletons), 1] <- mx:(mx + sum(singletons) - 1)
cr.melt.ext <- cr.melt %>%
  mutate(cluster.id = gene.to.cluster[Var2,1]) 

specificity <- function(vals, pos.matches) {
  vals.sorted <- vals %>% 
    arrange(ifelse(pos.matches, -1, 1) * value)
  
  best.clst <- vals.sorted %>%
    slice(1) %>%
    select(cluster.id, value, Var2)
  
  sec.best.clst <- vals.sorted %>% 
    filter(cluster.id != best.clst$cluster.id) %>%
    slice(1) %>%
    select(cluster.id, value) 
  
  df <- data.frame(spec. = (best.clst$value - sec.best.clst$value)/(best.clst$value),
             Var2 = best.clst$Var2)
  return(df)
}

make.match.pos <- function(x) {
  y <- x %>% 
    arrange(-value) %>%
    slice(1) %>%
    select(Var2, cluster.id, value) 
  return(y)
}

make.match.neg <- function(x) {
  y <- x %>% 
    arrange(value) %>%
    slice(1) %>%
    select(Var2, cluster.id, value) 
  return(y)
}

matches.pos <- cr.melt.ext %>% 
  group_by(Var1) %>% 
  do(data.frame(make.match.pos(.)))

matches.neg <- cr.melt.ext %>% 
  group_by(Var1) %>% 
  do(data.frame(make.match.neg(.))) 

pos.t <- cr.melt.ext %>%
  group_by(Var1) %>%
  do(data.frame(specificity(.[,c("value", "cluster.id", "Var2")], pos.matches = T))) %>%
  arrange(-spec.) %>%
  dplyr::left_join(., Pf.cmpd$data[, c("CPD_NAME", "MOA")], by = c("Var1" = "CPD_NAME")) %>% 
  dplyr::left_join(., matches.pos, by = "Var1") %>% 
  dplyr::rename(corr = value) %>%
  filter(abs(corr) > 0.4) %>% 
  #dplyr::mutate(spec. = round(spec., 2), 
  #              corr = round(corr, 2)) %>%
  dplyr::rename(Var2 = Var2.x) %>%
  dplyr::select(Var1, Var2, spec.)

neg.t <- cr.melt.ext %>%
  group_by(Var1) %>%
  do(data.frame(specificity(.[,c("value", "cluster.id", "Var2")], pos.matches = F))) %>%
  arrange(-spec.) %>%
  dplyr::left_join(., Pf.cmpd$data[, c("CPD_NAME", "MOA")], by = c("Var1" = "CPD_NAME")) %>% 
  dplyr::left_join(., matches.neg, by = "Var1") %>% 
  dplyr::rename(corr = value) %>%
  filter(abs(corr) > 0.4) %>% 
  #dplyr::mutate(spec. = round(spec., 2), 
  #              corr = round(corr, 2)) %>%
  dplyr::rename(Var2 = Var2.x) %>%
  dplyr::select(Var1, Var2, spec.)

spec.data <- rbind(pos.t, neg.t)

```

```{r, eval=T}

system("rm predictions.html")
res <- sample.tot(Pf.cmpd = Pf.cmpd, Pf.gene = Pf.gene, random.shuffle = F, random.shuffle.genes = F, random.shuffle.cmpds = F, verbose = T, cor.thr = cor.thr, how.many = no.top.matches, specificity.data = spec.data)
f <- fisher.test(res$V, alternative = "greater")

```

```{r, eval=T}

print(f)
print(res)
saveRDS(res$res.all, "gene_compound_all.rds")

```

```{r, eval=F}

library(ggplot2)

cmpd.list <- readr::read_csv("../input/hras/Compound_List.csv") %>% as.matrix() %>% as.vector()
cr.n <- cor(Pf.cmpd$data[,Pf.cmpd$feat_cols] %>% t, Pf.gene$data[,Pf.gene$feat_cols] %>% t)
rownames(cr.n) <- Pf.cmpd$data$Metadata_broad_sample
colnames(cr.n) <- Pf.gene$data$Treatment
cr.melt.n <- melt(cr.n)

df <- cr.melt.n %>%
  filter(Var2 %in% c("KRAS_WT.1", "KRAS_G12V", "HRAS_G12V")) %>%
  group_by(Var1) %>%
  do(data.frame(WT_score = as.vector(.[which(.[,"Var2"] == "KRAS_WT.1"), "value"]), 
                MUT1_score = as.vector(.[which(.[,"Var2"] == "KRAS_G12V"), "value"]), 
                MUT2_score = as.vector(.[which(.[,"Var2"] == "HRAS_G12V"), "value"]))) %>%
  dplyr::rename(WT_score = value, 
                MUT_KRAS_score = value.1,
                MUT_HRAS_score = value.2) %>% 
  dplyr::arrange(-WT_score+(MUT_KRAS_score+MUT_HRAS_score)/2) %>%
  dplyr::mutate(WT_score = round(WT_score, 2), 
                MUT_KRAS_score = round(MUT_KRAS_score, 2), 
                MUT_HRAS_score = round(MUT_HRAS_score, 2)) %>%
  dplyr::left_join(., Pf.cmpd$data[, c("Metadata_broad_sample", "MOA", "CPD_NAME")], by = c("Var1" = "Metadata_broad_sample")) %>%
  dplyr::mutate(MUT_Score = (MUT_KRAS_score + MUT_HRAS_score)/2)
  

df %>% 
  filter(MUT_Score  > 0.35 & WT_score < 0.25 | 
           MUT_Score < -0.35 & WT_score > -0.25) %>% 
  print

df %>% 
  filter(MUT_Score  < 0.25 & WT_score > 0.35 | 
           MUT_Score > -0.25 & WT_score < -0.35) %>% 
  print

g <- ggplot(df, aes(y = MUT_Score, x = WT_score)) + geom_point()
ggsave("WT_vs_Mut.png", g)

```
```{r, eval = F}

cos.d <- function(x, y) {
  rx <- apply(x, 2, function(x) sum(x^2)^0.5)
  ry <- apply(y, 2, function(x) sum(x^2)^0.5)
  cx <- t(outer(rep(1, length(ry)), rx))
  cy <- t(outer(ry, rep(1, length(rx))))
  d <- (t(x) %*% y)/(cx * cy)
  return(d)
}

kras.wt <- Pf.gene$data %>% 
  filter(Treatment == "KRAS_WT.1") %>% select(one_of(Pf.gene$feat_cols)) %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("feature") %>%
  dplyr::rename(value_kras_wt = V1)

kras.g12v <- Pf.gene$data %>% 
  filter(Treatment == "KRAS_G12V") %>% select(one_of(Pf.gene$feat_cols)) %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("feature") %>%
  dplyr::rename(value_kras_mt = V1)

hras.g12v <- Pf.gene$data %>% 
  filter(Treatment == "HRAS_G12V") %>% select(one_of(Pf.gene$feat_cols)) %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("feature") %>%
  dplyr::rename(value_hras_mt = V1)

u <- kras.wt %>% 
  left_join(., kras.g12v, by = "feature") %>%
  left_join(., hras.g12v, by = "feature")

for (i in 2:4) {
  u[,i] <- u[,i]/(sum(abs(u[,i]))) * NROW(u)
}

ft.mt <- u %>% 
  arrange(-abs(value_kras_wt)) %>%
  filter(abs(value_kras_mt) > 1 & value_kras_wt/value_kras_mt < 0.1) %>%
  select(feature) %>%
  as.matrix() %>%
  as.vector()
#ft.rest <- setdiff(u$feature, ft.mt)
ft.rest <- u %>% 
  arrange(-abs(value_kras_wt)) %>%
  filter(abs(value_kras_mt) > 1 & value_kras_wt/value_kras_mt > 0.8) %>%
  select(feature) %>%
  as.matrix() %>%
  as.vector()

u %>% 
  filter(feature %in% ft.mt) %>% 
  arrange(-abs(value_kras_mt)) %>% 
  select(-value_hras_mt) %>% 
  mutate(value_kras_mt = round(value_kras_mt, 2),
         value_kras_wt = round(value_kras_wt, 2)) %>% 
  as.data.frame() %>% 
  htmlTable::htmlTable()

u %>% 
  filter(feature %in% ft.rest) %>% 
  arrange(-abs(value_kras_mt)) %>% 
  select(-value_hras_mt) %>% 
  mutate(value_kras_mt = round(value_kras_mt, 2),
         value_kras_wt = round(value_kras_wt, 2)) %>% 
  as.data.frame() %>% 
  htmlTable::htmlTable()

cr.n <- (cos.d(Pf.cmpd$data[,ft.mt] %>% t, Pf.gene$data[which(Pf.gene$data$Treatment == "KRAS_G12V"),ft.mt] %>% t))
rownames(cr.n) <- Pf.cmpd$data$Metadata_broad_sample

cr.p <- abs(cos.d(Pf.cmpd$data[,ft.rest] %>% t, Pf.gene$data[which(Pf.gene$data$Treatment == "KRAS_WT.1"),ft.rest] %>% t))
rownames(cr.p) <- Pf.cmpd$data$Metadata_broad_sample

colnames(cr.n) <- "score.spec.mt"
colnames(cr.p) <- "score.comm"

cr.n <- cr.n %>% as.data.frame() %>% tibble::rownames_to_column("compound ID")
cr.p <- cr.p %>% as.data.frame() %>% tibble::rownames_to_column("compound ID")

cr.all <- cr.n %>% 
  left_join(cr.p, by = "compound ID") %>% 
  mutate(score = score.spec.mt - sign(score.spec.mt) * score.comm) %>%
  left_join(., Pf.cmpd$data[,c("Metadata_broad_sample", "CPD_NAME", "MOA")], by = c("compound ID" = "Metadata_broad_sample"))

cr.all <- cr.all %>% 
  filter(abs(score.comm) < 0.1)

cr.all %>% filter(abs(score) > 0.5) %>% htmlTable::htmlTable()

```

