
```{r}

rm(list = ls())
library(dplyr)
library(stringr)
library(doParallel)
source("moa_evaluations.R")

doParallel::registerDoParallel(cores = 4)

whiten <- F
top.p <- 0.01

cdrp <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")
feats <- colnames(cdrp)
feats <- feats[which(!str_detect(feats, "Metadata_"))]

if (whiten) {
  cdrp.dmso <- readRDS("../results/master/2017-09-05_da5f3073/Pf_bio_new_all.rds")
  cdrp.dmso <- cdrp.dmso %>% filter(Metadata_ASSAY_WELL_ROLE == "mock") %>% select(one_of(feats))
  mn <- apply(cdrp.dmso, 2, mean)
  cv <- cov(cdrp.dmso)
  ev <- eigen(cv)
  eps <- 10^-1
  W <- diag((ev$values + eps)^-0.5) %*% t(ev$vectors)
  cdrp[, feats] <- t(W %*% (apply(cdrp[, feats], 1, function(x) (x - mn))))
}

brd.to.name <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
moa <- read.csv("../input/moas.txt", sep = "\t")

moa <- moa %>% 
  mutate(Name.cano = str_to_lower(Name)) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "-", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, " ", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\[", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\]", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\(", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\)", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\+", "")) 
  
cdrp.profiles <- cdrp %>% 
  group_by(Metadata_broad_sample) %>%
  summarise_at(.vars = feats, .funs = mean) %>%
  mutate(Metadata_broad_id_trunc = str_sub(Metadata_broad_sample, 1, 13)) %>%
  left_join(., brd.to.name, by = c("Metadata_broad_id_trunc" = "BROAD_CPD_ID")) %>% 
  filter(CPD_NAME != "")
  
cdrp.profiles <- cdrp.profiles %>% 
  mutate(Name.cano = str_to_lower(CPD_NAME)) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "-", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, " ", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\[", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\]", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\(", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\)", "")) %>%
  mutate(Name.cano = str_replace_all(Name.cano, "\\+", "")) 

moa2 <- readr::read_csv("../input/CDP2/MOA_annot2.csv")
moa2 <- moa2 %>% mutate(Name = ifelse(is.na(Name), CPD_NAME, Name))

cdrp.profiles <- cdrp.profiles %>%
  left_join(., moa2, by = "Metadata_broad_sample") %>%
  filter(!is.na(Name) & !is.na(MOA))

cdrp.profiles <- cdrp.profiles %>% 
  group_by(Metadata_broad_sample) %>%
  slice(1) %>%
  ungroup()

rownames(cdrp.profiles) <- cdrp.profiles$Metadata_broad_sample

same.moa <- function(x, y) {
  if (is.na(x) || is.na(y) || x == "" || y == "") 
    return(FALSE)
  xs <- str_split(x, ", ")[[1]]
  ys <- str_split(y, ", ")[[1]]
  return(any(xs %in% ys) | any(ys %in% xs))
}

same.moa <- Vectorize(same.moa)

cr.melt <- cdrp.profiles %>%
  select(one_of(feats)) %>%
  t %>%
  cor %>% 
  reshape2::melt() %>%
  left_join(., cdrp.profiles %>% select(-one_of(feats)), by = c("Var1" = "Metadata_broad_sample")) %>%
  left_join(., cdrp.profiles %>% select(-one_of(feats)), by = c("Var2" = "Metadata_broad_sample")) %>%
  mutate(same.moa = same.moa(MOA.x, MOA.y))

v11 <- cr.melt %>% 
  filter(as.character(Var1) < as.character(Var2)) %>%
  arrange(-value) %>%
  slice(1:round(n() * top.p)) %>%
  filter(same.moa) %>%
  NROW

v12 <- cr.melt %>% 
  filter(as.character(Var1) < as.character(Var2)) %>%
  arrange(-value) %>%
  slice(1:round(n() * top.p)) %>%
  filter(!same.moa) %>%
  NROW

v21 <- cr.melt %>% 
  filter(as.character(Var1) < as.character(Var2)) %>%
  arrange(-value) %>%
  slice((round(n() * top.p)+1):n()) %>%
  filter(same.moa) %>%
  NROW

v22 <- cr.melt %>% 
  filter(as.character(Var1) < as.character(Var2)) %>%
  arrange(-value) %>%
  slice((round(n() * top.p)+1):n()) %>%
  filter(!same.moa) %>%
  NROW

V <- rbind(c(v11, v12), c(v21, v22))

fisher.test(V, alternative = "greater")

cr <- cdrp.profiles %>%
  select(one_of(feats)) %>%
  t %>%
  cor

cr.melt %>% 
  filter(as.character(Var1) < as.character(Var2)) %>%
  arrange(-value) %>%
  slice(1:round(n() * 0.05)) %>%
  filter(same.moa) %>%
  group_by(MOA.x) %>%
  tally() %>%
  arrange(-n) %>%
  htmlTable::htmlTable()

rownames(V) <- c("top 1% connections", "the remainder of connections")
colnames(V) <- c("share a common MOA", "have distinct MOAs")

V %>% htmlTable::htmlTable()

```

```{r network view of data}

library(igraph)
k <- 4

sim_normalize <- function(sim_mat) {
  sim_mat_norm <- apply(sim_mat, 1, function(x) (ecdf(x)(x)))
  sim_mat_norm <- (sim_mat_norm + t(sim_mat_norm))/2
  rownames(sim_mat_norm) <- rownames(sim_mat)
  colnames(sim_mat_norm) <- colnames(sim_mat)
  return(sim_mat_norm)
}

cr <- cr.melt %>%
  reshape2::acast(Var1 ~ Var2, value.var = "value")

cr.norm <- sim_normalize(cr)

cr.melt <- cr.melt %>%
  select(-value) %>%
  left_join(., cr.norm %>% reshape2::melt(), by = c("Var1", "Var2")) 


moa.cnt <- moa2 %>% 
  filter(Metadata_broad_sample %in% cr.melt$Var1) %>% 
  group_by(MOA) %>% 
  tally

moa.adj.mat <- cr.melt %>% 
  left_join(., moa.cnt, by = c("MOA.x" = "MOA")) %>% 
  left_join(., moa.cnt, by = c("MOA.y" = "MOA")) %>% 
  filter(Var1 != Var2) %>%
  filter(n.x >= 6 & n.y >= 6) %>% 
  group_by(MOA.x, MOA.y) %>% 
  summarise(n.z = sum(value > 0.99)/n.x[1]/n.y[1]) %>%
  arrange(-n.z) %>%
  slice(1:k) %>%
  ungroup() %>%
  reshape2::acast(MOA.x ~ MOA.y, value.var = "n.z") %>%
  reshape2::melt() %>%
  mutate(value = ifelse(is.na(value), 0, value)) %>%
  reshape2::acast(Var1 ~ Var2)

all.names <- unique(c(rownames(moa.adj.mat), colnames(moa.adj.mat)))
moa.adj.mat.rep <- matrix(0, length(all.names), length(all.names))
rownames(moa.adj.mat.rep) <- all.names
colnames(moa.adj.mat.rep) <- all.names
moa.adj.mat.rep[rownames(moa.adj.mat), colnames(moa.adj.mat)] <- moa.adj.mat

symmetrize <- function(a) {
  u <- apply(rbind(a[lower.tri(a)], a[upper.tri(a)]), 2, max)
  a[lower.tri(a)] <- u
  a[upper.tri(a)] <- u
  return(a)
}

moa.adj.mat.rep <- symmetrize(moa.adj.mat.rep)
moa.adj.mat <- moa.adj.mat.rep

gr <- graph_from_adjacency_matrix(moa.adj.mat, mode = "undirect", weighted = T)

#l <- layout_with_lgl(gr)
l <- layout_with_fr(gr)

quartz(width = 20, height = 15)
plot(gr, vertex.size = 2, edge.arrow.mode = 0, layout = l, vertex.frame.color = NA, vertex.label.cex = 1, edge.width = E(gr)$weight * 20)
dev.print(device = pdf, "graph.pdf")

```

```{r, eval=F}

hcl <- hclust(as.dist(1 - cr), method = "average")
ct <- cutree(hcl, h = 1 - 0.5)
cls <- c()
for (i in 1:max(ct)) {
  cls <- c(cls, list(names(which(ct == i))))
}

for (i in 1:length(cls)) {
  moas.in.cls <- cdrp.profiles %>%
    filter(Metadata_broad_sample %in% cls[[i]]) %>%
    select(MOA) %>%
    as.matrix() %>%
    as.vector() %>%
    lapply(., function(x) str_split(x, ", ")[[1]]) %>%
    unlist 
    
    moa.freq <- prop.table(table(moas.in.cls)) * length(moas.in.cls)
    df <- as.data.frame(moa.freq)
    colnames(df) <- c(sprintf("MOA in cluster %d", i), "n")
    df <- df %>% arrange(-n)
    knitr::kable(df) %>% print
}

```

```{r, results='asis'}

randomize <- F
cr.norm <- apply(cr, 1, function(x) (ecdf(x)(x)))
cr.norm <- (cr.norm + t(cr.norm))/2
rownames(cr.norm) <- colnames(cr.norm)

if (randomize) {
  m <- sample(rownames(cr.norm), NROW(cr.norm))
  rownames(cr.norm) <- m
  colnames(cr.norm) <- m
}

is.in <- function(x, y) {
  z <- str_split(x, ", ")[[1]]
  return(y %in% z)
}

is.in <- Vectorize(is.in)

plot.within.MOA <- function(MOA.name, cor.thr = 0.90, plot.mat = F, verbose = F) {
  MOA.name <- MOA.name %>% as.matrix() %>% as.vector()
  
  brds <- cdrp.profiles %>% 
    filter(is.in(MOA, MOA.name)) %>%
    select(Metadata_broad_sample) %>% 
    as.matrix() %>% 
    as.vector()
  
  other.brds <- cdrp.profiles %>% 
    filter(!str_detect(MOA, MOA.name)) %>%
    select(Metadata_broad_sample) %>% 
    as.matrix() %>% 
    as.vector()

  if (plot.mat) {
    corrplot::corrplot(cr.norm[brds, brds], 
                       method = "color", 
                       order = "hclust", 
                       hclust.method = "average", 
                       is.corr = F, 
                       cl.lim = c(0, 1), 
                       col = colorRampPalette(c("green", "white", "darkred", "white", "darkblue"))(200))
  }
  
  x <- cr.norm[brds, brds] %>% as.dist() %>% as.vector()
  y <- cr.norm[brds, other.brds] %>% as.vector()
  
  z1 <- x
  z2 <- y
  
  v11 <- which(z1 > cor.thr) %>% length
  v12 <- which(z1 < cor.thr) %>% length
  v21 <- which(z2 > cor.thr) %>% length
  v22 <- which(z2 < cor.thr) %>% length
  
  V <- rbind(c(v11, v12), c(v21, v22))
  
  if (verbose) {
    print(V)
  }
  
  fsh <- fisher.test(V, alternative = "greater")
  return(data.frame(p.value = fsh$p.value, 
                    odds.ratio = fsh$estimate))
}

sig.moas <- cdrp.profiles %>%
  group_by(MOA) %>% 
  tally %>% 
  arrange(-n) %>% 
  filter(n >= 2 & MOA != "") %>% 
  select(MOA) %>%
  as.matrix() %>%
  as.vector() %>%
  lapply(., function(x) str_split(x, ", ")[[1]]) %>%
  unlist %>%
  unique()

sep.MOA <- function(x) {
  return(str_split(x[,"MOA"], ", ")[[1]])
}

MOA.list <- cdrp.profiles %>%
  select(Metadata_broad_sample, MOA) %>%
  group_by(Metadata_broad_sample) %>%
  do(data.frame(MOA.sep = sep.MOA(.))) %>%
  dplyr::rename(MOA = MOA.sep)

df <- data.frame(MOA = sig.moas)
df <- df %>% 
  group_by(MOA) %>%
  do(data.frame(plot.within.MOA(.[,"MOA"]))) %>%
  ungroup()
  
moa.corr <- df %>% as.data.frame()

moa.corr <- moa.corr %>% 
  left_join(., MOA.list %>% 
            group_by(MOA) %>% 
            tally %>% 
            ungroup(), 
          by = "MOA") %>%
  filter(n >= 6) %>%
  mutate(p.value = p.adjust(p.value, method = "BH")) 

moa.corr %>%
  mutate(is.consistent = p.value < 0.05) %>%
  arrange(p.value) %>%
  mutate(p.value = round(-log(p.value)/log(10), 2)) %>%
  rename(`-log(adj. p.value)` = p.value) %>%
  mutate(odds.ratio = round(odds.ratio, 2)) %>%
  htmlTable::htmlTable()

```

```{r}

metadata <- cdrp.profiles %>%
  select(Metadata_broad_sample, MOA) %>%
  rename(Metadata_moa = MOA) %>% 
  distinct()

moas.score <- moa_recall(cr, metadata = metadata, n.cores = 3, N = 10000)

moas.score <- moas.score %>% filter(!is.na(p.value))

#moas.score <- moas.score %>% mutate(p.value = p.adjust(p.value, method = "BH"))

moas.score %>% 
  left_join(., MOA.list %>% 
            group_by(MOA) %>% 
            tally %>% 
            ungroup(), 
          by = "MOA") %>%
  filter(n >= 2) %>%
  #mutate(p.value = p.adjust(p.value, "BH")) %>%
  filter(p.value < 0.05) %>%
  arrange(p.value) %>%
  htmlTable::htmlTable()

```

```{r, eval=F}

gene.compound.cr <- readRDS("../results/master/2017-05-02_9796dc34/cr_melt_cp.rds")

extremest.value <- function(x) {
  mn <- min(x)
  mx <- max(x)
  if (abs(mn) > mx) {
    return(mn)
  } else {
    return(mx)
  }
} 

count.sig <- function(x, thr = 0.5) {
  y <- length(which(x >= thr))
  z <- length(which(x <= -thr))
  
  ifelse(y > z, y, -z)
}

moa.names <- moa.corr %>% 
  filter(p.value < 0.05) %>%
  select(MOA) %>% 
  as.matrix() %>%
  as.vector()

addn <- MOA.list %>%
  group_by(MOA) %>%
  tally() %>%
  filter(n < 6 & n >= 2) %>%
  select(MOA) %>%
  as.matrix() %>%
  as.vector()

#moa.names <- c(moa.names, addn)

for (MOA.name in moa.names) {
  brds <- cdrp.profiles %>% 
    filter(str_detect(MOA, MOA.name)) %>%
    select(CPD_NAME.x) %>% 
    mutate(CPD_NAME = str_to_lower(CPD_NAME.x)) 
  
    brds1 <- brds %>% mutate(CPD_NAME = str_replace(CPD_NAME, "-", ""))
    brds2 <- brds %>% mutate(CPD_NAME = str_replace(CPD_NAME, "-", " "))
    brds <- rbind(brds1, brds2, brds) %>% as.matrix() %>% as.vector() %>% unique
    
    cmpd.num <- gene.compound.cr %>% 
      filter(Var1 %in% brds) %>% 
      group_by(Var2) %>% 
      tally %>% 
      slice(1) %>%
      select(n) %>% 
      as.matrix() %>%
      as.vector()

  if (length(cmpd.num) > 0 && cmpd.num > 0) {    
    
    gene.compound.cr %>% 
      filter(Var1 %in% brds) %>% 
      group_by(Var2) %>% 
      summarise(value = count.sig(value, 0.45)) %>%
      arrange(-value) %>% 
      slice(c(1:5, (n()-4):n())) %>% 
      rename(gene = Var2) %>% 
      rename(!!sprintf("max corr. to %s in %d cmpd.", MOA.name, cmpd.num) := !!"value") %>%
      knitr::kable() %>%
      print
  }
}

```

```{r}

rep.moa <- function(x, colname) {
  if (!is.na(x[,colname])) {
    moas <- str_split(x[,colname] %>% as.character(), ", ")[[1]]
    df <- data.frame(cl = moas, x[, setdiff(colnames(x), colname)])
    u <- colnames(df)
    u[1] <- colname
    colnames(df) <- u
    return(df)
  } 
  return(x)
}

cr.melt.exp <- cr.melt %>% 
  mutate(MOA.x = as.character(MOA.x), MOA.y = as.character(MOA.y)) %>%
  mutate(rownm = 1:n()) %>%
  filter(as.character(Var1) < as.character(Var2)) %>% 
  arrange(-value) %>% 
  slice(1:round(n() * 0.05)) %>% 
  group_by(rownm) %>%
  do(data.frame(rep.moa(.[], "MOA.y"))) %>%
  ungroup() %>%
  select(-rownm) %>%
  mutate(rownm = 1:n()) %>%
  group_by(rownm) %>%
  do(data.frame(rep.moa(.[], "MOA.x")))

moas.list <- moa.corr %>% mutate(is.consistent = p.value < 0.05) %>% filter(is.consistent) %>% select(MOA) %>% as.matrix() %>% as.vector() %>% unique

cf <- matrix(0, nrow = length(moas.list), ncol = length(moas.list))
rownames(cf) <- moas.list
colnames(cf) <- moas.list

cr.n <- cr.melt.exp %>%
  group_by(MOA.x, MOA.y) %>%
  tally()

cx <- cf %>%
  reshape2::melt() %>%
  left_join(., cr.n, by = c("Var1" = "MOA.x", "Var2" = "MOA.y")) %>%
  mutate(value = ifelse(is.na(n), 0, n)) %>%
  select(-n) %>%
  reshape2::acast(Var1 ~ Var2)
  
i <- which(apply(cx, 1, sum) > 0)
cx <- cx[i, i]

v <- diag(apply(cx, 1, sum)^-0.5) %*% cx %*% diag(apply(cx, 1, sum)^-0.5)
colnames(v) <- colnames(cx)
rownames(v) <- rownames(cx)
#v[v < 0.10] <- 0
#v[v > 0.5] <- 0.5

od <- order(diag(v), decreasing = T)
v <- v[od, od]

corrplot::corrplot(v, method = "color", is.corr = F, tl.cex = 0.5)

```

```{r}

thr <- 0.97

gene.compound.cr <- readRDS("../results/master/2017-05-02_9796dc34/cr_melt_cp.rds")
cr.gc <- gene.compound.cr %>% 
  group_by(Var1, Var2) %>%
  slice(1) %>%
  ungroup() %>%
  reshape2::acast(Var1 ~ Var2)

cr.norm.gc <- apply(cr.gc, 2, function(x) (ecdf(x)(x))) 
rownames(cr.norm.gc) <- rownames(cr.gc)
colnames(cr.norm.gc) <- colnames(cr.gc)

gene.compound.cr <- cr.norm.gc %>% 
  reshape2::melt()

gene.compound.cr.ext <- gene.compound.cr %>%
  left_join(., cdrp.profiles %>% 
              select(CPD_NAME.x, Metadata_broad_sample, MOA, Target) %>%
              mutate(CPD_NAME.x = ifelse(str_detect(CPD_NAME.x, "BRD-"), 
                                         Metadata_broad_sample, 
                                         str_to_lower(CPD_NAME.x))),  
            by = c("Var1" = "CPD_NAME.x")) %>%
  group_by(Var1, Var2) %>%
  slice(1) %>%
  ungroup() 

v11 <- gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(value > thr | value < 1 - thr) %>%
  NROW

v12 <- gene.compound.cr.ext %>%
  filter(! (str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2)) %>%
  filter(value > thr | value < 1 - thr) %>% 
  NROW

v21 <- gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(! (value > thr | value < 1 - thr)) %>% 
  NROW

v22 <- gene.compound.cr.ext %>%
  filter(!(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2)) %>%
  filter(! (value > thr | value < 1 - thr)) %>% 
  NROW

V <- rbind(c(v11, v12), c(v21, v22))

fisher.test(V, alternative = "greater") %>% print

gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(value > thr | value < 1 - thr) %>%
  arrange(Var2) %>%
  htmlTable::htmlTable()

```

```{r}

source("getPPI.R")
thr <- 0.97

gene.compound.cr <- readRDS("../results/master/2017-05-02_9796dc34/cr_melt_cp.rds")
cr.gc <- gene.compound.cr %>% 
  group_by(Var1, Var2) %>%
  slice(1) %>%
  ungroup() %>%
  reshape2::acast(Var1 ~ Var2)

cr.norm.gc <- apply(cr.gc, 2, function(x) (ecdf(x)(x))) 
rownames(cr.norm.gc) <- rownames(cr.gc)
colnames(cr.norm.gc) <- colnames(cr.gc)

gene.compound.cr <- cr.norm.gc %>% 
  reshape2::melt()

gene.compound.cr.ext <- gene.compound.cr %>%
  left_join(., cdrp.profiles %>% 
              select(CPD_NAME.x, Metadata_broad_sample, MOA, Target) %>%
              mutate(CPD_NAME.x = ifelse(str_detect(CPD_NAME.x, "BRD-"), 
                                         Metadata_broad_sample, 
                                         str_to_lower(CPD_NAME.x))),  
            by = c("Var1" = "CPD_NAME.x")) %>%
  group_by(Var1, Var2) %>%
  slice(1) %>%
  ungroup() 


expand.prot.target <- function(target) {
  target <- target %>% as.character() %>% as.matrix() %>% as.vector()
  if (is.na(target)) {
    return(target)
  }
  
  ppis <- get.all.interacting.proteins(str_split(target, ", ")[[1]])
  if (is.null(ppis)) {
    return(NA)
  }
  
  return(ppis %>% 
           select(Protein.1, Protein.2) %>% 
           group_by(Protein.1, Protein.2) %>%
           tally() %>%
           filter(n >= 5) %>%
           ungroup() %>%
           as.matrix %>% as.vector() %>% unique() %>% paste(., collapse = ", "))
}

cmpd.targ <- gene.compound.cr.ext %>% 
  select(Var1, Target) %>% 
  distinct() %>%
  group_by(Var1) %>%
  do(data.frame(Target = expand.prot.target(.[,"Target"])))
  
gene.compound.cr.ext <- gene.compound.cr.ext %>%
  select(-Target) %>%
  left_join(., cmpd.targ %>% ungroup(), by = "Var1")

v11 <- gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(value > thr | value < 1 - thr) %>%
  NROW

v12 <- gene.compound.cr.ext %>%
  filter(! (str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2)) %>%
  filter(value > thr | value < 1 - thr) %>% 
  NROW

v21 <- gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(! (value > thr | value < 1 - thr)) %>% 
  NROW

v22 <- gene.compound.cr.ext %>%
  filter(!(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2)) %>%
  filter(! (value > thr | value < 1 - thr)) %>% 
  NROW

V <- rbind(c(v11, v12), c(v21, v22))

fisher.test(V, alternative = "greater") %>% print

gene.compound.cr.ext %>%
  filter(str_detect(Target, paste0(Var2, ", ")) | 
           str_detect(Target, paste0(", ", Var2)) |
           str_detect(Target, paste0(", ", Var2, ", ")) | 
           Target == Var2) %>%
  filter(value > thr | value < 1 - thr) %>%
  select(-Target) %>%
  arrange(Var2) %>%
  htmlTable::htmlTable()

```

