---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}

library(cytominer)
library(dplyr)
source("read_dataset.R")

Pf <- read.dataset("Repurposing", dose.closest = 10)

single.cell.1 <- readRDS("../results/master/2017-07-17_e204cf3a/Repurposing_dmso_single_cell.rds")
single.cell.3 <- readRDS("../results/master/2017-07-13_e204cf3a__1/Repurposing_dmso_single_cell.rds")

cl <- intersect(colnames(single.cell.1), colnames(single.cell.3))
cl <- intersect(Pf$feat_cols, cl)

single.cell.1 <- single.cell.1 %>% select(one_of(cl))
single.cell.3 <- single.cell.3 %>% select(one_of(cl))
single.cell <- rbind(single.cell.1, single.cell.3)

single.cell <- scale(single.cell)
single.cell <- as.data.frame(single.cell)

```

```{r}

fts <- entropy_feature_selection(population = single.cell, variables = colnames(single.cell), n_feature = 300)

```

```{r}

evaluate_feat_set <- function(Pf, Px, feats, same.moa.df) {
  top.p <- 0.01
  
  cr.melt <- Px %>%
    select(one_of(feats)) %>%
    t %>%
    cor %>% 
    reshape2::melt() %>%
    cbind(., same.moa.df)
  
  cr.melt.sorted <- cr.melt %>% 
    filter(as.character(Var1) < as.character(Var2)) %>%
    arrange(-value)
  
  v11 <- cr.melt.sorted %>%
    slice(1:round(n() * top.p)) %>%
    filter(same.moa) %>%
    NROW
  
  v12 <- cr.melt.sorted %>%
    slice(1:round(n() * top.p)) %>%
    filter(!same.moa) %>%
    NROW
  
  v21 <- cr.melt.sorted %>%
    slice((round(n() * top.p)+1):n()) %>%
    filter(same.moa) %>%
    NROW
  
  v22 <- cr.melt.sorted %>%
    slice((round(n() * top.p)+1):n()) %>%
    filter(!same.moa) %>%
    NROW
  
  V <- rbind(c(v11, v12), c(v21, v22))
  
  fisher.test(V, alternative = "greater")
}  

```

```{r}

N <- 100

Px <- Pf$data %>% 
  group_by(Metadata_broad_sample, Metadata_moa) %>%
  summarise_at(.vars = Pf$feat_cols, .funs = "mean") %>%
  ungroup() %>%
  group_by(Metadata_broad_sample, Metadata_moa) %>%
  slice(1) %>%
  ungroup

rownames(Px) <- Px$Metadata_broad_sample

same.moa <- function(x, y) {
  if (is.na(x) || is.na(y) || x == "" || y == "") 
    return(FALSE)
  xs <- str_split(x, "\\|")[[1]]
  ys <- str_split(y, "\\|")[[1]]
  return(any(xs %in% ys) | any(ys %in% xs))
}

same.moa <- Vectorize(same.moa)

same.moa.df <- Px %>%
  select(one_of(Pf$feat_cols)) %>%
  t %>%
  cor %>% 
  reshape2::melt() %>%
  left_join(., Px %>% 
              select(Metadata_broad_sample, Metadata_moa), by = c("Var1" = "Metadata_broad_sample")) %>%
  left_join(., Px %>% 
              select(Metadata_broad_sample, Metadata_moa), by = c("Var2" = "Metadata_broad_sample")) %>%
  mutate(same.moa = same.moa(Metadata_moa.x, Metadata_moa.y)) %>%
  select(same.moa)
  
f1 <- evaluate_feat_set(Pf = Pf, Px = Px, Pf$feat_cols, same.moa.df)
ors <- data.frame(feat.no = c(), odds.ratio = c(), odds.ratio.std = c())

for (i in seq(from = 50, to = 300, by = 5)) {
  f2 <- evaluate_feat_set(Pf = Pf, Px = Px, feats = fts$feats[1:i], same.moa.df)  
  ors <- rbind(ors, data.frame(feat.no = i, odds.ratio = unname(f2$estimate), odds.ratio.std = 0))
}

ors.r <- data.frame(feat.no = c(), odds.ratio = c())
for (j in 1:N) {
  for (i in seq(from = 50, to = 300, by = 5)) {
    f2 <- evaluate_feat_set(Pf = Pf, Px = Px, feats = sample(Pf$feat_cols, i), same.moa.df)  
    ors.r <- rbind(ors.r, data.frame(feat.no = i, odds.ratio = unname(f2$estimate)))
  }
}

ors.r <- ors.r %>%
  group_by(feat.no) %>%
  summarise(odds.ratio.mean = mean(odds.ratio), odds.ratio.std = sd(odds.ratio)/N^0.5) %>%
  ungroup() %>%
  rename(odds.ratio = odds.ratio.mean)

```

```{r}

library(ggplot2)

df.1 <- ors %>%
  mutate(method = "SR-SVD")

df.2 <- ors.r %>%
  mutate(method = "random selection")

df <- rbind(df.1, df.2)

g <- ggplot(df, aes(x = feat.no, y = odds.ratio, color = method)) + 
  geom_line() + geom_errorbar(aes(ymin = odds.ratio - odds.ratio.std, 
                                                 ymax = odds.ratio + odds.ratio.std)) + 
  xlab("Number of features") + 
  ylab("Fold of enrichment for top 1 percent conn.")

g

ggsave("Repurposing_eval.png", g)

```

