---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(plyr)
library(reshape2)
library(magrittr)
library(htmlTable)
  
source("rep.corr.func.R")
permute.moas <- F
seed.moa <- -8     ## ignore, if permute.moas is False
hit.sel.quant <- 0.95
just.bioactives <- T

base.dir <- "2016-07-20_90b7bb86"
corr.type <- "pearson"
just.common.cmpds <- T

if (just.bioactives) {
  Pf <- readRDS("../results/master/2017-06-02_4df9ed93/Pf_bio_new.rds")
} else {
  Pf.1 <- readRDS("../results/master/2017-06-02_4df9ed93/Pf_bio_new.rds")
  Pf.2 <- readRDS("../results/master/2017-06-02_4df9ed93/Pf_DOS_new.rds")
  Pf <- rbind(Pf.1, Pf.2)
}

feat <- Pf %>% 
          dplyr::select(-dplyr::contains("Metadata_")) %>% 
          colnames()

u <- rep.cor(list(data = Pf,
             feat_cols = feat,
             factor_cols = setdiff(colnames(Pf), feat)),
        grp.var = "Metadata_broad_sample", 
        feat.var = feat)
thr <- non.rep.cor(list(data = Pf,
             feat_cols = feat,
             factor_cols = setdiff(colnames(Pf), feat)),
        grp.var = "Metadata_broad_sample", 
        feat.var = feat, 
        quant = hit.sel.quant)

strongs <- u$Metadata_broad_sample[which(u$cr > thr)]
Pf %<>% dplyr::filter(Metadata_broad_sample %in% strongs)

metadata.ext <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
brd.full <- unique(Pf$Metadata_broad_sample)
brds <- lapply(brd.full, function(x) paste(str_split(x,
                                                                             "-")[[1]][1:2], 
                                                   sep = "-", collapse = "-")) %>% unlist()
brd.mapping <- data.frame(BROAD_CPD_ID = brds, 
                          Image_Metadata_BROAD_ID = brd.full)
metadata.ext %<>% 
  dplyr::select(BROAD_CPD_ID, CPD_NAME) %>% 
  dplyr::filter(BROAD_CPD_ID %in% brds) %>%
  dplyr::mutate(CPD_NAME = ifelse(str_detect(CPD_NAME, "BRD-"), "", CPD_NAME)) %>%
  dplyr::inner_join(., brd.mapping, by = "BROAD_CPD_ID") %>%
  dplyr::select(-BROAD_CPD_ID)

metadata <- data.frame(Metadata_broad_sample = unique(Pf$Metadata_broad_sample))
metadata %<>% 
  dplyr::left_join(., metadata.ext, by = c("Metadata_broad_sample" = "Image_Metadata_BROAD_ID"))

Pf %<>% dplyr::left_join(., metadata, by = "Metadata_broad_sample")

Pf %<>% dplyr::select(one_of(c(feat, "Metadata_broad_sample", "CPD_NAME"))) %>%
  dplyr::group_by(Metadata_broad_sample, CPD_NAME) %>%
  dplyr::summarise_each(funs("mean"))

Pf %<>% dplyr::mutate(CPD_NAME = str_to_lower(CPD_NAME))
Pf %<>% dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME, "-", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, " ", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\(", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\)", "")) 
  
MOA <- read.csv("../input/moas.txt", sep = "\t")
MOA %<>% dplyr::mutate(Name = str_to_lower(Name)) %>%
  dplyr::mutate(Name_san = str_replace_all(Name, "-", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, " ", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\(", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\)", "")) 

Pf %<>% dplyr::left_join(., MOA, by = c("CPD_NAME_san" = "Name_san"))
meta.col <- setdiff(colnames(Pf), feat)
Pf.cdrp <- list(data = Pf, feat_cols = feat, factor_cols = meta.col)
saveRDS(Pf.cdrp, "Pf_annotated.rds")

############

source("rep.corr.func.R")

load("../input/Gustafsdottir/Initial_analysis.RData")
MOAs <- read.csv("../input/Gustafsdottir/MOAs.csv")
Pf.full.plate.norm$data %<>% 
  dplyr::left_join(., 
                   MOAs, 
                   by = c("Image_Metadata_SOURCE_COMPOUND_NAME" = "Name"))

Pf.full.plate.norm$factor_cols <- c(Pf.full.plate.norm$factor_cols, 
                                    colnames(MOAs)) %>% unique()

thr <- non.rep.cor(Pf.full.plate.norm,
                   "Image_Metadata_BROAD_ID", 
                   Pf.full.plate.norm$feat_cols, 
                   quant = hit.sel.quant)

u <- rep.cor(Pf.full.plate.norm,
                   "Image_Metadata_BROAD_ID", 
                   Pf.full.plate.norm$feat_cols)

strong.trt <- u$Image_Metadata_BROAD_ID[which(u$cr > thr)]

sprintf("Hit ratio (compound-concentrations) : %f%%", round(length(strong.trt)/NROW(u) * 100))

Pf.full.plate.norm$data %<>% dplyr::filter(Image_Metadata_BROAD_ID %in% strong.trt)

Pf.full.plate.norm$data %<>% 
  dplyr::select(one_of(c(Pf.full.plate.norm$feat_cols, 
                         "Image_Metadata_BROAD_ID",
                         "MOA",
                         "Image_Metadata_SOURCE_COMPOUND_NAME",
                         "Target"))) %>%
  dplyr::group_by(Image_Metadata_BROAD_ID, 
                  MOA,
                  Image_Metadata_SOURCE_COMPOUND_NAME,
                  Target) %>% 
  dplyr::summarise_each(funs("mean")) %>% 
  dplyr::ungroup() #%>%
  #dplyr::filter(MOA != "" &
  #                !is.na(MOA))

Pf.gust <- Pf.full.plate.norm
Pf.gust$factor_cols <- c("Image_Metadata_BROAD_ID",
                         "MOA",
                         "Image_Metadata_SOURCE_COMPOUND_NAME",
                         "Target")

```

```{r}

f1 <- Pf.cdrp$feat_cols

f2 <- colnames(Pf.gust$data)
f2 <- str_replace_all(f2, "Syto", "RNA")
f2 <- str_replace_all(f2, "Hoechst", "DNA")
f2 <- str_replace_all(f2, "Ph_golgi", "AGP")
f2 <- str_replace_all(f2, "_3", "_3_0")
f2 <- str_replace_all(f2, "_5", "_5_0")
colnames(Pf.gust$data) <- f2
Pf.gust$feat_cols <- setdiff(f2, Pf.gust$factor_cols)
f2 <- Pf.gust$feat_cols

f <- intersect(f1, f2)

Pf.cdrp$feat_cols <- f
Pf.gust$feat_cols <- f

Pf.cdrp$data <- Pf.cdrp$data[,c(Pf.cdrp$factor_cols, Pf.cdrp$feat_cols)]
Pf.gust$data <- Pf.gust$data[,c(Pf.gust$factor_cols, Pf.gust$feat_cols)]

print(length(Pf.cdrp$feat_cols))
print(NROW(Pf.cdrp$data))
print(length(Pf.gust$feat_cols))
print(NROW(Pf.gust$data))


```

```{r}

cmpd1 <- Pf.cdrp$data$CPD_NAME %>% str_to_lower()
cmpd2 <- Pf.gust$data$Image_Metadata_SOURCE_COMPOUND_NAME %>% str_to_lower()

cmpd <- intersect(cmpd1, cmpd2)

Pf.cdrp$data %<>%
  dplyr::filter(str_to_lower(CPD_NAME) %in% cmpd) %>%
  dplyr::mutate(MOA = str_to_lower(CPD_NAME))

Pf.gust$data %<>%
  dplyr::filter(str_to_lower(Image_Metadata_SOURCE_COMPOUND_NAME) %in% cmpd) %>%
  dplyr::mutate(MOA = str_to_lower(Image_Metadata_SOURCE_COMPOUND_NAME))

dim(Pf.cdrp$data)
dim(Pf.gust$data)

```

```{r}

cr <- cor(Pf.gust$data[,Pf.gust$feat_cols] %>% t, 
          Pf.cdrp$data[,Pf.cdrp$feat_cols] %>% t, 
          method = corr.type)

colnames(cr) <- Pf.cdrp$data$Metadata_broad_sample
rownames(cr) <- Pf.gust$data$Image_Metadata_BROAD_ID

cr.melt <- cr %>% melt
crx <- cr

```

```{r}

cr.melt.ext <- cr.melt %>% 
  dplyr::left_join(., unique(Pf.cdrp$data[,c("Metadata_broad_sample",
                                      "CPD_NAME",
                                      "MOA")]), 
                   by = c("Var2" = "Metadata_broad_sample")) %>%
  dplyr::left_join(., unique(Pf.gust$data[,c("Image_Metadata_BROAD_ID",
                                             "Image_Metadata_SOURCE_COMPOUND_NAME",
                                             "MOA")]), 
                   by = c("Var1" = "Image_Metadata_BROAD_ID"))

```

```{r}

cr.melt.ext %<>% 
  dplyr::filter(!is.infinite(value) & 
                  !is.na(MOA.x) & 
                  MOA.x != "")

matching.moas <- function(moa1, moa2) {
  m1 <- str_split(moa1, ", ")[[1]]  
  m2 <- str_split(moa2, ", ")[[1]]  
  any(m1 %in% m2)
}

matching.moas <- Vectorize(matching.moas)

cr.melt.ext2 <- cr.melt.ext %>% 
  dplyr::mutate(match = matching.moas(MOA.x, MOA.y))

```

```{r}

cr.melt.ext2.sor <- cr.melt.ext2 %>% 
  dplyr::arrange(-value) %>%
  dplyr::filter(!is.na(match)) %>% dplyr::ungroup()

n <- round(0.01 * NROW(cr.melt.ext2.sor))

v11 <- cr.melt.ext2.sor %>% 
  dplyr::slice(1:n) %>%
  dplyr::select(match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v12 <- cr.melt.ext2.sor %>% 
  dplyr::slice(1:n) %>%
  dplyr::select(match) %>%
  dplyr::mutate(match = !match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v21 <- cr.melt.ext2.sor %>% 
  dplyr::slice((n+1):NROW(cr.melt.ext2.sor)) %>%
  dplyr::select(match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v22 <- cr.melt.ext2.sor %>% 
  dplyr::slice((n+1):NROW(cr.melt.ext2.sor)) %>%
  dplyr::select(match) %>%
  dplyr::mutate(match = !match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)

V <- rbind(c(v11, v12), c(v21, v22))
fisher.test(V, alternative = "greater") %>% print

```

```{r}

k <- 3
N <- 100

d <- cr.melt.ext2.sor %>% 
  dplyr::group_by(Var2, MOA.x) %>%
  dplyr::slice(1:k) %>%
  dplyr::summarise(success = any(match)) %>% 
  dplyr::filter(success) 
  
ns <- c()

for (i in 1:N) {
  n <- d.null <- cr.melt.ext2.sor %>% 
    dplyr::group_by(Var2, MOA.x) %>%
    dplyr::sample_n(k) %>%
    dplyr::summarise(success = any(match)) %>% 
    dplyr::filter(success) %>%
    NROW
  
  ns <- c(ns, n)
}
  
print(NROW(d)/length(unique(cr.melt.ext2.sor$Var2)))
print(mean(ns)/length(unique(cr.melt.ext2.sor$Var2)))
print(NROW(d)/mean(ns))

```

```{r}

k <- 3
N <- 100

d <- cr.melt.ext2.sor %>% 
  dplyr::group_by(Var1, MOA.y) %>%
  dplyr::slice(1:min(k, NROW(.))) %>%
  dplyr::summarise(success = any(match)) %>% 
  dplyr::filter(success) 
  
ns <- c()

for (i in 1:N) {
  n <- d.null <- cr.melt.ext2.sor %>% 
    dplyr::sample_frac(1) %>%
    dplyr::group_by(Var1, MOA.y) %>%
    dplyr::slice(1:min(k, NROW(.))) %>%
    dplyr::summarise(success = any(match)) %>% 
    dplyr::filter(success) %>%
    NROW
  
  ns <- c(ns, n)
}
  
print(NROW(d)/length(unique(cr.melt.ext2.sor$Var1)))
print(mean(ns)/length(unique(cr.melt.ext2.sor$Var1)))
print(NROW(d)/mean(ns))

```

```{r}

thr <- cr.melt.ext2 %>% 
  dplyr::filter(!match) %>%
  dplyr::select(value) %>%
  as.matrix() %>% 
  as.vector() %>%
  quantile(., 0.95)

d <- cr.melt.ext2 %>%
  dplyr::filter(match & value > thr) %>%
  NROW

print(d/sum(cr.melt.ext2$match))

```

