```{r}

library(dplyr)
library(stringr)
library(magrittr)
library(tidyr)
library(purrr)
library(foreach)
library(doMC)
library(ggplot2)
source("rep.corr.func.R")
just.strongs <- F
remove.untreated <- F

doMC::registerDoMC(64)

process.plate <- function(plate.data) {
  c <- plate.data
  c %<>% unique
  
  feats <- colnames(c) %>% 
            data.frame(features = .) %>%
            dplyr::filter(!str_detect(features, "Metadata_")) %>%
            as.matrix() %>% as.vector()
  metas <- setdiff(colnames(c), feats)
  
  feats.to.retain  <- c %>% 
                        dplyr::select(one_of(feats)) %>% 
                        purrr::map(function(x) (sd(x) == 0 | any(is.na(x)))) %>% 
                        as.data.frame() %>%
                        tidyr::gather(key = "feature") %>%
                        dplyr::filter(!value) %>%
                        dplyr::select(feature) %>%
                        as.matrix() %>%
                        as.vector()
  c %<>% dplyr::select(one_of(c(feats.to.retain, metas)))
  feats <- feats.to.retain
  
  c %>% select(one_of(feats)) %>% 
    apply(., 1, function(x) any(is.na(x) | is.infinite(x) | is.nan(x))) %>%
    any %>%
    ifelse(., "some bad rows", "all ok.") %>%
    print
  
  v <- c %>% 
    dplyr::filter(Metadata_ASSAY_WELL_ROLE == "mock") %>%
    dplyr::select(one_of(feats)) %>%
    purrr::map(function(x) c(mean(x, na.rm = T), sd(x, na.rm = T))) %>% as.data.frame %>% as.matrix()
  
  c.nrm <- c
  c.nrm[,feats] <- c[,feats] %>% 
    scale(., center = (v[1, feats]), scale = as.vector(v[2, feats]))

  i <- c.nrm[,feats] %>% apply(., 2, function(x) !any(is.na(x)))
  c.nrm <- c.nrm[,c(feats[i], metas)]
  
  return(c.nrm)
}

```

```{r}

lst <- list.dirs("../../../backend/CDRP")
profiles <- foreach (i = lst[2:length(lst)]) %dopar% {
  pl <- str_split(i, "/")[[1]]
  pl <- pl[length(pl)]
  fl <- sprintf("%s/%s_augmented.csv", i, pl)
  if (file.exists(fl)) {
    c <- readr::read_csv(fl)  
    process.plate(c)
  } else {
    return(NULL)
  }
}

feat.comm <- lapply(profiles, function(x) colnames(x)) %>% 
  unlist() %>%
  data.frame(feature = .) %>% 
  group_by(feature) %>% 
  tally %>%
  filter(n == max(n)) %>%
  select(feature) %>% 
  as.matrix() %>%
  as.vector()

profiles.mat <- lapply(profiles, function(x) x[,feat.comm]) %>% do.call(rbind, .)

feats <- colnames(profiles.mat) %>% 
          data.frame(features = .) %>%
          dplyr::filter(!str_detect(features, "Metadata_")) %>%
          as.matrix() %>% as.vector()
metas <- setdiff(colnames(profiles.mat), feats)

Pf <- list(data = profiles.mat, feat_cols = feats, factor_cols = metas)
#feats.to.remove <- Pf$data[,Pf$feat_cols] %>% 
#                      cor %>%
#                      caret::findCorrelation(., 0.9)

feats.to.remove <- c()

feats <- setdiff(Pf$feat_cols, Pf$feat_cols[feats.to.remove])
Pf$feat_cols <- feats
Pf$data <- Pf$data[,c(Pf$feat_cols, Pf$factor_cols)]

if (just.strongs) {
u.cntrl <- Pf$data %>% dplyr::filter(Metadata_ASSAY_WELL_ROLE == "mock") %>% dplyr::group_by(Metadata_Plate_Map_Name, Metadata_pert_well) %>% do(data.frame(cr = median(as.dist(cor(t(.[,Pf$feat_cols]))), na.rm = T))) 
u.cntrl$cr %>% quantile(., na.rm = T) %>% print
}

if (remove.untreated) {
  Pf$data %<>% dplyr::filter(Metadata_ASSAY_WELL_ROLE == "treated")  
}

Pf.bio <- Pf
Pf.nonbio <- Pf

Pf.bio$data <- Pf.bio$data %>% dplyr::filter(str_detect(Metadata_Plate_Map_Name, "BIO"))
Pf.nonbio$data <- Pf.nonbio$data %>% dplyr::filter(!str_detect(Metadata_Plate_Map_Name, "BIO"))

if (just.strongs) {
u.bio <- rep.cor(Pf.bio, "Metadata_broad_sample", Pf.bio$feat_cols)
v.bio <- non.rep.cor(Pf.bio, "Metadata_broad_sample", Pf.bio$feat_cols)

u.strong <- u.bio %>% dplyr::filter(cr > v.bio)
hit.rate <- (u.strong %>% NROW)/(u.bio %>% NROW)
print(hit.rate)
}

if (just.strongs) {
Pf.bio$data %>% 
  dplyr::filter(Metadata_broad_sample %in% u.strong$Metadata_broad_sample) %>%
  saveRDS(., "Pf_bio_new.rds")
} else {
Pf.bio$data %>%
  saveRDS(., "Pf_bio_new_all.rds")
}

if (just.strongs) {
u.nbio <- rep.cor(Pf.nonbio, "Metadata_broad_sample", Pf.nonbio$feat_cols)
v.nbio <- non.rep.cor(Pf.nonbio, "Metadata_broad_sample", Pf.nonbio$feat_cols)

u.strong <- u.nbio %>% dplyr::filter(cr > v.nbio)
hit.rate <- (u.strong %>% NROW)/(u.nbio %>% NROW)
print(hit.rate)
}

if(just.strongs) {
Pf.nonbio$data %>%
  dplyr::filter(Metadata_broad_sample %in% u.strong$Metadata_broad_sample) %>%
  saveRDS(., "Pf_DOS_new.rds")
} else {
Pf.nonbio$data %>%
  saveRDS(., "Pf_DOS_new_all.rds")
}

```

```{r, eval=FALSE}

Pf.old <- readRDS("../input/CDP2/Pf.rds")
Pf.old$feat_cols <- setdiff(Pf.old$feat_cols, "Cells_CellCount")
Pf.old$data <- Pf.old$data[,c(Pf.old$feat_cols, Pf.old$factor_cols)]

brds <- Pf$data$Metadata_broad_sample %>% unique 
Pf.old$data <- Pf.old$data %>% 
  dplyr::filter(Image_Metadata_BroadID %in% brds)

feats.to.remove <- Pf.old$data[,Pf.old$feat_cols] %>% 
                      cor %>%
                      caret::findCorrelation(., 0.9)
feats <- setdiff(Pf.old$feat_cols, Pf.old$feat_cols[feats.to.remove])
Pf.old$feat_cols <- feats
Pf.old$data <- Pf.old$data[,c(Pf.old$feat_cols, Pf.old$factor_cols)]

u1 <- rep.cor(Pf.old, "Image_Metadata_BroadID", Pf.old$feat_cols)
v1 <- non.rep.cor(Pf.old, "Image_Metadata_BroadID", Pf.old$feat_cols)

hit.rate1 <- (u1 %>% dplyr::filter(cr > v1) %>% NROW)/(u1 %>% NROW) 
print(hit.rate1)

u2 <- u1 %>% dplyr::inner_join(., u, by = c("Image_Metadata_BroadID" = "Metadata_broad_sample"))

D <- data.frame(type = sprintf("new \n %d%%", round(hit.rate * 100)), rep.cor = u$cr)
D1 <- data.frame(type = sprintf("old \n %d%%", round(hit.rate1 * 100)), rep.cor = u1$cr)
D.tot <- rbind(D, D1)
D.tot$type <- as.factor(D.tot$type)

ggplot2::ggplot(D.tot, aes(x = type, fill = type, y = rep.cor)) +
  ggplot2::geom_violin() + 
  ggplot2::geom_hline(yintercept = v, color = "#F8766D", linetype = 2) +
  ggplot2::geom_hline(yintercept = v1, color = "#00BFC4", linetype = 2) + 
  ggplot2::xlab("") +
  ggplot2::ylab("replicate correlation") +
  ggplot2::scale_fill_discrete(guide=FALSE)

D <- data.frame(old.cor = u2$cr.x, new.cor = u2$cr.y)
ggplot2::ggplot(D, aes(x = old.cor, y = new.cor)) + 
  ggplot2::geom_point() +
  ggplot2::geom_hline(yintercept = v, linetype = 2, color = "red") + 
  ggplot2::geom_vline(xintercept = v1, linetype = 2, color = "red") +
  ggplot2::xlab("rep. corr. (old)") + 
  ggplot2::ylab("rep. corr. (new)")
  

```

```{r}

Pf$data$Metadata_Plate %>% unique %>% length %>% print
Pf$data$Metadata_broad_sample %>% unique %>% length %>% print
Pf$data$Metadata_Plate_Map_Name %>% unique %>% length %>% print
profiles.mat %>% group_by(Metadata_ASSAY_WELL_ROLE) %>% summarise(cnt = n()) %>% print
profiles.mat %>% group_by(Metadata_Plate) %>% summarise(cnt = n()) %>% print

Pf$feat_cols %>% length %>% print
feat.comm %>% length %>% print

```

