```{r Load Gene OE and Compound data, eval=TRUE, warning=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(plyr)
library(reshape2)
library(htmlTable)
source("rep.corr.func.R")
use.repurp.annots <- F
permute.moas <- F
seed.moa <- -8     ## ignore, if permute.moas is False
LUAD <- F

base.dir <- "2016-07-20_90b7bb86"
use.feat.selected.in.TA.ORF.in.common <- F
corr.type <- "pearson"

if (LUAD) {
  load("../input/LUAD/LUAD.RData")
  Pf.ta <- list(data = Px, factor_cols = "Metadata_x_mutation_status", feat_cols = setdiff(colnames(Px), "Metadata_x_mutation_status"))
  Pf.ta.all <- Pf
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "Treatment")
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta.all$factor_cols <- c(Pf.ta.all$factor_cols, "Treatment")

  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta.all$data$Treatment <- lapply(Pf.ta.all$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta$data <- Pf.ta$data %>% dplyr::group_by(Treatment) %>% slice(1) %>% dplyr::ungroup()
} else {
  load("../input/TA/Initial_analysis_workspace_old.RData")
  Pf.ta <- Pf_org.org.collapsed
  Pf.ta.all <- Pf_org.org
  strong.trt <- Pf.trt.strong.collapsed$data$Treatment
  data.annot <- Pf.strong %>% dplyr::filter(Treatment %in% strong.trt) %>% dplyr::select(one_of(c("Treatment", "Pathway", "Gene", "AlleleDesc"))) %>% 
    dplyr::mutate(Pathway = str_replace(Pathway, "Canonical ", "")) %>% 
    dplyr::mutate(AlleleDesc = str_sub(AlleleDesc, 1, 2)) %>%
    dplyr::filter(AlleleDesc == "WT") %>% dplyr::group_by(Gene) %>% dplyr::slice(1) %>%
    dplyr::ungroup() 
  desired.ta <- data.annot$Treatment
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(Treatment %in% c(as.character(desired.ta), "EMPTY_")) 
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
  
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist 
}

Pf.gene <- Pf.ta
Pf.gene.all <- Pf.ta.all

############

source("rep.corr.func.R")

x <- readRDS("../input/repurp/2016_04_01_a549_48hr_batch1_normalized.rds")
moa.list <- x[,c("Metadata_pert_iname", "Metadata_moa")]
m.list <- moa.list$Metadata_moa %>% unique %>% as.matrix() %>% as.vector() %>% as.vector()
m.list <- setdiff(m.list, NA)
set.seed(seed.moa)
pr <- permute::shuffle(length(m.list))
m.list <- data.frame(moa = m.list)
rownames(m.list) <- m.list$moa[pr]
m.list.p <- lapply(x$Metadata_moa, function(x) m.list[(x %>% as.character()), "moa"]) %>% unlist
if (permute.moas) {
  x$Metadata_moa <- m.list.p  
}

x <- cbind(x, data.frame(Metadata_Treatment = paste(x$Metadata_pert_id, x$Metadata_mg_per_ml, sep = "@")))
feats <- colnames(x)
feats <- feats[which(!str_detect(feats, "Metadata"))]
metadata <- colnames(x)
metadata <- metadata[which(str_detect(metadata, "Metadata"))]
thr <- non.rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
u <- rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
strong.trt <- u$Metadata_Treatment[which(u$cr > thr)]
sprintf("Hit ratio (compound-concentrations) : %f%%", round(length(strong.trt)/NROW(u) * 100))
strong.cmpd <- lapply(strong.trt, function(x) str_split(x, "@")[[1]][1]) %>% unlist %>% unique
all.cmpd <- lapply(u$Metadata_Treatment, function(x) str_split(x, "@")[[1]][1]) %>% unlist %>% unique
sprintf("Hit ratio (compounds) : %f%%", round(length(strong.cmpd)/length(all.cmpd) * 100))
x.all <- x
x <- x %>% dplyr::filter(Metadata_Treatment %in% strong.trt)
x.collapsed <- x %>% dplyr::group_by(Metadata_pert_iname, Metadata_pert_idose, Metadata_moa) %>% 
  dplyr::select(one_of(c(feats, "Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))) %>% dplyr::summarise_each(funs("mean")) %>% dplyr::ungroup() %>% dplyr::filter(!is.na(Metadata_pert_iname))

Pf.cmpd <- list(data = x.collapsed, feat_cols = feats, factor_cols = c("Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))
Pf.cmpd.all <- list(data = x.all, feat_cols = feats, factor_cols = c("Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))

```

```{r Align the features in Compound and Gene OE data, eval=TRUE}

f1 <- Pf.cmpd$feat_cols
f2 <- Pf.gene$feat_cols
f <- intersect(f1, f2)

Pf.cmpd$feat_cols <- f
Pf.gene$feat_cols <- f

Pf.cmpd$data <- Pf.cmpd$data[,c(Pf.cmpd$factor_cols, Pf.cmpd$feat_cols)]
Pf.gene$data <- Pf.gene$data[,c(Pf.gene$factor_cols, Pf.gene$feat_cols)]

#med <- apply(Pf.cmpd$data[,Pf.cmpd$feat_cols], 2, median)
#md <- apply(Pf.cmpd$data[,Pf.cmpd$feat_cols], 2, mad)
#Pf.cmpd$data[,Pf.cmpd$feat_cols] <- scale(Pf.cmpd$data[,Pf.cmpd$feat_cols], med, md)

Pf.cmpd.all$feat_cols <- f
Pf.gene.all$feat_cols <- f

Pf.cmpd.all$data <- Pf.cmpd.all$data[,c(Pf.cmpd.all$factor_cols, Pf.cmpd.all$feat_cols)]
Pf.gene.all$data <- Pf.gene.all$data[,c(Pf.gene.all$factor_cols, Pf.gene.all$feat_cols)]

if (use.feat.selected.in.TA.ORF.in.common) {
  feats <- Pf_org$feat_cols
  feats <- intersect(feats, Pf.cmpd$feat_cols)
  Pf.cmpd$feat_cols <- feats
  Pf.cmpd$data <- Pf.cmpd$data[,c(feats, Pf.cmpd$factor_cols)]
  Pf.gene$feat_cols <- feats
  Pf.gene$data <- Pf.gene$data[,c(feats, Pf.gene$factor_cols)]

  Pf.cmpd.all$feat_cols <- feats
  Pf.cmpd.all$data <- Pf.cmpd.all$data[,c(feats, Pf.cmpd.all$factor_cols)]
  Pf.gene.all$feat_cols <- feats
  Pf.gene.all$data <- Pf.gene.all$data[,c(feats, Pf.gene.all$factor_cols)]
}

#med <- apply(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], 2, median)
#md <- apply(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], 2, mad)
#Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols] <- scale(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], med, md)

print(length(Pf.cmpd$feat_cols))
print(NROW(Pf.cmpd$data))

print(length(Pf.gene$feat_cols))
print(NROW(Pf.gene$data))

print(length(Pf.cmpd.all$feat_cols))
print(NROW(Pf.cmpd.all$data))

print(length(Pf.gene.all$feat_cols))
print(NROW(Pf.gene.all$data))

```

```{r Testing neg. control sample statistics in both datasets, eval=TRUE}

cr.cmpd.mat <- Pf.cmpd.all$data %>% dplyr::filter(is.na(Metadata_pert_iname)) %>% dplyr::select(one_of(Pf.cmpd.all$feat_cols)) %>% cor
cr.cmpd <- cr.cmpd.mat %>% melt %>% dplyr::filter(as.character(Var1) < as.character(Var2))
cr.gene.mat <- Pf.gene.all$data %>% dplyr::filter(Treatment == "EMPTY_") %>% dplyr::select(one_of(Pf.gene.all$feat_cols)) %>% cor
cr.gene <- cr.gene.mat %>% melt %>% dplyr::filter(as.character(Var1) < as.character(Var2))

(sum(cr.gene[,3] * cr.cmpd[,3], na.rm = T)/(sum(cr.gene[,3]^2, na.rm = T)^0.5 * sum(cr.cmpd[,3]^2, na.rm = T)^0.5)) %>% print()
cor(cr.gene[,3], cr.cmpd[,3]) %>% print

cr.comp <- cr.cmpd
cr.comp[,3] <- cr.gene[,3] * cr.cmpd[,3]

cr.comp <- cbind(cr.comp, data.frame(cmpd.corr = cr.cmpd[,3]), data.frame(gene.corr = cr.gene[,3]))
cr.comp %>% dplyr::arrange(value) %>% head(., 200) %>% dplyr::mutate(value = round(value, 2), cmpd.corr = round(cmpd.corr, 2), gene.corr = round(gene.corr, 2)) %>% htmlTable(.)

```

```{r Find the correlation matrix, eval=T}

cr.melt.all <- c()
cmpd.all <- Pf.cmpd$data$Metadata_pert_iname %>% unique()
cr <- outer(rep(0, length(cmpd.all)), rep(0, NROW(Pf.gene$data)), "*")
rownames(cr) <- cmpd.all
colnames(cr) <- Pf.gene$data$Treatment

for (i in 1:6) {
  d <- Pf.cmpd$data %>% dplyr::group_by(Metadata_pert_iname) %>% dplyr::slice(i) %>% dplyr::ungroup()
  
  x <- d[,Pf.cmpd$feat_cols]
  y <- Pf.gene$data[,Pf.gene$feat_cols]
  
  cri <- cor(x %>% t, y %>% t, method = corr.type) 
  rownames(cri) <- d$Metadata_pert_iname
  colnames(cri) <- Pf.gene$data$Treatment
  
  crj <- cr * NA
  crj[rownames(cri), colnames(cri)] <- cri 
  
  if (is.null(cr.melt.all)) {
    cr.melt.all <- crj %>% melt
  } else {
    cr.melt <- crj %>% melt
    cr.melt.all <- cbind(cr.melt.all, cr.melt[,3])
  }
}

#v1 <- apply(cr.melt.all, 1, function(x) (quantile(x[3:NCOL(cr.melt.all)] %>% as.numeric(), 0.75, na.rm = T) %>% as.matrix() %>% as.vector))
#v2 <- apply(cr.melt.all, 1, function(x) (quantile(x[3:NCOL(cr.melt.all)] %>% as.numeric(), 0.25, na.rm = T) %>% as.matrix() %>% as.vector))
v1 <- apply(cr.melt.all, 1, function(x) (max(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))
v2 <- apply(cr.melt.all, 1, function(x) (min(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))

v3 <- apply(cbind(abs(v1), abs(v2)), 1, function(x) max(x, na.rm = T) * c(1, -1)[which.max(x)])
cr.melt <- melt(cr)
cr.melt[,3] <- v3

```

```{r, results='asis'}

MOA.consistency <- readRDS("../results/master/2017-03-01_66f41a62/MOA_consistency.rds")
moas.to.consider <- MOA.consistency %>% 
  dplyr::arrange(-sig.strn + thresh) %>%
  dplyr::filter(consistent) %>% 
  dplyr::select(MOA) %>% as.matrix() %>% as.vector() %>% as.character()

moas <- read.csv("../input/moas.txt", sep = "\t")

get.interacting.proteins <- function(protein.name) {
  tbl <- read.table(sprintf("http://webservice.thebiogrid.org/interactions/?searchNames=true&geneList=%s&taxId=9606&includeHeader=true&accesskey=ca950b072394ce1897811022f7757222", protein.name), sep="\t", header = FALSE, fill = T)
  tbl <- tbl[, c(8, 9, 12, 13, 14)] 
  colnames(tbl) <- c("Protein.1", "Protein.2", "Method", "Type", "Evidence")
  return(tbl)
}

get.all.interacting.proteins <- function(protein.name) {
  res <- c()
  for (p in protein.name) {
    ppi <- tryCatch(get.interacting.proteins(p), error = function(e) {})
    res <- rbind(res, ppi)
  }
  return(res)
}

V <- matrix(0, 2, 2)
rownames(V) <- c("filtered top/bottom pairs", "remainder of pairs")
colnames(V) <- c("validated (have interaction with the MOA target)", "non-validated")
dt.summ <- data.frame(MOA = c(), target = c(), genes = c())

for (moa in moas.to.consider) {
  u.res <- cr.melt %>% 
    dplyr::filter(Var1 %in% (Pf.cmpd$data$Metadata_pert_iname[which(str_detect(Pf.cmpd$data$Metadata_moa, moa))] %>% unique())) %>%
    dplyr::mutate(Gene.Overexpression=Var2) %>% dplyr::select(one_of(c("Gene.Overexpression", "Var1", "value"))) %>%
    dplyr::group_by(Gene.Overexpression) %>% dplyr::summarise(score = mean(value)) %>%
    dplyr::arrange(score) %>% dplyr::mutate(score = round(score, 2)) %>% dplyr::filter(abs(score) > 0.3) 
  up.reg <- u.res %>% head(., 5) %>% dplyr::filter(score < 0) %>% dplyr::select(Gene.Overexpression) %>% as.matrix() %>% as.vector()
  down.reg <- u.res %>% tail(., 5) %>% dplyr::filter(score > 0) %>% dplyr::select(Gene.Overexpression) %>% as.matrix() %>% as.vector()
  reg <- c(up.reg, down.reg) %>% unique
  rest <- setdiff(Pf.gene$data$Treatment, reg)
  v <- lapply(moas$Target[moas$MOA == moa], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) 
  if (length(v) == 0) {
    next
  }
  main.targ <- data.frame(gene = v) %>% dplyr::group_by(gene) %>% tally() %>% dplyr::filter(gene != "") %>% dplyr::arrange(-n) %>% head(., 1) %>% dplyr::select(gene) %>% as.matrix() %>% as.vector()
  dt <- rbind(u.res %>% head(., 5), u.res %>% tail(., 5)) %>% unique
  if (NROW(dt) >= 1) {
    #dt %>% htmlTable::htmlTable() %>% print  
  }
  ppi <- tryCatch(get.all.interacting.proteins(main.targ), error = function(e) {})
  if(is.null(ppi)) {
    next
  }
  i <- which(reg %in% (c(ppi$Protein.1 %>% as.character(), ppi$Protein.2 %>% as.character()) %>% unique))
  if (length(i) > 0) {
    dt.summ <- rbind(dt.summ, data.frame(MOA = moa, target = main.targ, genes = paste(reg[i], " ", collapse = " ")))
    cat(sprintf("MOA : %s", moa))
    cat("<br>")
    cat(sprintf("Selected target of the MOA : %s", main.targ))
    cat("<br>")
    u.res.s <- u.res %>% dplyr::filter(Gene.Overexpression %in% reg)
    if (NROW(u.res.s) > 0) {
      u.res.s %>% htmlTable::htmlTable() %>% cat()
    }
    cat("<br>")
    cat(sprintf("Following genes are relevant : %s", paste(reg[i], " ", collapse = " ")))
    cat("<br>")
  }
  v11 <- length(i)
  v12 <- length(reg) - v11
  v21 <- which(rest %in% (c(ppi$Protein.1 %>% as.character(), ppi$Protein.2 %>% as.character()) %>% unique)) %>% length
  v22 <- length(rest) - v21
  Vi <- rbind(c(v11, v12), c(v21, v22))
  rownames(Vi) <- c("filtered top/bottom pairs", "remainder of pairs")
  colnames(Vi) <- c("validated", "non-validated")
  V <- V + Vi
  if (length(i) > 0) {
    Vi %>% htmlTable::htmlTable() %>% cat
    cat("<br>")
    ppi.s <- ppi %>% dplyr::filter(Protein.1 %in% reg | Protein.2 %in% reg) 
    if (NROW(ppi.s) > 0) {
      ppi.s %>% head(., 20) %>% htmlTable::htmlTable() %>% cat
    } 
    cat("<hr>")
  }
}

```

```{r}

dt.summ %>% htmlTable()
print(V)
fisher.test(V, alternative = "greater") %>% print

```

