```{r Load Gene OE and Compound data, eval=TRUE, warning=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(plyr)
library(reshape2)
library(htmlTable)
library(foreach)
library(doMC)
registerDoMC(cores = 3)

source("rep.corr.func.R")
use.repurp.annots <- F
permute.moas <- F
seed.moa <- -8     ## ignore, if permute.moas is False

base.dir <- "2016-07-20_90b7bb86"
use.feat.selected.in.TA.ORF.in.common <- F
corr.type <- "spearman"

load("../input/TA/Initial_analysis_workspace.RData")
Pf.ta <- Pf_org.org.collapsed
Pf.ta.all <- Pf_org.org
strong.trt <- Pf.trt.strong.collapsed$data$Treatment
data.annot <- Pf.strong %>% dplyr::filter(Treatment %in% strong.trt) %>% dplyr::select(one_of(c("Treatment", "Pathway", "Gene", "AlleleDesc"))) %>% 
  dplyr::mutate(Pathway = str_replace(Pathway, "Canonical ", "")) %>% 
  dplyr::mutate(AlleleDesc = str_sub(AlleleDesc, 1, 2)) %>%
  dplyr::filter(AlleleDesc == "WT") %>% dplyr::group_by(Gene) %>% dplyr::slice(1) %>%
  dplyr::ungroup() 
desired.ta <- data.annot$Treatment
Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(Treatment %in% c(as.character(desired.ta), "EMPTY_")) 
Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 

Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
Pf.gene <- Pf.ta
Pf.gene.all <- Pf.ta.all

############

source("rep.corr.func.R")

x <- readRDS("../input/repurp/2016_04_01_a549_48hr_batch1_normalized.rds")
moa.list <- x[,c("Metadata_pert_iname", "Metadata_moa")]
m.list <- moa.list$Metadata_moa %>% unique %>% as.matrix() %>% as.vector() %>% as.vector()
m.list <- setdiff(m.list, NA)
set.seed(seed.moa)
pr <- permute::shuffle(length(m.list))
m.list <- data.frame(moa = m.list)
rownames(m.list) <- m.list$moa[pr]
m.list.p <- lapply(x$Metadata_moa, function(x) m.list[(x %>% as.character()), "moa"]) %>% unlist
if (permute.moas) {
  x$Metadata_moa <- m.list.p  
}

x <- cbind(x, data.frame(Metadata_Treatment = paste(x$Metadata_pert_id, x$Metadata_mg_per_ml, sep = "@")))
feats <- colnames(x)
feats <- feats[which(!str_detect(feats, "Metadata"))]
metadata <- colnames(x)
metadata <- metadata[which(str_detect(metadata, "Metadata"))]
thr <- non.rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
u <- rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
strong.trt <- u$Metadata_Treatment[which(u$cr > thr)]
sprintf("Hit ratio (compound-concentrations) : %f%%", round(length(strong.trt)/NROW(u) * 100))
strong.cmpd <- lapply(strong.trt, function(x) str_split(x, "@")[[1]][1]) %>% unlist %>% unique
all.cmpd <- lapply(u$Metadata_Treatment, function(x) str_split(x, "@")[[1]][1]) %>% unlist %>% unique
sprintf("Hit ratio (compounds) : %f%%", round(length(strong.cmpd)/length(all.cmpd) * 100))
x.all <- x
x <- x %>% dplyr::filter(Metadata_Treatment %in% strong.trt)
x.collapsed <- x %>% dplyr::group_by(Metadata_pert_iname, Metadata_pert_idose, Metadata_moa) %>% 
  dplyr::select(one_of(c(feats, "Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))) %>% dplyr::summarise_each(funs("mean")) %>% dplyr::ungroup() %>% dplyr::filter(!is.na(Metadata_pert_iname))

Pf.cmpd <- list(data = x.collapsed, feat_cols = feats, factor_cols = c("Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))
Pf.cmpd.all <- list(data = x.all, feat_cols = feats, factor_cols = c("Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa"))

```

```{r Align the features in Compound and Gene OE data, eval=TRUE}

f1 <- Pf.cmpd$feat_cols
f2 <- Pf.gene$feat_cols
f <- intersect(f1, f2)

Pf.cmpd$feat_cols <- f
Pf.gene$feat_cols <- f

Pf.cmpd$data <- Pf.cmpd$data[,c(Pf.cmpd$factor_cols, Pf.cmpd$feat_cols)]
Pf.gene$data <- Pf.gene$data[,c(Pf.gene$factor_cols, Pf.gene$feat_cols)]

#med <- apply(Pf.cmpd$data[,Pf.cmpd$feat_cols], 2, median)
#md <- apply(Pf.cmpd$data[,Pf.cmpd$feat_cols], 2, mad)
#Pf.cmpd$data[,Pf.cmpd$feat_cols] <- scale(Pf.cmpd$data[,Pf.cmpd$feat_cols], med, md)

Pf.cmpd.all$feat_cols <- f
Pf.gene.all$feat_cols <- f

Pf.cmpd.all$data <- Pf.cmpd.all$data[,c(Pf.cmpd.all$factor_cols, Pf.cmpd.all$feat_cols)]
Pf.gene.all$data <- Pf.gene.all$data[,c(Pf.gene.all$factor_cols, Pf.gene.all$feat_cols)]

if (use.feat.selected.in.TA.ORF.in.common) {
  feats <- Pf_org$feat_cols
  feats <- intersect(feats, Pf.cmpd$feat_cols)
  Pf.cmpd$feat_cols <- feats
  Pf.cmpd$data <- Pf.cmpd$data[,c(feats, Pf.cmpd$factor_cols)]
  Pf.gene$feat_cols <- feats
  Pf.gene$data <- Pf.gene$data[,c(feats, Pf.gene$factor_cols)]

  Pf.cmpd.all$feat_cols <- feats
  Pf.cmpd.all$data <- Pf.cmpd.all$data[,c(feats, Pf.cmpd.all$factor_cols)]
  Pf.gene.all$feat_cols <- feats
  Pf.gene.all$data <- Pf.gene.all$data[,c(feats, Pf.gene.all$factor_cols)]
}

#med <- apply(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], 2, median)
#md <- apply(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], 2, mad)
#Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols] <- scale(Pf.cmpd.all$data[,Pf.cmpd.all$feat_cols], med, md)

print(length(Pf.cmpd$feat_cols))
print(NROW(Pf.cmpd$data))

print(length(Pf.gene$feat_cols))
print(NROW(Pf.gene$data))

print(length(Pf.cmpd.all$feat_cols))
print(NROW(Pf.cmpd.all$data))

print(length(Pf.gene.all$feat_cols))
print(NROW(Pf.gene.all$data))

```

```{r Testing neg. control sample statistics in both datasets, eval=TRUE}

cr.cmpd.mat <- Pf.cmpd.all$data %>% dplyr::filter(is.na(Metadata_pert_iname)) %>% dplyr::select(one_of(Pf.cmpd.all$feat_cols)) %>% cor
cr.cmpd <- cr.cmpd.mat %>% melt %>% dplyr::filter(as.character(Var1) < as.character(Var2))
cr.gene.mat <- Pf.gene.all$data %>% dplyr::filter(Treatment == "EMPTY_") %>% dplyr::select(one_of(Pf.gene.all$feat_cols)) %>% cor
cr.gene <- cr.gene.mat %>% melt %>% dplyr::filter(as.character(Var1) < as.character(Var2))

(sum(cr.gene[,3] * cr.cmpd[,3], na.rm = T)/(sum(cr.gene[,3]^2, na.rm = T)^0.5 * sum(cr.cmpd[,3]^2, na.rm = T)^0.5)) %>% print()
cor(cr.gene[,3], cr.cmpd[,3]) %>% print

cr.comp <- cr.cmpd
cr.comp[,3] <- cr.gene[,3] * cr.cmpd[,3]

cr.comp <- cbind(cr.comp, data.frame(cmpd.corr = cr.cmpd[,3]), data.frame(gene.corr = cr.gene[,3]))
cr.comp %>% dplyr::arrange(value) %>% head(., 200) %>% dplyr::mutate(value = round(value, 2), cmpd.corr = round(cmpd.corr, 2), gene.corr = round(gene.corr, 2)) %>% htmlTable(.)

```

```{r Find the correlation matrix, eval=T}

cr.melt.all <- c()
cmpd.all <- Pf.cmpd$data$Metadata_pert_iname %>% unique()
cr <- outer(rep(0, length(cmpd.all)), rep(0, NROW(Pf.gene$data)), "*")
rownames(cr) <- cmpd.all
colnames(cr) <- Pf.gene$data$Treatment

for (i in 1:6) {
  d <- Pf.cmpd$data %>% dplyr::group_by(Metadata_pert_iname) %>% dplyr::slice(i) %>% dplyr::ungroup()
  
  x <- d[,Pf.cmpd$feat_cols]
  y <- Pf.gene$data[,Pf.gene$feat_cols]
  
  cri <- cor(x %>% t, y %>% t, method = corr.type) 
  rownames(cri) <- d$Metadata_pert_iname
  colnames(cri) <- Pf.gene$data$Treatment
  
  crj <- cr * NA
  crj[rownames(cri), colnames(cri)] <- cri 
  
  if (is.null(cr.melt.all)) {
    cr.melt.all <- crj %>% melt
  } else {
    cr.melt <- crj %>% melt
    cr.melt.all <- cbind(cr.melt.all, cr.melt[,3])
  }
}

#v1 <- apply(cr.melt.all, 1, function(x) (quantile(x[3:NCOL(cr.melt.all)] %>% as.numeric(), 0.75, na.rm = T) %>% as.matrix() %>% as.vector))
#v2 <- apply(cr.melt.all, 1, function(x) (quantile(x[3:NCOL(cr.melt.all)] %>% as.numeric(), 0.25, na.rm = T) %>% as.matrix() %>% as.vector))
v1 <- apply(cr.melt.all, 1, function(x) (max(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))
v2 <- apply(cr.melt.all, 1, function(x) (min(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))

v3 <- apply(cbind(abs(v1), abs(v2)), 1, function(x) max(x, na.rm = T) * c(1, -1)[which.max(x)])
cr.melt <- melt(cr)
cr.melt[,3] <- v3

```

```{r}

cls.gene <- lapply(cls, function(x) unique(unlist(lapply(x, function(y) str_split(y, "_")[[1]][1]))))

moas <- read.csv("../input/moas.txt", sep = "\t")

get.interacting.proteins <- function(protein.name) {
  dr <- "../results/manual/ppis"
  if (!dir.exists(dr)) {
    system(sprintf("mkdir -p %s", dr))
  }
  f.name <- sprintf("%s/%s.rds", dr, protein.name)
  if (file.exists(f.name)) {
    return(readRDS(f.name))
  }
  
  tbl <- read.table(sprintf("http://webservice.thebiogrid.org/interactions/?searchNames=true&geneList=%s&taxId=9606&includeHeader=true&accesskey=ca950b072394ce1897811022f7757222", protein.name), sep="\t", header = FALSE, fill = T)
  tbl <- tbl[, c(8, 9, 12, 13, 14)] 
  colnames(tbl) <- c("Protein.1", "Protein.2", "Method", "Type", "Evidence")
  saveRDS(tbl, f.name)
  return(tbl)
}

get.all.interacting.proteins <- function(protein.name) {
  res <- c()
  for (p in protein.name) {
    ppi <- tryCatch(get.interacting.proteins(p), error = function(e) {})
    res <- rbind(res, ppi)
  }
  return(res)
}

 V <- matrix(0, 2, 2)

sample.tot <- function(random.shuffle = F, verbose = F, cor.thr = 0.5, how.many = 5) {
  gn.list <- c()
  all.moas <- moas %>% dplyr::filter(str_to_lower(Name) %in% str_to_lower(Pf.cmpd$data$Metadata_pert_iname %>% unique)) %>% dplyr::select(MOA) %>% as.matrix() %>% as.vector() %>% as.character %>% unique
  gn.map <- Pf.gene$data$Treatment %>% as.matrix() %>% as.vector()
  if (random.shuffle) {
    while(T) {
      names(gn.map) <- gn.map[permute::shuffle(length(gn.map))]
      flag <- T
      for (i in 1:length(cls.gene)) {
        if (any(gn.map[cls.gene[[i]]] %in% cls.gene[[i]])) {
          flag <- F
          break
        }
      }
      if (flag) {
        break
      }
    }
  } else {
    names(gn.map) <- gn.map
  }
  
  all.targ <- lapply(moas$Target[moas$Name %in% (Pf.cmpd$data$Metadata_pert_iname %>% unique)], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) %>% unique
  path <- sprintf("../results/manual/ppis")
  if (!dir.exists(path)) {
    system(sprintf("mkdir -p %s", path))
  }
  if (file.exists(sprintf("%s/all.rds", path))) {
    ppi.all <- readRDS(sprintf("%s/all.rds", path))
  } else {
    ppi.all <- tryCatch(get.all.interacting.proteins(all.targ), error = function(e) {})
    saveRDS(ppi.all, sprintf("%s/all.rds", path))
  }
  
  for (gene in Pf.gene$data$Treatment) {
    gn <- gn.map[gene] %>% as.matrix() %>% as.vector()
    u.res <- cr.melt %>% 
      dplyr::filter(Var2 == gn) %>%
      dplyr::arrange(-value) %>%
      dplyr::mutate(value = round(value, 2)) %>% dplyr::filter(abs(value) > cor.thr) 
    
    up.reg <- u.res %>% head(., how.many) %>% dplyr::filter(value > 0) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()
    down.reg <- u.res %>% tail(., how.many) %>% dplyr::filter(value < 0) %>% dplyr::select(Var1) %>% as.matrix() %>% as.vector()
    reg <- c(up.reg, down.reg) %>% unique
    u.res.lim <- u.res %>% dplyr::filter(Var1 %in% reg) %>% dplyr::mutate(Name = Var1) %>% dplyr::mutate(Corr. = value) %>% dplyr::select(one_of(c("Name", "Corr.")))
    rest <- setdiff(Pf.cmpd$data$Metadata_pert_iname %>% unique, reg)
    v <- lapply(moas$Target[moas$Name %in% reg], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) 
    if (length(v) == 0) {
      next
    }
    u <- lapply(moas$Target[moas$Name %in% rest], function(x) str_split(x, ", ")[[1]]) %>% do.call(c, .) 
    
    main.targ <- data.frame(gene = v) %>% dplyr::group_by(gene) %>% tally() %>% dplyr::filter(gene != "") %>% dplyr::arrange(-n) %>% dplyr::select(gene) %>% as.matrix() %>% as.vector()
    rest.targ <- data.frame(gene = u) %>% dplyr::group_by(gene) %>% tally() %>% dplyr::filter(gene != "") %>% dplyr::arrange(-n) %>% dplyr::select(gene) %>% as.matrix() %>% as.vector()
    
    ppi <- ppi.all %>% dplyr::filter(Protein.1 %in% main.targ | Protein.2 %in% main.targ)
    ppi2 <- ppi.all %>% dplyr::filter(Protein.1 %in% rest.targ | Protein.2 %in% rest.targ)
    
    id <- ppi %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% NROW
    id0 <- ppi2 %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% NROW
    Vi <- rbind(c(id, NROW(ppi %>% unique) - id), c(id0, NROW(ppi2 %>% unique) - id0))
    V <- V + Vi
    
    fsh <- fisher.test(Vi, alternative = "greater")
    if (fsh$p.value < 0.05/NROW(Pf.gene$data$Treatment)) {
      gn.list <- c(gn.list, gene)
      if (verbose) {
        cat(gene)
        cat("<br>")
        colnames(Vi) <- c("gene in relevant ppi", "otherwise")
        rownames(Vi) <- c("compound matches", "rest of compounds")
        Vi %>% htmlTable::htmlTable() %>% cat
        cat("<br>")
        fsh %>% print
        cat("<br>")
        (moas %>% dplyr::filter(Name %in% reg) %>% dplyr::select(one_of(c("Name", "MOA", "Target")))) %>% plyr::join(., u.res.lim, by = "Name") %>% htmlTable::htmlTable() %>% cat
        (ppi %>% dplyr::filter(Protein.1 == gene | Protein.2 == gene) %>% unique %>% head(., 20)) %>% htmlTable::htmlTable() %>% cat
        cat("<br> <hr>")
      }
    }
  }
  
  return(list(genes = gn.list, V = V))
}

```

```{r, eval=F}

odds <- c()
p.val <- c()
res <- sample.tot(random.shuffle = F, verbose = T, cor.thr = 0.4, how.many = 10)
f <- fisher.test(res$V, alternative = "greater")

n.genes <- foreach(i = 1:50) %dopar% {
  res <- sample.tot(random.shuffle = T, verbose = F, cor.thr = 0.4, how.many = 10)
  (res$genes %>% length)
}


print(1 - ecdf(n.genes %>% unlist)(res$genes %>% length))

```

```{r, results='asis'}

res <- sample.tot(random.shuffle = F, verbose = T, cor.thr = 0.4, how.many = 10)
f <- fisher.test(res$V, alternative = "greater")

```

```{r}

print(f)
print(res)

```

