```{r Load Gene OE and Compound data, eval=TRUE, warning=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(plyr)
library(reshape2)
library(magrittr)
library(htmlTable)
library(ggplot2)
library(foreach)
library(doParallel)

doParallel::registerDoParallel(cores = 3)
  
source("rep.corr.func.R")
permute.moas <- F
seed.moa <- -8     ## ignore, if permute.moas is False
hit.sel.quant <- 0.95
hit.sel.quant.repurp <- 0.95
just.bioactives <- T
dmos.null <- F
manual.hit.sel.thr <- T
hit.sel.thr.repurp <- 0.70
hit.sel.thr.cdrp <- 0.48
do.pca <- T
pca.thr <- 0.99
perc.top <- 0.02
random.feat.sel <- F
error.analysis <- F
dose.to.select <- 5
seed.x <- 30
do.cca <- F

base.dir <- "2016-07-20_90b7bb86"
corr.type <- "pearson"
just.common.cmpds <- F
set.moa.to.cmpd.name <- F

x <- readRDS("../input/repurp/2016_04_01_a549_48hr_batch1_normalized.rds")

x <- cbind(x, data.frame(Metadata_Treatment = paste(x$Metadata_pert_id, x$Metadata_mg_per_ml, sep = "@")))
feats <- colnames(x)
feats <- feats[which(!str_detect(feats, "Metadata"))]
metadata <- colnames(x)
metadata <- metadata[which(str_detect(metadata, "Metadata"))]

Pf.repurp <- list(data = x, 
                        feat_cols = feats, 
                        factor_cols = metadata)

Pf.repurp$data %<>% dplyr::mutate(Metadata_plate_well = paste(Metadata_plate_map_name, Metadata_Well, sep = "_"))

Pf.repurp$factor_cols <- c(Pf.repurp$factor_cols, "Metadata_plate_well")
trts <- Pf.repurp$data %>% 
  dplyr::mutate(tmp_dose = abs(Metadata_mmoles_per_liter - dose.to.select)) %>%
  dplyr::arrange(tmp_dose) %>%
  dplyr::group_by(Metadata_pert_iname) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup(.) %>%
  dplyr::select(Metadata_Treatment) %>%
  as.matrix() %>%
  as.vector()

Pf.repurp$data %<>%
  dplyr::filter(Metadata_Treatment %in% trts)
  
############

if (just.bioactives) {
  Pf <- readRDS("../results/master/2017-06-26_5b0bbf7c/Pf_bio_new.rds")
} else {
  Pf.1 <- readRDS("../results/master/2017-06-26_5b0bbf7c/Pf_bio_new.rds")
  Pf.2 <- readRDS("../results/master/2017-06-26_5b0bbf7c/Pf_DOS_new.rds")
  Pf <- rbind(Pf.1, Pf.2)
}

Pf %<>% filter(Metadata_broad_sample != "DMSO" | 
                                    (!str_detect(Metadata_Well, "01") &
                                    !str_detect(Metadata_Well, "24") &
                                    !str_detect(Metadata_Well, "a") &
                                    !str_detect(Metadata_Well, "p")))

Pf %<>% dplyr::mutate(Metadata_plate_well = paste(Metadata_Plate_Map_Name, Metadata_Well, sep = "_"))

feat <- Pf %>% 
          dplyr::select(-dplyr::contains("Metadata_")) %>% 
          colnames()

metadata.ext <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
brd.full <- unique(Pf$Metadata_broad_sample)
brds <- lapply(brd.full, function(x) paste(str_split(x,
                                                                             "-")[[1]][1:2], 
                                                   sep = "-", collapse = "-")) %>% unlist()
brd.mapping <- data.frame(BROAD_CPD_ID = brds, 
                          Image_Metadata_BROAD_ID = brd.full)
metadata.ext %<>% 
  dplyr::select(BROAD_CPD_ID, CPD_NAME) %>% 
  dplyr::filter(BROAD_CPD_ID %in% brds) %>%
  dplyr::mutate(CPD_NAME = ifelse(str_detect(CPD_NAME, "BRD-"), "", CPD_NAME)) %>%
  dplyr::inner_join(., brd.mapping, by = "BROAD_CPD_ID") %>%
  dplyr::select(-BROAD_CPD_ID)

metadata <- data.frame(Metadata_broad_sample = unique(Pf$Metadata_broad_sample))
metadata %<>% 
  dplyr::left_join(., metadata.ext, by = c("Metadata_broad_sample" = "Image_Metadata_BROAD_ID"))

Pf %<>% dplyr::left_join(., metadata, by = "Metadata_broad_sample")

Pf %<>% dplyr::mutate(CPD_NAME = str_to_lower(CPD_NAME))
Pf %<>% dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME, "-", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, " ", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\(", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\)", "")) 
  
MOA <- read.csv("../input/moas.txt", sep = "\t")
MOA %<>% dplyr::mutate(Name = str_to_lower(Name)) %>%
  dplyr::mutate(Name_san = str_replace_all(Name, "-", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, " ", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\(", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\)", "")) 

Pf %<>% dplyr::left_join(., MOA, by = c("CPD_NAME_san" = "Name_san"))
meta.col <- setdiff(colnames(Pf), feat)
Pf.cdrp <- list(data = Pf, feat_cols = feat, factor_cols = meta.col)

```

```{r Align the features in Compound and Gene OE data, eval=TRUE}

f1 <- Pf.repurp$feat_cols
f2 <- colnames(Pf.cdrp$data)

f <- intersect(f1, f2)

if (random.feat.sel) {
  f <- sample(f, round(length(f) * 0.8))
}

Pf.repurp$feat_cols <- f
Pf.cdrp$feat_cols <- f

Pf.repurp$data <- Pf.repurp$data[,c(Pf.repurp$factor_cols, Pf.repurp$feat_cols)]
Pf.cdrp$data <- Pf.cdrp$data[,c(Pf.cdrp$factor_cols, Pf.cdrp$feat_cols)]

pr <- prcomp(rbind(Pf.repurp$data[,f], Pf.cdrp$data[,f]), center = F, scale. = F, retx = T)

v <- pr$sdev
v <- v^2
r <- lapply(1:length(v), function(i) (sum(v[1:i])/sum(v))) %>% unlist
k <- which.min(abs(r - pca.thr))

if (!do.pca) {
  k <- length(v)  
}

d1 <- cbind(pr$x[1:NROW(Pf.repurp$data),1:k] %>% as.data.frame(), Pf.repurp$data[,Pf.repurp$factor_cols] %>% as.data.frame())
d2 <- cbind(pr$x[(NROW(Pf.repurp$data)+1):NROW(pr$x),1:k] %>% as.data.frame(), Pf.cdrp$data[,Pf.cdrp$factor_cols] %>% as.data.frame())

Pf.repurp$data <- d1
Pf.cdrp$data <- d2

Pf.repurp$feat_cols <- setdiff(colnames(d1), Pf.repurp$factor_cols)
Pf.cdrp$feat_cols <- setdiff(colnames(d2), Pf.cdrp$factor_cols)

print(length(Pf.repurp$feat_cols))
print(NROW(Pf.repurp$data))
print(length(Pf.cdrp$feat_cols))
print(NROW(Pf.cdrp$data))

```

```{r hit selection}

u <- rep.cor(Pf.repurp,
        grp.var = "Metadata_plate_well", 
        feat.var = Pf.repurp$feat_cols, 
        aux.var = "Metadata_broad_sample")
u.repurp <- u

if (!dmos.null) {
  thr <- non.rep.cor(Pf.repurp,
        grp.var = "Metadata_broad_sample", 
        feat.var = Pf.repurp$feat_cols, 
        quant = hit.sel.quant.repurp)
  
} else {
  thr <- u %>% dplyr::filter(Metadata_broad_sample == "DMSO") %>% select(cr) %>% as.matrix() %>% as.vector() %>% quantile(., hit.sel.quant.repurp, na.rm = T)
}

if (manual.hit.sel.thr) {
  thr <- hit.sel.thr.repurp
}

thr.repurp <- thr
print(thr)

strongs <- setdiff(u$Metadata_broad_sample[which(u$cr > thr)], "DMSO")
Pf.repurp$data %<>% dplyr::filter(Metadata_broad_sample %in% strongs)

Pf.repurp$data %<>% dplyr::select(one_of(c(Pf.repurp$feat_cols, "Metadata_broad_sample", "Metadata_pert_iname", "Metadata_moa"))) %>%
  dplyr::group_by(Metadata_broad_sample, Metadata_pert_iname, Metadata_moa) %>%
  dplyr::summarise_each(funs("mean"))

############

u <- rep.cor(Pf.cdrp,
                   grp.var = "Metadata_plate_well",
                   feat.var = Pf.cdrp$feat_cols,
                   aux.var = "Metadata_broad_sample")
u.cdrp <- u

if (!dmos.null) {
  thr <- non.rep.cor(Pf.cdrp,
                   "Metadata_broad_sample", 
                   Pf.cdrp$feat_cols, 
                   quant = hit.sel.quant)

} else {
  thr <- u %>% dplyr::filter(Metadata_broad_sample == "DMSO") %>% select(cr) %>% as.matrix() %>% as.vector() %>% quantile(., hit.sel.quant, na.rm = T)
  
}

if (manual.hit.sel.thr) {
  thr <- hit.sel.thr.cdrp
}

thr.cdrp <- thr

print(thr)

strong.trt <- u$Metadata_broad_sample[which(u$cr > thr)]

sprintf("Hit ratio (compound-concentrations) : %f%%", round(length(strong.trt)/NROW(u) * 100))

Pf.cdrp$data %<>% dplyr::filter(Metadata_broad_sample %in% strong.trt)

Pf.cdrp$data %<>% 
  dplyr::select(one_of(c(Pf.cdrp$feat_cols, 
                         "Metadata_broad_sample",
                         "MOA",
                         "CPD_NAME",
                         "Target"))) %>%
  dplyr::group_by(Metadata_broad_sample, 
                  MOA,
                  CPD_NAME,
                  Target) %>% 
  dplyr::summarise_each(funs("mean")) %>% 
  dplyr::ungroup() 

Pf.repurp$data %<>% 
  group_by(Metadata_pert_iname) %>%
  slice(1) %>%
  ungroup(.)

Pf.cdrp$data %<>% 
  group_by(CPD_NAME) %>%
  slice(1) %>%
  ungroup(.)

```

```{r restricting to the common compounds, eval=T}

Pf.repurp$data$Metadata_pert_iname <- Pf.repurp$data$Metadata_pert_iname %>% str_to_lower() 
Pf.cdrp$data$CPD_NAME <- Pf.cdrp$data$CPD_NAME %>% str_to_lower()

cmpd1 <- Pf.repurp$data$Metadata_pert_iname
cmpd2 <- Pf.cdrp$data$CPD_NAME

if (just.common.cmpds) {
  cmpd <- setdiff(intersect(cmpd1, cmpd2), c("", NA, "NA"))
} else {
  cmpd <- c(cmpd1, cmpd2) %>% unique
}
  

print(length(cmpd))

if (set.moa.to.cmpd.name) {
  Pf.repurp$data %<>%
    dplyr::filter(Metadata_pert_iname %in% cmpd) %>%
    dplyr::mutate(Metadata_moa = Metadata_pert_iname)
  
  Pf.cdrp$data %<>%
    dplyr::filter(CPD_NAME %in% cmpd) %>%
    dplyr::mutate(MOA = CPD_NAME)
  
} else {
    Pf.repurp$data %<>%
    dplyr::filter(Metadata_pert_iname %in% cmpd) %>%
    dplyr::mutate(Metadata_moa = paste(Metadata_pert_iname, Metadata_moa, sep = "|"))
  
  Pf.cdrp$data %<>%
    dplyr::filter(CPD_NAME %in% cmpd) %>%
    dplyr::mutate(MOA = paste(CPD_NAME, MOA, sep = ", "))
}

```

```{r do cca, eval = do.cca}

x <- cancor(Pf.cdrp$data[,Pf.cdrp$feat_cols], Pf.repurp$data[,Pf.repurp$feat_cols], xcenter = F, ycenter = F)

x1 <- apply(Pf.cdrp$data[,Pf.cdrp$feat_cols], 1, function(row) (row - x$xcenter)) %>% t
x1 <- x1[,1:NROW(x$xcoef)] %*% x$xcoef
x1 <- as.data.frame(x1)

x2 <- apply(Pf.repurp$data[,Pf.repurp$feat_cols], 1, function(row) (row - x$ycenter)) %>% t
x2 <- x2[,1:NROW(x$ycoef)] %*% x$ycoef
x2 <- as.data.frame(x2)

fact_cols <- setdiff(colnames(Pf.cdrp$data), Pf.cdrp$feat_cols)
cdrp <- list(data = cbind(x1, Pf.cdrp$data[,fact_cols]), feat_cols = colnames(x1), factor_cols = fact_cols)

fact_cols <- setdiff(colnames(Pf.repurp$data), Pf.repurp$feat_cols)
repurp <- list(data = cbind(x2, Pf.repurp$data[,fact_cols]), feat_cols = colnames(x2), factor_cols = fact_cols)

Pf.cdrp <- cdrp
Pf.repurp <- repurp

```

```{r Find the correlation matrix, eval=T}

cr <- cor(Pf.repurp$data[,Pf.repurp$feat_cols] %>% t, 
          Pf.cdrp$data[,Pf.cdrp$feat_cols] %>% t, 
          method = corr.type)

rownames(cr) <- Pf.repurp$data$Metadata_broad_sample
colnames(cr) <- Pf.cdrp$data$Metadata_broad_sample

cr.melt <- cr %>% melt

cr.melt <- cr.melt %>% group_by(Var1, Var2) %>% dplyr::summarise(value = mean(value, na.rm = T))

crx <- cr.melt %>% reshape2::dcast(Var1 ~ Var2)
crx <- crx %>% 
  tibble::column_to_rownames(., var = "Var1")

cr <- crx

```

```{r}

cr.melt.ext <- cr.melt %>% 
  dplyr::left_join(., unique(Pf.repurp$data[,c("Metadata_broad_sample",
                                      "Metadata_pert_iname",
                                      "Metadata_moa")]), 
                   by = c("Var1" = "Metadata_broad_sample")) %>%
  dplyr::left_join(., unique(Pf.cdrp$data[,c("Metadata_broad_sample",
                                             "CPD_NAME",
                                             "MOA")]), 
                   by = c("Var2" = "Metadata_broad_sample"))
  
cr.melt.ext %<>% 
  dplyr::filter(!is.infinite(value))

matching.moas <- function(moa1, moa2) {
  m1 <- setdiff(str_split(moa1, ", ")[[1]], c(NA, "NA", ""))
  m2 <- setdiff(str_split(moa2, "\\|")[[1]], c(NA, "NA", ""))
  any(m1 %in% m2)
}

matching.moas <- Vectorize(matching.moas)

cr.melt.ext2 <- cr.melt.ext %>% 
  dplyr::mutate(match = matching.moas(MOA, Metadata_moa))

```

```{r}

cr.melt.ext2.sor <- cr.melt.ext2 %>% 
  dplyr::arrange(-value) %>%
  dplyr::filter(!is.na(match)) %>% dplyr::ungroup()

n <- round(0.01 * NROW(cr.melt.ext2.sor))

v11 <- cr.melt.ext2.sor %>% 
  dplyr::slice(1:n) %>%
  dplyr::select(match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v12 <- cr.melt.ext2.sor %>% 
  dplyr::slice(1:n) %>%
  dplyr::select(match) %>%
  dplyr::mutate(match = !match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v21 <- cr.melt.ext2.sor %>% 
  dplyr::slice((n+1):NROW(cr.melt.ext2.sor)) %>%
  dplyr::select(match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)
v22 <- cr.melt.ext2.sor %>% 
  dplyr::slice((n+1):NROW(cr.melt.ext2.sor)) %>%
  dplyr::select(match) %>%
  dplyr::mutate(match = !match) %>%
  as.matrix() %>% 
  as.vector() %>%
  sum(., na.rm = T)

V <- rbind(c(v11, v12), c(v21, v22))
fisher.test(V, alternative = "greater") %>% print

d <- cr.melt.ext2.sor %>% 
    dplyr::slice(1:n) %>%
    dplyr::filter(match) %>%
    dplyr::arrange(MOA) 

d %>%
    htmlTable::htmlTable()

c <- cr.melt.ext2.sor %>%
  dplyr::filter(match) %>%
  dplyr::group_by(MOA) %>%
  dplyr::tally()
colnames(c)[2] <- "n.total"
  
d %>% 
  dplyr::group_by(MOA) %>%
  dplyr::tally() %>% 
  dplyr::left_join(., c, by = "MOA") %>%
  dplyr::mutate(ratio = round(n/n.total, 3)) %>%
  dplyr::arrange(-ratio) %>%
  htmlTable::htmlTable()

```

```{r matching CDRP to BBBC022, eval=!error.analysis}

k <- max(round(perc.top * length(cmpd)), 1)
N <- 300

d <- cr.melt.ext2.sor %>% 
  dplyr::group_by(Var1, Metadata_moa) %>%
  dplyr::slice(1:k) %>%
  dplyr::summarise(success = any(match)) %>% 
  dplyr::filter(success) 
  
ns <- c()

for (i in 1:N) {
  n <- d.null <- cr.melt.ext2.sor %>% 
    dplyr::group_by(Var1, Metadata_moa) %>%
    dplyr::sample_n(k) %>%
    dplyr::summarise(success = any(match)) %>% 
    dplyr::filter(success) %>%
    NROW
  
  ns <- c(ns, n)
}
  
print(NROW(d)/length(unique(cr.melt.ext2.sor$Var1)))
print(mean(ns)/length(unique(cr.melt.ext2.sor$Var1)))
print(NROW(d)/mean(ns))


```

```{r matching BBBC022 to CDRP, eval=!error.analysis}

k <- max(round(perc.top * length(cmpd)), 1)
N <- 300

d <- cr.melt.ext2.sor %>% 
  dplyr::group_by(Var2, MOA) %>%
  dplyr::slice(1:min(k, NROW(.))) %>%
  dplyr::summarise(success = any(match)) %>% 
  dplyr::filter(success) 
  
ns <- c()

for (i in 1:N) {
  n <- d.null <- cr.melt.ext2.sor %>% 
    dplyr::sample_frac(1) %>%
    dplyr::group_by(Var2, MOA) %>%
    dplyr::slice(1:min(k, NROW(.))) %>%
    dplyr::summarise(success = any(match)) %>% 
    dplyr::filter(success) %>%
    NROW
  
  ns <- c(ns, n)
}
  
print(NROW(d)/length(unique(cr.melt.ext2.sor$Var2)))
print(mean(ns)/length(unique(cr.melt.ext2.sor$Var2)))
print(NROW(d)/mean(ns))


```

```{r}

thr <- cr.melt.ext2 %>% 
  dplyr::ungroup() %>%
  dplyr::filter(!match) %>%
  dplyr::select(value) %>%
  as.matrix() %>% 
  as.vector() %>%
  quantile(., 0.95)

d <- cr.melt.ext2 %>%
  dplyr::filter(match & value > thr) %>%
  NROW

print(d/sum(cr.melt.ext2$match))

```

```{r error analysis, eval=error.analysis}

u.cdrp <- u.cdrp %>% filter(cr >= thr.cdrp)
u.repurp <- u.repurp %>% filter(cr >= thr.repurp)

dx <- cr.melt.ext2.sor %>% left_join(., u.cdrp, by = c("Var2" = "Metadata_broad_sample")) 
dx2 <- dx %>% left_join(., u.repurp, by = c("Var1" = "Metadata_broad_sample"))

n <- dx$match %>% sum
D.tst <- dx2 %>% 
  dplyr::select(match, value, cr.x, cr.y) %>%
  dplyr::rename(rep.cor.cdrp = cr.x,
                rep.cor.repurp = cr.y,
                signature.cor = value) %>%
  dplyr::mutate(min.rep.cor = ifelse(rep.cor.cdrp < rep.cor.repurp, rep.cor.cdrp, rep.cor.repurp))

D <- D.tst %>% 
  dplyr::group_by(match) %>%
  dplyr::sample_n(n) 

g <- ggplot(D, aes(x = min.rep.cor, y = signature.cor, color = match)) + 
  geom_point(stat = "identity") + 
  ylab("Signatures correlation for a compound pair") +
  xlab("Minimum of replicate correlation for a compound pair")

ggsave("charac_plot.pdf", g)

fn <- function(rep.cor.cdrp, 
               rep.cor.repurp, 
               signature.cor, 
               sig.cor.thr, 
               rep.cor.thr.cdrp, 
               rep.cor.thr.repurp) {
  
  return(rep.cor.cdrp > rep.cor.thr.cdrp &
         rep.cor.repurp > rep.cor.thr.repurp &
         signature.cor > sig.cor.thr)
}

evaluate.thrs <- function(rep.cor.thr.cdrp, 
                          rep.cor.thr.repurp, 
                          sig.cor.thr) {
  t <- D.tst %>%
    filter(fn(rep.cor.cdrp, rep.cor.repurp, signature.cor, sig.cor.thr, rep.cor.thr.cdrp, rep.cor.thr.repurp))
  
  n <- D.tst %>%
    filter(!fn(rep.cor.cdrp, rep.cor.repurp, signature.cor, sig.cor.thr, rep.cor.thr.cdrp, rep.cor.thr.repurp))
  
  tp <-  t %>%
    select(match) %>%
    as.matrix() %>%
    as.vector() %>%
    sum

  tn <- n %>%
    select(match) %>%
    mutate(match = !match) %>%
    as.matrix() %>%
    as.vector() %>%
    sum
  
  fp <- t %>%
    select(match) %>%
    mutate(match = !match) %>%
    as.matrix() %>%
    as.vector() %>%
    sum

  fn <- n %>%
    select(match) %>%
    as.matrix() %>%
    as.vector() %>%
    sum
  
  tpr <- tp/(tp + fn)
  fpr <- fp/(fp + tn)
  precision <- tp/(tp + fp)
  sensitivity <- tpr
  specificity <- tn/(tn + fp)
  f.score <- 2*tp/(2*tp + fp + fn)

  return(f.score)  
#   return(list(tpr = tpr,
#               fpr = fpr, 
#               precision = precision,
#               sensitivity = sensitivity,
#               specificity = specificity, 
#               f.score = f.score))
}

evaluate.thrs <- Vectorize(evaluate.thrs)

sq <- seq(from = 0.2, to = 0.7, by = 0.02)

final.opt <- function(sig.cor.thr) {
  d.eval <- outer(sq, sq, function(x, y) evaluate.thrs(x, y, sig.cor.thr))
  
  rownames(d.eval) <- sq
  colnames(d.eval) <- sq
  d.eval.melt <- d.eval %>% reshape2::melt()
  
  opt <- d.eval.melt %>%
    arrange(-value) %>%
    slice(1) %>%
    select(Var1, Var2, value) 
  return(opt)
}

l <- foreach (x = sq) %dopar% {
  final.opt(x)[3]
}
  
l <- unlist(l)

s.max <- max(l)
i <- which.max(l)
opt <- final.opt(sq[i])

print(sprintf("rep.cor cdrp : %f", opt[1]))
print(sprintf("rep.cor repurp : %f", opt[2]))
print(sprintf("sig.cor thr : %f", sq[i]))
print(sprintf("optimal f.score : %f", s.max))

```
