```{r}
rm(list = ls())

library(dplyr)
library(stringr)
library(readr)
library(magrittr)
library(reshape2)
library(htmlTable)
library(ggplot2)
library(foreach)
library(doParallel)

doParallel::registerDoParallel(cores = 3)

Pf <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")

feat <- Pf %>% 
          dplyr::select(-dplyr::contains("Metadata_")) %>% 
          colnames()

metadata.ext <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
brd.full <- unique(Pf$Metadata_broad_sample)
brds <- lapply(brd.full, function(x) paste(str_split(x,
                                                                             "-")[[1]][1:2], 
                                                   sep = "-", collapse = "-")) %>% unlist()
brd.mapping <- data.frame(BROAD_CPD_ID = brds, 
                          Image_Metadata_BROAD_ID = brd.full)
metadata.ext %<>% 
  dplyr::select(BROAD_CPD_ID, CPD_NAME) %>% 
  dplyr::filter(BROAD_CPD_ID %in% brds) %>%
  dplyr::mutate(CPD_NAME = ifelse(str_detect(CPD_NAME, "BRD-"), "", CPD_NAME)) %>%
  dplyr::inner_join(., brd.mapping, by = "BROAD_CPD_ID") %>%
  dplyr::select(-BROAD_CPD_ID)

metadata <- data.frame(Metadata_broad_sample = unique(Pf$Metadata_broad_sample))
metadata %<>% 
  dplyr::left_join(., metadata.ext, by = c("Metadata_broad_sample" = "Image_Metadata_BROAD_ID"))

Pf %<>% dplyr::left_join(., metadata, by = "Metadata_broad_sample")

Pf %<>% dplyr::select(one_of(c(feat, "Metadata_broad_sample", "CPD_NAME"))) %>%
  dplyr::group_by(Metadata_broad_sample, CPD_NAME) %>%
  dplyr::summarise_each(funs("mean"))

Pf %<>% dplyr::mutate(CPD_NAME = str_to_lower(CPD_NAME))
Pf %<>% dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME, "-", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, " ", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\(", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\)", "")) 
  

MOA <- read.csv("../input/moas.txt", sep = "\t")
MOA %<>% dplyr::mutate(Name = str_to_lower(Name)) %>%
  dplyr::mutate(Name_san = str_replace_all(Name, "-", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, " ", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\(", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\)", "")) 

Pf %<>% dplyr::left_join(., MOA, by = c("CPD_NAME_san" = "Name_san"))
meta.col <- setdiff(colnames(Pf), feat)
saveRDS(list(data = Pf, feat_cols = feat, factor_cols = meta.col), "Pf_annotated.rds")

```

```{r, eval=F}

Pf %<>% dplyr::filter(!is.na(MOA) & CPD_NAME != "")
moas <- Pf[, c("CPD_NAME", "MOA")]

cr <- Pf[,feat] %>% t %>% cor
rownames(cr) <- Pf$CPD_NAME
colnames(cr) <- Pf$CPD_NAME

cr.melt <- cr %>% melt %>% dplyr::filter(Var1 != Var2)

cr.melt %<>% dplyr::left_join(., moas, by = c("Var1" = "CPD_NAME")) %>%
  dplyr::left_join(., moas, by = c("Var2" = "CPD_NAME"))

k <- 5

is.matching <- function(x) {
any(setdiff(str_split(x[,"MOA.x"], ", ") %>% unlist, NA) %in% setdiff(str_split(x[,"MOA.y"], ", ") %>% unlist, NA)) |
        any(setdiff(str_split(x[,"MOA.y"], ", ") %>% unlist, NA) %in% setdiff(str_split(x[,"MOA.x"], ", ") %>% unlist, NA))
}

res <- cr.melt %>% 
  arrange(-value) %>%
  group_by(Var1, MOA.x) %>%
  do(data.frame(has.a.match = is.matching(.[1:k,]))) %>%
  dplyr::filter(has.a.match) %>% 
  dplyr::select(-has.a.match) %>% 
  dplyr::arrange(MOA.x) 

res %>%
  htmlTable::htmlTable()

print(sprintf("ratio of compounds with a same MOA compound being in their %d-NN : %f", k, NROW(res)/NROW(cr)))

acc <- c()
for (i in 1:100) {
  res <- cr.melt %>% 
    arrange(-value) %>%
    group_by(Var1, MOA.x) %>%
    do(data.frame(has.a.match = is.matching(.[sample(1:NROW(cr), k),]))) %>%
    dplyr::filter(has.a.match) %>% 
    dplyr::select(-has.a.match) %>% 
    dplyr::arrange(MOA.x) 
  
  acc <- c(acc, NROW(res)/NROW(cr))
}

print(mean(acc))
print(quantile(acc, 0.95))
print(quantile(acc, 0.99))

```

```{r, eval=T}

N <- 10
ks <- 1:40

Pf %<>% dplyr::filter(!is.na(MOA) & CPD_NAME != "")
moas <- Pf[, c("CPD_NAME", "MOA")]

cr <- Pf[,feat] %>% t %>% cor
rownames(cr) <- Pf$CPD_NAME
colnames(cr) <- Pf$CPD_NAME

cr.melt <- cr %>% melt %>% dplyr::filter(Var1 != Var2)

cr.melt %<>% dplyr::left_join(., moas, by = c("Var1" = "CPD_NAME")) %>%
  dplyr::left_join(., moas, by = c("Var2" = "CPD_NAME"))

is.matching <- function(x) {
any(setdiff(str_split(x[,"MOA.x"], ", ") %>% unlist, NA) %in% setdiff(str_split(x[,"MOA.y"], ", ") %>% unlist, NA)) |
        any(setdiff(str_split(x[,"MOA.y"], ", ") %>% unlist, NA) %in% setdiff(str_split(x[,"MOA.x"], ", ") %>% unlist, NA))
}
D <- data.frame(k = c(0, 0), meas = c(0, 0), type = c("data", "null"), ci = c(0, 0))

cr.arr.grp <- cr.melt %>% 
      arrange(-value) %>%
      group_by(Var1, MOA.x)
 
for (k in ks) {
  res <- cr.arr.grp %>%
    do(data.frame(has.a.match = is.matching(.[1:k,]))) %>%
    dplyr::filter(has.a.match)
  
  D <- rbind(D, data.frame(k = k, meas = NROW(res)/NROW(cr), type = "data", ci = 0))
  
  baseline <- foreach (i = 1:N) %dopar% {
    res <- cr.arr.grp %>%
      do(data.frame(has.a.match = is.matching(.[sample(1:NROW(cr), k),]))) %>%
      dplyr::filter(has.a.match) 
    
    NROW(res)/NROW(cr)
  }
  baseline <- unlist(baseline)
  D <- rbind(D, data.frame(k = k, meas = mean(baseline), type = "null", ci = sd(baseline)/(N^0.5)))  
}

g <- ggplot(D, aes(x = k, y = meas, color = type)) + 
  ggplot2::geom_line() + 
  ggplot2::geom_errorbar(aes(ymin = meas - ci, ymax = meas + ci), width = 0.1) +
  ggplot2::ylab("ratio of same MOA compound pairs")

g

ggsave("CDRP_eval_MOA.pdf", g, width = 6, height = 4)

```
