
```{r}
rm(list = ls())

library(dplyr)
library(stringr)
library(readr)
library(magrittr)
library(reshape2)
library(htmlTable)

Pf <- readRDS("../results/master/2017-04-18_c69b4f5e/Pf_new.rds")
feat <- Pf %>% 
          dplyr::select(-dplyr::contains("Metadata_")) %>% 
          colnames()

metadata.ext <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
brd.full <- unique(Pf$Metadata_broad_sample)
brds <- lapply(brd.full, function(x) paste(str_split(x,
                                                                             "-")[[1]][1:2], 
                                                   sep = "-", collapse = "-")) %>% unlist()
brd.mapping <- data.frame(BROAD_CPD_ID = brds, 
                          Image_Metadata_BROAD_ID = brd.full)
metadata.ext %<>% 
  dplyr::select(BROAD_CPD_ID, CPD_NAME) %>% 
  dplyr::filter(BROAD_CPD_ID %in% brds) %>%
  dplyr::mutate(CPD_NAME = ifelse(str_detect(CPD_NAME, "BRD-"), "", CPD_NAME)) %>%
  dplyr::inner_join(., brd.mapping, by = "BROAD_CPD_ID") %>%
  dplyr::select(-BROAD_CPD_ID)

#metadata.ext2 <- read_csv("../input/Gustafsdottir/manual/metadata.csv")
#metadata.ext2 %<>% 
#  dplyr::select(Image_Metadata_BROAD_ID, Image_Metadata_SOURCE_COMPOUND_NAME) %>% 
#  dplyr::filter(Image_Metadata_BROAD_ID %in% Pf$Metadata_broad_sample) %>% unique()

metadata <- data.frame(Metadata_broad_sample = unique(Pf$Metadata_broad_sample))
metadata %<>% 
  dplyr::left_join(., metadata.ext, by = c("Metadata_broad_sample" = "Image_Metadata_BROAD_ID"))

Pf %<>% dplyr::left_join(., metadata, by = "Metadata_broad_sample")

Pf %<>% dplyr::filter(CPD_NAME != "")

Pf %<>% dplyr::select(one_of(c(feat, "Metadata_broad_sample", "CPD_NAME"))) %>%
  dplyr::group_by(Metadata_broad_sample, CPD_NAME) %>%
  dplyr::summarise_each(funs("mean"))

Pf %<>% dplyr::mutate(CPD_NAME = str_to_lower(CPD_NAME))
Pf %<>% dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME, "-", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, " ", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\(", "")) %>%
  dplyr::mutate(CPD_NAME_san = str_replace_all(CPD_NAME_san, "\\)", "")) 
  

MOA <- read.csv("../input/moas.txt", sep = "\t")
MOA %<>% dplyr::mutate(Name = str_to_lower(Name)) %>%
  dplyr::mutate(Name_san = str_replace_all(Name, "-", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, " ", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\(", "")) %>%
  dplyr::mutate(Name_san = str_replace_all(Name_san, "\\)", "")) 

Pf %<>% dplyr::left_join(., MOA, by = c("CPD_NAME_san" = "Name_san"))
meta.col <- setdiff(colnames(Pf), feat)
saveRDS(list(data = Pf, feat_cols = feat, factor_cols = meta.col), "Pf_annotated.rds")

```

```{r}

Pf %<>% dplyr::filter(!is.na(MOA))
moas <- Pf[, c("CPD_NAME", "MOA")]

cr <- Pf[,feat] %>% t %>% cor
rownames(cr) <- Pf$CPD_NAME
colnames(cr) <- Pf$CPD_NAME

cr.melt <- cr %>% melt %>%
  dplyr::filter(as.character(Var1) < as.character(Var2))

cr.melt %<>% dplyr::left_join(., moas, by = c("Var1" = "CPD_NAME")) %>%
  dplyr::left_join(., moas, by = c("Var2" = "CPD_NAME"))

valid <- apply(cr.melt, 1, function(x) (any(str_split(x["MOA.x"], ", ")[[1]] %in% str_split(x["MOA.y"], ", ")[[1]]) |
        any(str_split(x["MOA.y"], ", ")[[1]] %in% str_split(x["MOA.x"], ", ")[[1]])))
        
cr.melt.val <- cr.melt %>% dplyr::mutate(valid = valid)

thr <- cr.melt.val$value %>% abs %>% quantile(., 0.95)

v11 <- cr.melt.val %>% dplyr::filter(abs(value) > thr & valid) %>% NROW
v12 <- cr.melt.val %>% dplyr::filter(abs(value) > thr & !valid) %>% NROW
v21 <- cr.melt.val %>% dplyr::filter(abs(value) < thr & valid) %>% NROW
v22 <- cr.melt.val %>% dplyr::filter(abs(value) < thr & !valid) %>% NROW
V <- rbind(c(v11, v12), c(v21, v22))

fisher.test(V, alternative = "greater") %>% print

cr.melt.val %>% dplyr::filter(abs(value) > thr & valid) %>% 
  arrange(MOA.x) %>% htmlTable::htmlTable()

tot <- cr.melt.val %>% group_by(MOA.x) %>% tally %>% dplyr::select(MOA.x, n)
colnames(tot)[2] <- "total.n"

cr.melt.val %>% dplyr::filter(abs(value) > thr & valid) %>% 
  group_by(MOA.x) %>% tally %>% arrange(-n) %>% 
  dplyr::left_join(., tot, by = "MOA.x") %>% htmlTable::htmlTable()

rownames(V) <- c("top 5 percent", "remainder")
colnames(V) <- c("validated", "non-validated")

V %>% htmlTable::htmlTable()


```
