---
title: "Plot figures for paper"
output: html_notebook
---

```{r message=FALSE}
library(magrittr)
library(glue)
library(tidyverse)
```

```{r}
statistics_agg <- read_csv("output/statistics_agg.csv")
```


```{r}
plot_paper_figure <- 
  function(test_type, 
           annotate_column, 
           Conci,
           strong_effect_threshold = 2,
           compound_list = NULL) {
  
  statistics_agg <-
    statistics_agg %>%
    filter(Conc == Conci) %>%
    mutate(pval_adj = .data[[paste0(test_type, "_pval_adj")]])
    
  p <- 
    statistics_agg %>%
    ggplot(aes(Broad, -log10(pval_adj), shape = is_cp_negcon, color = is_inhibitor)) +
    geom_point()
  
  if (annotate_column == "median_ratio") {
    p <- p +
      ggrepel::geom_text_repel(
        data = statistics_agg %>% filter(is_inhibitor),
        aes(label = sprintf("%0.2f", median_ratio)),
        max.overlaps = Inf,
        min.segment.length = unit(0, 'lines'),
        nudge_y = .3,
        color = "black",
        alpha = 0.5,
        size = 3
      )
  }
  
  if (annotate_column == "significant") {
    p <- p +
      ggrepel::geom_text_repel(
        data = statistics_agg %>% filter(-log10(pval_adj) > strong_effect_threshold),
        aes(label = Cmpd),
        max.overlaps = Inf,
        min.segment.length = unit(0, 'lines'),
        nudge_y = .3,
        color = "black",
        alpha = 0.5,
        size = 3
      )
    
  }
  
  
  if (annotate_column == "compound_list") {
    p <- p +
      ggrepel::geom_text_repel(
        data = statistics_agg %>% filter(Cmpd %in% compound_list),
        aes(label = Cmpd),
        max.overlaps = Inf,
        min.segment.length = unit(0, 'lines'),
        nudge_y = .3,
        color = "black",
        alpha = 0.5,
        size = 3
      )
    
  } 
  
  p <- p +
    geom_hline(yintercept = -log10(0.01), linetype = "dotted") +
    coord_cartesian(clip = "off") +
    xlab("Cell Painting Correlation") +
    ylab(glue("-log10 adjusted p-value ({test_type}-test)")) +
    theme_bw()
  
  p <- p +
    theme(panel.border = element_blank(),
          panel.grid = element_blank())
  
  p <- p + ggtitle(glue("Conc = {Conci}"))
  
  ggsave(
    glue("output/p38_{test_type}_tlr_annot_{annotate_column}_conc_{Conci}.png"),
    width = 6,
    height = 4
  )
  
  ggsave(
    glue("output/p38_{test_type}_tlr_annot_{annotate_column}_conc_{Conci}.svg"),
    width = 6,
    height = 4
  )  
  
  p
  }

plot_paper_figure("ks", "compound_list", Conci = Conci, compound_list = compound_list)
```


Pick the 4 hits across KS-test and t-test -based selection

```{r}
compound_list <- c("K543", "A649", "K381", "K523")
```


```{r}
Conci <- 1

p <- plot_paper_figure("ks", "compound_list", Conci = Conci, compound_list = compound_list)

print(p)

p <- plot_paper_figure("t", "compound_list", Conci = Conci, compound_list = compound_list)

print(p)
```
