```{r Load Gene OE and Compound data, eval=TRUE, warning=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(plyr)
library(reshape2)
library(htmlTable)
library(foreach)
library(doMC)
library(magrittr)
library(readr)
registerDoMC(cores = 3)

source("rep.corr.func.R")
use.repurp.annots <- F
permute.moas <- F
seed.moa <- -8     ## ignore, if permute.moas is False
LUAD <- F
LUAD.mut <- F
just.bioactives <- T
cor.thr <- 0.45
n.ppi.thr <- -1
N <- 2000                     ## number of Monte-carlo simulations to estimate expected random matches
genes.to.remove <- c()        ## remove these genes before making matches

base.dir <- "2016-07-20_90b7bb86"
use.feat.selected.in.TA.ORF.in.common <- F
corr.type <- "pearson"

if (LUAD) {
  load("../input/LUAD/LUAD.RData")
  Pf.ta <- list(data = Px, factor_cols = "Metadata_x_mutation_status", feat_cols = setdiff(colnames(Px), "Metadata_x_mutation_status"))
  Pf.ta.all <- Pf
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "Treatment")
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta.all$factor_cols <- c(Pf.ta.all$factor_cols, "Treatment")

  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta.all$data$Treatment <- lapply(Pf.ta.all$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta$data <- Pf.ta$data %>% dplyr::group_by(Treatment) %>% slice(1) %>% dplyr::ungroup()
} else if (LUAD.mut) {
  load("../input/LUAD/LUAD.RData")
  Pf.ta <- list(data = Px, factor_cols = "Metadata_x_mutation_status", feat_cols = setdiff(colnames(Px), "Metadata_x_mutation_status"))
  Pf.ta.all <- Pf
  a <- read.csv("../input/LUAD/allele_classification.csv")
  GOF <- a$Allele[which(a$Benchmark.activity == "GOF" | a$eVIP_prediction %in% c("GOF", "Neutral"))]
  s <- Pf.ta$data$Metadata_x_mutation_status %>% unique
  s <- s[which(str_detect(s, "_WT"))]
  GOF <- c(as.character(GOF), as.character(s))
  
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Metadata_x_mutation_status %in% GOF) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "Treatment")
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(str_detect(Metadata_x_mutation_status, "WT")) %>% dplyr::mutate(Treatment = Metadata_x_mutation_status)
  Pf.ta.all$factor_cols <- c(Pf.ta.all$factor_cols, "Treatment")

  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta.all$data$Treatment <- lapply(Pf.ta.all$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist
  Pf.ta$data <- dplyr::left_join(Pf.ta$data, uu, by = "Metadata_x_mutation_status")
  Pf.ta$factor_cols <- c(Pf.ta$factor_cols, "strn")
  Pf.ta$data <- Pf.ta$data %>% dplyr::group_by(Treatment) %>% arrange(-strn) %>% slice(1) %>% dplyr::ungroup()
  Pf.ta$data %>% dplyr::select(Treatment, Metadata_x_mutation_status, strn) %>% unique %>% knitr::kable()
} else {
  load("../input/TA/Initial_analysis_workspace_new.RData")
  Pf.ta <- Pf_org.org.collapsed
  Pf.ta.all <- Pf_org.org
  strong.trt <- Pf.trt.strong.collapsed$data$Treatment
  data.annot <- Pf.strong %>% dplyr::filter(Treatment %in% strong.trt) %>% dplyr::select(one_of(c("Treatment", "Pathway", "Gene", "AlleleDesc"))) %>% 
    dplyr::mutate(Pathway = str_replace(Pathway, "Canonical ", "")) %>% 
    dplyr::mutate(AlleleDesc = str_sub(AlleleDesc, 1, 2)) %>%
    dplyr::filter(AlleleDesc == "WT") %>% dplyr::group_by(Gene) %>% dplyr::slice(1) %>%
    dplyr::ungroup() 
  desired.ta <- data.annot$Treatment
  Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(Treatment %in% c(as.character(desired.ta), "EMPTY_")) 
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
  
  Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
  Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist 
}

Pf.gene <- Pf.ta
Pf.gene.all <- Pf.ta.all
Pf.gene$data <- Pf.gene$data %>% dplyr::filter(! Treatment %in% genes.to.remove)


############

Pf.cmpd <- readRDS("../results/master/2017-04-20_64917c8b/Pf_annotated.rds")
Pf.cmpd$data %<>% mutate(CPD_NAME = ifelse(CPD_NAME != "", CPD_NAME, Metadata_broad_sample))

source("rep.corr.func.R")
Pf.1 <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")
if (!just.bioactives) {
  Pf.2 <- readRDS("../results/master/2017-04-20_425d653/Pf_DOS_new.rds")
  Pf <- rbind(Pf.1, Pf.2)
} else {
  Pf <- Pf.1 
}

u <- rep.cor(list(data = Pf, feat_cols = Pf.cmpd$feat_cols, factor_cols = Pf.cmpd$factor_cols), grp.var = "Metadata_broad_sample", feat.var = Pf.cmpd$feat_cols)
up <- readr::read_csv("../results/master/2017-04-21_425d6537/Cell_counts.csv")

x <- Pf %>% 
  left_join(., u, by = "Metadata_broad_sample") %>%
  left_join(., up, by = c("Metadata_Plate" = "Image_Metadata_Plate", "Metadata_Well" = "Image_Metadata_Well")) %>%
  select(Metadata_broad_sample, cr, Image_Count_Cells) %>%
  group_by(Metadata_broad_sample) %>%
  summarise_each(funs(mean))
  
Pf.cmpd$data %<>% 
  right_join(., x, by = "Metadata_broad_sample") %>%
  mutate(rep.corr = round(cr, 2), Mean_Cells_Count = round(Image_Count_Cells, 2)) %>%
  select(-cr, -Image_Count_Cells) 

Pf.cmpd$factor_cols <- c(Pf.cmpd$factor_cols, "rep.corr", "Mean_Cells_Count")
Pf.cmpd$data$Mean_Cells_Count <- round(scale(Pf.cmpd$data$Mean_Cells_Count), 2)

```

```{r Align the features in Compound and Gene OE data, eval=TRUE}

f1 <- Pf.cmpd$feat_cols
f2 <- Pf.gene$feat_cols
f <- intersect(f1, f2)

Pf.cmpd$feat_cols <- f
Pf.gene$feat_cols <- f

Pf.cmpd$data <- Pf.cmpd$data[,c(Pf.cmpd$factor_cols, Pf.cmpd$feat_cols)]
Pf.gene$data <- Pf.gene$data[,c(Pf.gene$factor_cols, Pf.gene$feat_cols)]

if (use.feat.selected.in.TA.ORF.in.common) {
  feats <- Pf_org$feat_cols
  feats <- intersect(feats, Pf.cmpd$feat_cols)
  Pf.cmpd$feat_cols <- feats
  Pf.cmpd$data <- Pf.cmpd$data[,c(feats, Pf.cmpd$factor_cols)]
  Pf.gene$feat_cols <- feats
  Pf.gene$data <- Pf.gene$data[,c(feats, Pf.gene$factor_cols)]
}

print(length(Pf.cmpd$feat_cols))
print(NROW(Pf.cmpd$data))

print(length(Pf.gene$feat_cols))
print(NROW(Pf.gene$data))

```

```{r Find the correlation matrix, eval=T}

cr <- cor(Pf.cmpd$data[,Pf.cmpd$feat_cols] %>% t, Pf.gene$data[,Pf.gene$feat_cols] %>% t, method = cor_type)
rownames(cr) <- Pf.cmpd$data$CPD_NAME
colnames(cr) <- Pf.gene$data$Treatment
cr.melt <- melt(cr)

```

```{r}

moas <- read.csv("../input/moas.txt", sep = "\t")

get.interacting.proteins <- function(protein.name) {
  dr <- "../results/manual/ppis"
  if (!dir.exists(dr)) {
    system(sprintf("mkdir -p %s", dr))
  }
  f.name <- sprintf("%s/%s.rds", dr, protein.name)
  if (file.exists(f.name)) {
    return(readRDS(f.name))
  }
  
  tbl <- read.table(sprintf("http://webservice.thebiogrid.org/interactions/?searchNames=true&geneList=%s&taxId=9606&includeHeader=true&accesskey=ca950b072394ce1897811022f7757222", protein.name), sep="\t", header = FALSE, fill = T)
  tbl <- tbl[, c(8, 9, 12, 13, 14)] 
  colnames(tbl) <- c("Protein.1", "Protein.2", "Method", "Type", "Evidence")
  saveRDS(tbl, f.name)
  return(tbl)
}

get.all.interacting.proteins <- function(protein.name) {
  res <- c()
  for (p in protein.name) {
    ppi <- tryCatch(get.interacting.proteins(p), error = function(e) {})
    res <- rbind(res, ppi)
  }
  return(res)
}

get.all.interacting.proteins.brief <- function(protein.name) {
  protein.name <- str_split(protein.name, ", ")[[1]]
  if (protein.name == "" || is.na(protein.name) || is.null(protein.name)) {
    return("")
  }
  if (any(protein.name %in% Pf.gene$data$Treatment)) {
    return(protein.name %>%
      unique() %>%
      intersect(., Pf.gene$data$Treatment) %>%
      paste(., sep = ", ", collapse = ", ") %>%
      paste(., ", ", sep = ""))
  } else {
    return("")
  }
  
  res <- get.all.interacting.proteins(protein.name)
  if (!is.null(res)) {
    res <- res %>% 
      group_by(Protein.1, Protein.2) %>%
      tally %>%
      arrange(-n) %>%
      filter(Protein.1 %in% Pf.gene$data$Treatment | Protein.2 %in% Pf.gene$data$Treatment) %>% 
      slice(1) %>%
      select(Protein.1, Protein.2) %>%
      as.matrix() %>% 
      as.vector() %>%
      c(., protein.name) %>%
      unique() %>%
      paste(., sep = ", ", collapse = ", ") %>%
      paste(., ", ", sep = "")
    return(res)
  } else {
    return("")  
  }
}

get.all.interacting.proteins.brief.vec <- Vectorize(get.all.interacting.proteins.brief)
#Pf.cmpd$data$relevant.genes <- get.all.interacting.proteins.brief.vec(Pf.cmpd$data$Target)

pred.targ <- function(cr.melt, cor.thr = 0.5) {
  n.genes <- NROW(Pf.gene$data)
  x <- cr.melt %>%
    dplyr::arrange(-value) %>%
    dplyr::group_by(Var1) %>%
    dplyr::slice(c(1, n.genes)) %>%
    dplyr::ungroup() %>%
    dplyr::filter(abs(value) > cor.thr) %>%
    dplyr::left_join(., Pf.cmpd$data[,c("CPD_NAME", "Target")], 
                     by = c("Var1" = "CPD_NAME")) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(gene.tmp = paste(Var2, ", ", sep = "")) %>%
    dplyr::mutate(Target = paste(Target, ", ", sep = "")) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(valid = str_detect(Target, gene.tmp)) %>%
    dplyr::filter(valid) %>%
    dplyr::select(-gene.tmp, -valid) %>%
    dplyr::rename(compound = Var1, gene = Var2, corr. = value) %>%
    dplyr::arrange(gene)
  return(x)
}

```

```{r}

c <- pred.targ(cr.melt, cor.thr = cor.thr) 
c %>% htmlTable::htmlTable()
print(NROW(c))

```

```{r, eval=TRUE}

nl <- c()

library(foreach)
library(doMC)
doMC::registerDoMC(cores = 4)

nl <- foreach (i = 1:N) %dopar% {
  pr <- permute::shuffle(length(Pf.cmpd$data$CPD_NAME))
  rownames(cr) <- Pf.cmpd$data$CPD_NAME[pr]
  cr.melt.sh <- melt(cr)
  c.sh <- pred.targ(cr.melt.sh, cor.thr = cor.thr) 
  NROW(c.sh)
}

nl <- unlist(nl)

print(median(nl))
print(mean(nl))
print(quantile(nl, 0.95))
max(nl)

apply(Pf.cmpd$data, 1, function(x) any(str_detect(x["Target"], Pf.gene$data$Treatment)))  %>% sum(., na.rm = T)

```

