---
title: "R Notebook"
output: html_notebook
---

```{r loading data}

rm(list = ls())

library(dplyr)
library(stringr)
library(magrittr)

Pf.cmpd.data1 <- readRDS("../results/master/2017-04-20_425d653/Pf_DOS_new.rds")
Pf.cmpd.data2 <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")
Pf.cmpd.data <- rbind(Pf.cmpd.data1, Pf.cmpd.data2)

cl <- colnames(Pf.cmpd.data)
meta.cols <- cl[which(str_detect(cl, "Metadata"))]
feat.cols <- setdiff(cl, meta.cols)
Pf.cmpd <- list(data = Pf.cmpd.data, feat_cols = feat.cols, factor_cols = meta.cols)
Pf.cmpd$data <- Pf.cmpd$data %>%
  dplyr::select(one_of(c("Metadata_broad_sample", Pf.cmpd$feat_cols))) %>%
  dplyr::group_by(Metadata_broad_sample) %>%
  dplyr::summarise_each(funs("mean"))

Pf.cmpd$factor_cols <- "Metadata_broad_sample"

cl <- colnames(Pf.cmpd.data1)
meta.cols <- cl[which(str_detect(cl, "Metadata"))]
meta.data <- rbind(Pf.cmpd.data1, Pf.cmpd.data2) %>%
  dplyr::select(Metadata_broad_sample, Metadata_Plate_Map_Name) %>%
  unique

Pf.cmpd$data %<>%
  dplyr::left_join(., meta.data, "Metadata_broad_sample")

Pf.cmpd$data %<>%
  mutate(Metadata_is.bioactive = str_detect(Metadata_Plate_Map_Name, "BIO"))

Pf.cmpd$factor_cols <- c(Pf.cmpd$factor_cols, "Metadata_Plate_Map_Name", "Metadata_is.bioactive")
Pf <- Pf.cmpd

```

```{r adding compound name metadata}

metadata.ext <- readr::read_csv("../input/CDP2/cdrp.cpd.meta.csv")
brd.full <- unique(Pf$data$Metadata_broad_sample)
brds <- lapply(brd.full, function(x) paste(str_split(x, "-")[[1]][1:2],
                                                   sep = "-", collapse = "-")) %>% unlist()
brd.mapping <- data.frame(BROAD_CPD_ID = brds,
                          Image_Metadata_BROAD_ID = brd.full)
metadata.ext %<>%
  dplyr::select(BROAD_CPD_ID, CPD_NAME) %>%
  dplyr::filter(BROAD_CPD_ID %in% brds) %>%
  dplyr::mutate(CPD_NAME = ifelse(str_detect(CPD_NAME, "BRD-"), "", CPD_NAME)) %>%
  dplyr::inner_join(., brd.mapping, by = "BROAD_CPD_ID") %>%
  dplyr::select(-BROAD_CPD_ID)

metadata <- data.frame(Metadata_broad_sample = unique(Pf$data$Metadata_broad_sample))
metadata %<>%
  dplyr::left_join(., metadata.ext, by = c("Metadata_broad_sample" = "Image_Metadata_BROAD_ID"))

Pf$data %<>% dplyr::left_join(., metadata, by = "Metadata_broad_sample")

Pf$data %<>% dplyr::mutate(Metadata_Compound_Name = CPD_NAME) %>%
  select(-CPD_NAME)
Pf$factor_cols <- c(Pf$factor_cols, "Metadata_Compound_Name")

Pf$data %>% group_by(Metadata_is.bioactive) %>% tally
Pf$data %>% mutate(has.a.name = !(Metadata_Compound_Name %in% c("", NA))) %>% group_by(has.a.name) %>% tally


```

```{r get the correlation}

cr <- Pf$data %>% select(one_of(Pf$feat_cols)) %>% t %>% cor
cmpd.id <- paste(Pf$data$Metadata_Compound_Name, Pf$data$Metadata_broad_sample, sep = "_")
rownames(cr) <- cmpd.id
colnames(cr) <- cmpd.id

```

```{r hierarchical clustering}

cls.id <- (1 - cr) %>%
  as.dist() %>%
  hclust(., method = "average") %>%
  cutree(., h = 1 - 0.5)

```

```{r printing out the clusters}

cls <- c()
no.clust.with.bioact <- 0
for (i in 1:max(cls.id)) {
  cli <- names(which(cls.id == i))
  cls <- c(cls, list(cli))
  if (any(str_sub(cli, start = 1, end = 1) != "_")) {
    cat(sprintf("%d \n", i))
    cat(paste(cli, sep = "\n", collapse = "\n"))
    cat("\n --------------------- \n")
    no.clust.with.bioact <- no.clust.with.bioact + 1
  }
}

print(data.frame('No. of clusters with at least one bioactive cmpd' = no.clust.with.bioact))
print(data.frame('No. of all clusters' = max(cls.id)))
print(data.frame('Percentage of clusters with at least one bioactive cmpd' = no.clust.with.bioact/max(cls.id) * 100))


```

