---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}

library(cytominer)
library(dplyr)
source("read_dataset.R")

Pf <- read.dataset("Repurposing", dose.closest = 10)

single.cell.1 <- readRDS("../results/master/2017-07-17_e204cf3a/Repurposing_dmso_single_cell.rds")
single.cell.3 <- readRDS("../results/master/2017-07-13_e204cf3a__1/Repurposing_dmso_single_cell.rds")

cl <- intersect(colnames(single.cell.1), colnames(single.cell.3))
cl <- intersect(Pf$feat_cols, cl)

single.cell.1 <- single.cell.1 %>% select(one_of(cl))
single.cell.3 <- single.cell.3 %>% select(one_of(cl))
single.cell <- rbind(single.cell.1, single.cell.3)

single.cell <- scale(single.cell)
single.cell <- as.data.frame(single.cell)

```

```{r}

fts <- entropy_feature_selection(population = single.cell, variables = colnames(single.cell), n_feature = NCOL(single.cell))

```

```{r}

evaluate_feat_set <- function(Px, feats, same.moa.df) {
  top.p <- 0.01

  cr.melt <- Px %>%
    select(one_of(feats)) %>%
    t %>%
    cor %>%
    reshape2::melt() %>%
    cbind(., same.moa.df)

  cr.melt.sorted <- cr.melt %>%
    filter(as.character(Var1) < as.character(Var2)) %>%
    arrange(-value)

  v11 <- cr.melt.sorted %>%
    slice(1:round(n() * top.p)) %>%
    filter(same.moa) %>%
    NROW

  v12 <- cr.melt.sorted %>%
    slice(1:round(n() * top.p)) %>%
    filter(!same.moa) %>%
    NROW

  v21 <- cr.melt.sorted %>%
    slice((round(n() * top.p)+1):n()) %>%
    filter(same.moa) %>%
    NROW

  v22 <- cr.melt.sorted %>%
    slice((round(n() * top.p)+1):n()) %>%
    filter(!same.moa) %>%
    NROW

  V <- rbind(c(v11, v12), c(v21, v22))

  fisher.test(V, alternative = "greater")
}

gsea_plot <- function(Px, feats, same.moa.df) {

  cr.melt <- Px %>%
    select(one_of(feats)) %>%
    t %>%
    cor %>%
    reshape2::melt() %>%
    cbind(., same.moa.df)

  cr.melt.sorted <- cr.melt %>%
    filter(as.character(Var1) < as.character(Var2)) %>%
    arrange(-value)

  s1 <- sum(cr.melt.sorted$same.moa)
  s2 <- sum(!cr.melt.sorted$same.moa)

  v <- as.numeric(cr.melt.sorted$same.moa)
  v[which(v > 0)] <- 1/s1
  v[which(v == 0)] <- -1/s2
  gsea <- cumsum(v)

  return(gsea)
}


```

```{r}

N <- 100

Px <- Pf$data %>%
  group_by(Metadata_broad_sample, Metadata_moa) %>%
  summarise_at(.vars = Pf$feat_cols, .funs = "mean") %>%
  ungroup() %>%
  group_by(Metadata_broad_sample, Metadata_moa) %>%
  slice(1) %>%
  ungroup

rownames(Px) <- Px$Metadata_broad_sample

same.moa <- function(x, y) {
  if (is.na(x) || is.na(y) || x == "" || y == "")
    return(FALSE)
  xs <- str_split(x, "\\|")[[1]]
  ys <- str_split(y, "\\|")[[1]]
  return(any(xs %in% ys) | any(ys %in% xs))
}

same.moa <- Vectorize(same.moa)

same.moa.df <- Px %>%
  select(one_of(Pf$feat_cols)) %>%
  t %>%
  cor %>%
  reshape2::melt() %>%
  left_join(., Px %>%
              select(Metadata_broad_sample, Metadata_moa), by = c("Var1" = "Metadata_broad_sample")) %>%
  left_join(., Px %>%
              select(Metadata_broad_sample, Metadata_moa), by = c("Var2" = "Metadata_broad_sample")) %>%
  mutate(same.moa = same.moa(Metadata_moa.x, Metadata_moa.y)) %>%
  select(same.moa)

g1 <- gsea_plot(Px = Px, feats = Pf$feat_cols, same.moa.df = same.moa.df)

g2 <- gsea_plot(Px = Px, feats = fts$feats[fts$CE > 0], same.moa.df = same.moa.df)

g3 <- NULL

for (i in 1:N) {
  gx <- gsea_plot(Px = Px, feats = sample(Pf$feat_cols, sum(fts$CE > 0)), same.moa.df = same.moa.df)
  if (is.null(g3)) {
    g3 <- gx
  } else {
    g3 <- g3 + gx
  }
}

g3 <- g3 / N

```

```{r}

library(ggplot2)

g1 <- head(g1, round(0.01 * length(g1)))
g2 <- head(g2, round(0.01 * length(g2)))
g3 <- head(g3, round(0.01 * length(g3)))

df.1 <- data.frame(GSEA = g1) %>%
  mutate(index = 1:length(g1)) %>%
  mutate(method = sprintf("All the features (d = %d)", length(Pf$feat_cols)))

df.2 <- data.frame(GSEA = g2) %>%
  mutate(index = 1:length(g2)) %>%
  mutate(method = sprintf("SR-SVD (d = %d)", sum(fts$CE > 0)))

df.3 <- data.frame(GSEA = g3) %>%
  mutate(index = 1:length(g3)) %>%
  mutate(method = "random of size as in SR-SVD")

df <- rbind(df.1, df.2, df.3)

g <- ggplot(df, aes(x = index, y = GSEA, color = method)) +
  geom_line() +
  xlab("index of sorted conn.") +
  ylab("enrichment score")

g

ggsave("Repurposing_eval.png", g)

```
```{r}

library(rbenchmark)
library(progress)

bns <- NULL
rg <- 500:100:NROW(single.cell)
pb <- progress_bar$new(total = length(rg))

for (sz in rg) {
  single.cell.sub <- single.cell %>%
    sample_n(size = sz)

  bn <- benchmark("SR_SVD" = {entropy_feature_selection(population = single.cell.sub, variables = colnames(single.cell.sub), n_feature = NCOL(single.cell.sub)) }, replications = 5, columns = c("test","replications", "elapsed", "relative", "user.self", "sys.self"))

  pb <- pb$tick()
  if (is.null(bns)) {
    bns <- bn
  } else {
    bns <- rbind(bns, bn)
  }
}

```

