
```{r read data}

rm(list = ls())
set.seed(42)

library(dplyr)
library(stringr)
library(foreach)
library(doParallel)
library(pbapply)
doParallel::registerDoParallel(cores = 4)

source("validate_compound_conn.R")
valid.pair <- Vectorize(valid.pair)
valid.pair.alt <- Vectorize(valid.pair.alt)

soft.req <- T

load("../input/TA/Initial_analysis_workspace_new.RData")
gene.compound.cr <- readRDS("../results/master/2017-05-02_9796dc34/cr_melt_cp.rds")
moa2 <- readr::read_csv("../input/CDP2/MOA_annot2_hand_edited.csv")

```

```{r}

moa2 <- moa2 %>%
  mutate(CPD_NAME = str_to_lower(CPD_NAME)) %>%
  mutate(CPD_NAME = ifelse(str_sub(CPD_NAME, 1, 4) == "brd-", Metadata_broad_sample, CPD_NAME))

moa2 <- moa2 %>%
  group_by(Name) %>%
  dplyr::slice(1) %>%
  ungroup()

pthw <- Pf_org$data %>%
  dplyr::select(Gene, Pathway) %>%
  unique %>%
  dplyr::filter(Gene != "EMPTY")

gene.compound.cr <- gene.compound.cr %>%
  left_join(., moa2, by = c("Var1" = "CPD_NAME")) %>%
  left_join(., pthw, by = c("Var2" = "Gene")) %>%
  mutate(valid = valid.pair(Var2, Target))

```

```{r}

vls <- gene.compound.cr %>%
  group_by(Var1) %>%
  summarise(valids = sum(valid > 0)) %>%
  select(valids)

library(ggplot2)

g <- ggplot(vls, aes(x = valids)) + geom_histogram(aes(y = ..count..)) + xlab("Number of Associated Genes")

ggsave(filename = "n_gene_plot.png", g)

```

```{r}

vls <- gene.compound.cr %>%
  group_by(Var2) %>%
  summarise(valids = sum(valid > 0)) %>%
  select(valids)

library(ggplot2)

g <- ggplot(vls, aes(x = valids)) + geom_histogram(aes(y = ..count..)) + xlab("Number of Associated Compounds")

ggsave(filename = "n_compound_plot.png", g)

```

```{r}

gene.compound.cr.alt <- gene.compound.cr %>%
  left_join(., moa2, by = c("Var1" = "CPD_NAME")) %>%
  left_join(., pthw, by = c("Var2" = "Gene")) %>%
  mutate(valid = valid.pair.alt(Var2, Target))

```


```{r}

cmpd.targs <- gene.compound.cr %>%
  filter(valid > 0) %>%
  group_by(Var1) %>%
  #dplyr::summarise(valids = sum(valid > 0))
  dplyr::summarise(valids = length(str_split(Target, ", ")[[1]]))

cmpd.joined <- gene.compound.cr %>%
  filter(valid > 0) %>%
  left_join(cmpd.targs, by = "Var1")

library(ggplot2)

g <- ggplot(cmpd.joined, aes(x = value, y = valids)) + ggplot2::geom_point() + ylab("Number of Direct Protein Targets of the Compound") + xlab("Absolute Correlation of a Correct Compound-Gene Connection")

ggsave("plot.png", g)

```

```{r}

corr.thr <- 0.35
gene.thr <- 3

cmpd.targs <- gene.compound.cr %>%
  group_by(Var1) %>%
  dplyr::summarise(valids = length(str_split(Target, ", ")[[1]]))

cmpd.joined <- gene.compound.cr %>%
  left_join(cmpd.targs, by = "Var1")

u <- cmpd.joined %>%
  group_by(Var1) %>%
  summarise(valids = mean(valids),
            correct.matches = sum(valid > 0 & value > corr.thr),
            non.matches = sum(valid == 0 & value > corr.thr))

V11 <- u %>%
  filter(valids < gene.thr & correct.matches > 0) %>%
  NROW()

V12 <- u %>%
  filter(valids < gene.thr & correct.matches == 0) %>%
  NROW()

V21 <- u %>%
  filter(valids >= gene.thr & correct.matches > 0) %>%
  NROW()

V22 <- u %>%
  filter(valids >= gene.thr & correct.matches == 0) %>%
  NROW()

V <- rbind(c(V11, V12), c(V21, V22))
fisher.test(V, alternative = "greater")

```

```{r}
ls <- c()
gene.compound.cr.tot <- readRDS("../results/master/2017-10-11_7d18c89d/cr_melt_cp.rds")


gene <- lapply(gene.compound.cr.tot$Var2, function(x) str_split(x, "_")[[1]][1]) %>% unlist
allele <- lapply(gene.compound.cr.tot$Var2, function(x) str_split(x, "_")[[1]][2]) %>% unlist
v <- gene.compound.cr.tot %>%
  mutate(Var2.gene = gene,
         Var2.allele = allele)
u <- v %>%
  filter(Var2.allele == "WT" | Var2.allele == "WT.1")

gene.compound.cr.tot <- u %>% mutate(Var2 = Var2.gene) %>% select(Var1, Var2, value)

gene.compound.cr.all <- gene.compound.cr.tot %>%
  left_join(gene.compound.cr, by = c("Var1", "Var2"))

for (gene in unique(gene.compound.cr$Var2)) {
  u <- gene.compound.cr.all %>%
    filter(Var2 == gene) %>%
    arrange(-abs(value.x))

  s <- which(u$valid > 0)[1] %>% as.matrix() %>% as.vector()
  ls <- c(ls, s)
}

df <- data.frame(rank = ls)

library(ggplot2)

g <- ggplot(df %>% filter(!is.na(rank)), aes(x = rank)) + geom_histogram(bins = 40) + xlab("rank number of the top-most correct compound for a given gene") + ggplot2::xlim(0, 15863) + theme_bw()

ggsave("rank_hist.png", g)

```

```{r}

cmpd.num <- length(unique(gene.compound.cr.all$Var1))
length(which(df$rank < cmpd.num * 0.001))
length(which(df$rank < cmpd.num * 0.01))
length(which(df$rank < cmpd.num * 0.02))
length(which(df$rank < cmpd.num * 0.05))

```

```{r}

length(which(df$rank < 307))

```

```{r}

library(ggplot2)

vls <- gene.compound.cr %>%
  filter(!is.na(Target)) %>%
  arrange(-abs(value)) %>%
  select(valid) %>%
  as.matrix() %>%
  as.vector()

pos.avg <- sum(vls)/sum(vls != 0)
zr <- which(vls == 0)
nzr <- which(vls != 0)

hash.marks <- vls
vls[zr] <- -1/length(zr)
vls[nzr] <- vls[nzr]/length(nzr)/pos.avg

cs <- cumsum(vls)

plot(cs, type = "l")


```

```{r}
library(ggplot2)

vls <- gene.compound.cr %>%
  filter(!is.na(Target)) %>%
  arrange(-abs(value)) %>%
  select(valid) %>%
  as.matrix() %>%
  as.vector()

corrs <- gene.compound.cr %>%
  filter(!is.na(Target)) %>%
  arrange(-abs(value)) %>%
  select(value) %>%
  as.matrix() %>%
  as.vector()

pos.avg <- sum(vls)/sum(vls != 0)
zr <- which(vls == 0)
nzr <- which(vls != 0)

hash.marks <- vls
vls[zr] <- -1/length(zr)
vls[nzr] <- vls[nzr]/length(nzr)/pos.avg

cs <- cumsum(vls)

df <- data.frame(abs.corr = 1 - abs(corrs), enrichment = cs)

library(ggplot2)

g <- ggplot(df, aes(x = abs.corr, y = enrichment)) + geom_line() + xlab(" 1 - Absolute Correlation") + ylab("Enrichment Score")

ggsave("enrichment_by_corr.png", g)

```

```{r}

valid.pairs <- gene.compound.cr %>%
  filter(valid > 0) %>%
  select(value) %>%
  as.matrix() %>%
  as.vector() %>%
  abs()

non.val.pairs <- gene.compound.cr %>%
  filter(valid == 0) %>%
  select(value) %>%
  as.matrix() %>%
  as.vector() %>%
  abs()

df1 <- data.frame(same.moa = "Correct Pairs", correlation = valid.pairs)
df2 <- data.frame(same.moa = "Incorrect Pairs", correlation = non.val.pairs)

library(ggplot2)

g <- ggplot2::ggplot(mapping = aes(x = correlation, y=..density..)) +
  geom_histogram(data = df1, aes(fill = "red"), bins = 40, alpha=0.5) +
  geom_histogram(data = df2, aes(fill = "blue"), bins = 40, alpha=0.5) +
  xlab("Correlation") +
  scale_fill_manual(name = "", values = c("red", "blue"), labels=c("red" = "Correct Pairs", "blue" = "Incorrect Pairs"))

ggsave("correct_vs_incorrect_corr.png", g)

```

```{r}

u <- gene.compound.cr %>%
  dplyr::mutate(value.rank = NROW(gene.compound.cr) - rank(abs(value)))

valid.pairs <- u %>%
  filter(valid > 0) %>%
  select(value.rank) %>%
  as.matrix() %>%
  as.vector() %>%
  abs()

non.val.pairs <- u %>%
  filter(valid == 0) %>%
  select(value.rank) %>%
  as.matrix() %>%
  as.vector() %>%
  abs()

df1 <- data.frame(same.moa = "Correct Pairs", correlation = valid.pairs)
df2 <- data.frame(same.moa = "Incorrect Pairs", correlation = non.val.pairs)

library(ggplot2)

g <- ggplot2::ggplot(mapping = aes(x = correlation, y=..density..)) +
  geom_histogram(data = df1, aes(fill = "red"), bins = 40, alpha=0.5) +
  geom_histogram(data = df2, aes(fill = "blue"), bins = 40, alpha=0.5) +
  xlab("rank of absolute correlation") +
  scale_fill_manual(name = "", values = c("red", "blue"), labels=c("red" = "Correct Pairs", "blue" = "Incorrect Pairs"))

ggsave("correct_vs_incorrect_rank.png", g)
```

```{r}

library(grid)
library(gridExtra)

valid.pair2 <- function(targets, gene) {
  gene %in% (str_split(targets, ", ")[[1]])
}

valid.pair2 <- Vectorize(valid.pair2)

valid.sum <- gene.compound.cr %>%
  group_by(Var2) %>%
  summarise(valid.sum = sum(valid)) %>%
  arrange(-valid.sum)

#valid.sum != 0 & valid/valid.sum >= 0.05 & soft.req |
gene.compound.cr.precise <- gene.compound.cr %>%
  left_join(., valid.sum, by = "Var2") %>%
  mutate(valid2 = ( valid.pair2(Target, Var2)))


vls <- gene.compound.cr.precise %>%
  arrange(-abs(value)) %>%
  select(valid2) %>%
  as.matrix() %>%
  as.vector()

indx <- which(vls)

zr <- which(vls == 0)
nzr <- which(vls != 0)
vls[zr] <- -1/length(zr)
vls[nzr] <- vls[nzr]/length(nzr)
cs <- cumsum(vls)

g2 <- ggplot(data.frame(x = 1:length(cs), y = cs), aes(x = x, y = y)) + geom_line() + xlab("sorted index of gene-compound connections") + ylab("enrichment")

g <- ggplot()

for (i in indx) {
    g <- g + geom_vline(xintercept = i)
}

g <- g + xlab("") + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

g1 <- ggplot_gtable(ggplot_build(g))
g2 <- ggplot_gtable(ggplot_build(g2))
maxWidth <- unit.pmax(g1$widths[2:3], g2$widths[2:3])
g1$widths[2:3] <- maxWidth
g2$widths[2:3] <- maxWidth

graphics.off()
quartz(width = 12, height = 8)
grid.arrange(g2, g1, heights = c(1.33, 0.3))

dev.print(device = pdf, "enrichment.pdf")

```

```{r}

gene.compound.cr.precise <- gene.compound.cr.alt %>% filter(!is.na(Target))

val.thr <- 0.5

v11 <- gene.compound.cr.precise %>% filter(abs(value) >= 0.35 & valid > val.thr) %>% NROW

v12 <- gene.compound.cr.precise %>% filter(abs(value) < 0.35 & valid > val.thr) %>% NROW

v21 <- gene.compound.cr.precise %>% filter(abs(value) >= 0.35 & valid <= val.thr) %>% NROW

v22 <- gene.compound.cr.precise %>% filter(abs(value) < 0.35 & valid <= val.thr) %>% NROW

V <- rbind(c(v11, v12), c(v21, v22))

rownames(V) <- c("validated pairs", "non-validated pairs")
colnames(V) <- c("abs corr. >= 0.35", "abs corr. < 0.35")

V %>% t %>% htmlTable::htmlTable() %>% print

fisher.test(V, alternative = "greater")

```

```{r}

thr <- 0.35

s11 <- gene.compound.cr.precise %>%
  filter(abs(value) >= thr & valid2)

s12 <- gene.compound.cr.precise %>%
  filter(abs(value) < thr & valid2)

s21 <- gene.compound.cr.precise %>%
  filter(abs(value) >= thr & !valid2)

s22 <- gene.compound.cr.precise %>%
  filter(abs(value) < thr & !valid2)


V <- rbind(c(s11 %>% NROW, s12 %>% NROW), c(s21 %>% NROW, s22 %>% NROW))
fisher.test(V, alternative = "greater")

s11 %>% htmlTable::htmlTable()
V %>% htmlTable::htmlTable()

```

```{r}

library(igraph)

coeff <- 1.5

adj.mat <- s11 %>%
  mutate(value = ifelse(value > 0, 2, ifelse(value < 0, 1, 0))) %>%
  reshape2::acast(Name ~ Var2, fill = 0)

org.adj.mat <- adj.mat

mt1 <- matrix(0, NROW(adj.mat), NROW(adj.mat))
rownames(mt1) <- rownames(adj.mat)
colnames(mt1) <- rownames(adj.mat)

mt2 <- matrix(0, NCOL(adj.mat), NCOL(adj.mat))
rownames(mt2) <- colnames(adj.mat)
colnames(mt2) <- colnames(adj.mat)

cls <- c(rep("black", NROW(mt1)),
         rep("dark green", NROW(mt2)))

vertex.shape <- c(rep("none", NROW(mt1)),
         rep("none", NROW(mt2)))

vertex.size <- coeff * c(rep(10, NROW(mt1)),
         rep(10, NROW(mt2)))

vertex.size2 <- coeff * c(rep(4, NROW(mt1)),
         rep(4, NROW(mt2)))

vertex.label.cex = coeff * c(rep(1, NROW(mt1)),
         rep(1.2, NROW(mt2)))

adj.mat <- cbind(mt1, adj.mat)
adj.mat <- rbind(adj.mat, cbind(t(org.adj.mat), mt2))

g <- igraph::graph.adjacency(adj.mat, mode = "undirected", weighted = T)

E(g)$color <- ifelse(E(g)$weight == 1, "red", "blue")

graphics.off()
quartz(width = 20, height = 15)

plot(g,
     vertex.size = vertex.size,
     vertex.size2 = vertex.size2,
     vertex.label.cex = vertex.label.cex,
     vertex.shape = vertex.shape,
     curved = T, vertex.label.color = cls,
     asp = 15/20)

dev.print(device = pdf, "hit_graph.pdf")

```

```{r, drug disc.}

k <- 30
N <- 1000
n <- 10
permute <- F
.gene <- gene.compound.cr %>% select(Var2) %>% unique %>% as.matrix() %>% as.vector()
gene.compound.cr <- gene.compound.cr.precise

if (permute) {
  .cr <- gene.compound.cr %>%
    group_by(Var1, Var2) %>%
    summarise(value = max(value, na.rm = T)) %>%
    select(Var1, Var2, value) %>%
    reshape2::acast(Var1 ~ Var2)

  rn <- rownames(.cr)
  cn <- colnames(.cr)

  while(T) {
    cn.pr <- sample(cn, size = length(cn))
    if (all(cn.pr != cn)) {
      break
    }
  }

  colnames(.cr) <- cn.pr

  gene.compound.cr.pr <- .cr %>%
    reshape2::melt() %>%
    left_join(., gene.compound.cr %>% select(-value), by = c("Var1", "Var2"))
} else {
  gene.compound.cr.pr <- gene.compound.cr
}

gene.compound.cr.pr <- gene.compound.cr.pr %>%
  arrange(-abs(value)) %>%
  filter(!is.na(Target))

matching.score <- function(gene.x, top.k, N, n) {
  sg.v <- gene.compound.cr.pr %>% filter(Var2 == gene.x) %>% slice(1:top.k)
  sg <- sg.v %>% filter(valid2) %>% NROW

  cr.rem <- gene.compound.cr.pr %>% filter(Var2 == gene.x) %>% slice((top.k + 1):n())

  p.val <- foreach (j = 1:n, .combine = rbind) %do% {
    nl <- foreach (i = 1:N) %dopar% {
       r <- cr.rem %>% sample_n(NROW(sg.v)) %>% filter(valid2) %>% NROW
       r
    }

    nl <- unlist(nl)
    if (max(nl) == 0) {
      return(1)
    }
    return(1 - ecdf(nl)(sg))
  }

  mean(p.val)
}

p.vals <- pblapply(.gene, function(x) matching.score(x, top.k = k, N, n)) %>% unlist

gene.blacklist <- gene.compound.cr %>% group_by(Var2) %>% summarise(x = sum(valid)) %>% filter(x == 0) %>% select(Var2) %>% as.matrix() %>% as.vector()

data.frame(gene = .gene, p.value = p.vals) %>%
  filter(!gene %in% gene.blacklist) %>%
  mutate(p.value = p.adjust(p.value, "BH")) %>%
  arrange(p.value) %>%
  htmlTable::htmlTable()

save.image("workspace_drugDisc.RData")

```

```{r, MOA pred}

k <- 2
N <- 1000
n <- 10
permute <- F
.compound <- gene.compound.cr %>% select(Var1) %>% unique %>% as.matrix() %>% as.vector()
gene.compound.cr <- gene.compound.cr.precise

if (permute) {
  .cr <- gene.compound.cr %>%
    group_by(Var1, Var2) %>%
    summarise(value = max(value, na.rm = T)) %>%
    select(Var1, Var2, value) %>%
    reshape2::acast(Var1 ~ Var2)

  rn <- rownames(.cr)
  cn <- colnames(.cr)

  while(T) {
    cn.pr <- sample(cn, size = length(cn))
    if (all(cn.pr != cn)) {
      break
    }
  }

  colnames(.cr) <- cn.pr

  gene.compound.cr.pr <- .cr %>%
    reshape2::melt() %>%
    left_join(., gene.compound.cr %>% select(-value), by = c("Var1", "Var2"))
} else {
  gene.compound.cr.pr <- gene.compound.cr
}

gene.compound.cr.pr <- gene.compound.cr.pr %>%
  arrange(-abs(value)) %>%
  filter(!is.na(Target))

matching.score <- function(compound.x, top.k, N, n) {
  sg.v <- gene.compound.cr.pr %>% filter(Var1 == compound.x) %>% slice(1:top.k)
  sg <- sg.v %>% filter(valid2) %>% NROW

  cr.rem <- gene.compound.cr.pr %>% filter(Var1 == compound.x) %>% slice((top.k + 1):n())

  p.val <- foreach (j = 1:n, .combine = rbind) %do% {
    nl <- foreach (i = 1:N) %dopar% {
       r <- cr.rem %>% sample_n(NROW(sg.v)) %>% filter(valid2) %>% NROW
       r
    }

    nl <- unlist(nl)
    if (max(nl) == 0) {
      return(1)
    }
    return(1 - ecdf(nl)(sg))
  }

  mean(p.val)
}

p.vals <- pblapply(.compound, function(x) matching.score(x, top.k = k, N, n)) %>% unlist

compound.blacklist <- gene.compound.cr %>% group_by(Var1) %>% summarise(x = sum(valid2)) %>% filter(x == 0) %>% select(Var1) %>% as.matrix() %>% as.vector()

data.frame(compound = .compound, p.value = p.vals) %>%
  filter(!compound %in% compound.blacklist) %>%
  mutate(p.value = p.adjust(p.value, "BH")) %>%
  arrange(p.value) %>%
  htmlTable::htmlTable()

save.image("workspace_MOApred.RData")

```
