---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
library(dplyr)
library(stringr)
library(Rtsne)
library(ggplot2)
set.seed(12)

cdrp.bio <- readRDS("../results/master/2017-04-20_425d653/Pf_bio_new.rds")
cdrp.DOS <- readRDS("../results/master/2017-04-20_425d653/Pf_DOS_new.rds")

cdrp.all <- rbind(cdrp.bio, cdrp.DOS)

feat.cols <- colnames(cdrp.all)
feat.cols <- feat.cols[which(!str_detect(feat.cols, "Metadata"))]
metadata.cols <- setdiff(colnames(cdrp.all), feat.cols)
  
Px <- cdrp.all %>%
  group_by(Metadata_broad_sample, Metadata_Plate_Map_Name) %>%
  summarise_at(.vars = feat.cols, .funs = "mean") %>%
  ungroup() %>%
  mutate(Metadata_Treatment = paste0(Metadata_broad_sample, ":", "Metadata_Plate_Map_Name"))

metadata.cols <- c(metadata.cols, "Metadata_Treatment")

```

```{r}

hits <- c("BRD-K26994486", "BRD-K91354313")

has.hits <- function(x) {
  any(str_detect(x, hits))  
}

has.hits <- Vectorize(has.hits)

hits.canonical <- Px %>%
  filter(has.hits(Metadata_broad_sample)) %>%
  select(Metadata_broad_sample) %>%
  as.matrix() %>% 
  as.vector()
  
rownames(Px) <- Px$Metadata_broad_sample

cr <- cor(Px %>% filter(Metadata_broad_sample %in% hits.canonical) %>% select(one_of(feat.cols)) %>% t %>% as.matrix(), Px[, feat.cols] %>% t %>% as.matrix())
  
rownames(cr) <- hits.canonical
colnames(cr) <- Px$Metadata_broad_sample

moa2 <- readr::read_csv("../input/CDP2/MOA_annot2.csv")
moa2 <- moa2 %>% mutate(Name = ifelse(is.na(Name), CPD_NAME, Name))

cr.melt <- cr %>%
  reshape2::melt() %>%
  arrange(-value) %>%
  left_join(., moa2, by = c("Var2" = "Metadata_broad_sample")) %>%
  select(-CPD_NAME) %>%
  filter(!is.na(Name))

x <- cr.melt %>% 
  group_by(Var1) %>%
  slice(1:10) %>%
  ungroup() %>%
  arrange(Var1) 

x %>%
  htmlTable::htmlTable()

cmpd.matches <- x %>%
  select(Var2) %>%
  as.matrix() %>%
  as.vector() 

```

```{r}

gene.matches <- c("BRD-K59184148-001-10-9", "BRD-K93051667-001-01-8", "BRD-K68303333-001-01-8", "BRD-K84480302-001-01-1", "BRD-K68074655-001-01-5", "BRD-K80298065-001-01-8", "BRD-K87264606-001-01-9", "BRD-K99195544-001-01-6", "BRD-A62505706-001-02-3", "BRD-K04407772-001-01-2", "BRD-K26994486-001-01-0", "BRD-K50710722-001-01-3", "BRD-K88156935-001-01-8", "BRD-K91354313-001-01-6", "BRD-K54148510-001-01-8")

Px.sub <- Px %>%
  filter(Metadata_broad_sample %in% gene.matches)

cr.sub <- Px.sub %>% 
  select(one_of(feat.cols)) %>%
  t %>%
  cor 
  
y <- Rtsne::Rtsne(Px %>% select(one_of(feat.cols)), perplexity = 20)
  
z <- as.data.frame(y$Y)

z <- cbind(z, Px %>% select(Metadata_broad_sample)) %>%
  filter(Metadata_broad_sample %in% gene.matches) %>%
  mutate(compound =  ifelse(Metadata_broad_sample == "BRD-K59184148-001-10-9",
                            "SB-216763", 
                            ifelse(str_detect(Metadata_broad_sample, hits[1]), hits[1], 
                                   ifelse(str_detect(Metadata_broad_sample, hits[2]), hits[2],
                                          "other compound matches")))) %>%
  mutate(size = 2) %>%
  mutate(Metadata_broad_sample = str_sub(Metadata_broad_sample, 1, 13))

g <- ggplot(z, aes(x = V1, y = V2, colour = compound, label = Metadata_broad_sample)) +
  geom_text_repel(size = 3.5, segment.size = 0) 

ggsave("tsne_gsk3_matches.png", g, width = 12, height = 10)

```

```{r}

cr.cmpd.gene <- readRDS("../results/master/2017-10-11_7d18c89d/cr_melt_cp.rds")

cmpd <- hits[1]
cr.cmpd.gene %>% 
  filter(str_detect(Var1, cmpd)) %>%
  arrange(value) %>%
  head %>%
  mutate(value = round(value, 2)) %>%
  htmlTable::htmlTable()

cmpd <- hits[2]
cr.cmpd.gene %>% 
  filter(str_detect(Var1, cmpd)) %>%
  arrange(value) %>%
  head %>%
  mutate(value = round(value, 2)) %>%
  htmlTable::htmlTable()

```

