---
title: "R Notebook"
output: html_notebook
---

```{r}

library(dplyr)
library(stringr)
source("read_dataset.R")

Pf.repurp <- read.dataset("Repurposing", dose.closest = NULL)

a <- Pf.repurp$data %>%
  select(one_of(c(Pf.repurp$feat_cols, 
                  "Metadata_Treatment", 
                  "Metadata_pert_iname"))) %>% 
  group_by(Metadata_Treatment, 
           Metadata_pert_iname) %>% 
  summarise_each(funs("mean"))

cr <- cor(a[,Pf.repurp$feat_cols] %>% t)

colnames(cr) <- a$Metadata_Treatment
rownames(cr) <- a$Metadata_Treatment

selected.trt <- Pf.repurp$data %>%
  filter(Metadata_pert_iname %in% c("clofoctol",
                                    "disulfiram",
                                    "felbamate",
                                    "kpt-330",
                                    "mk-2206",
                                    "mozavaptan",
                                    "sta-5326",
                                    "tosedostat")) %>%
  select(Metadata_Treatment) %>% 
  as.matrix() %>% 
  as.vector()

cr <- cr[selected.trt,]

cr.melt <- cr %>% 
  reshape2::melt() %>% 
  left_join(., 
            Pf.repurp$data[,c("Metadata_pert_iname", "Metadata_moa", "Metadata_Treatment")] %>% unique, 
            by = c("Var1" = "Metadata_Treatment")) %>%
  left_join(., 
            Pf.repurp$data[,c("Metadata_pert_iname", "Metadata_moa", "Metadata_Treatment")] %>% unique, 
            by = c("Var2" = "Metadata_Treatment")) %>%
  filter(Metadata_pert_iname.x != Metadata_pert_iname.y) 

u <- cr.melt %>% 
  filter(Metadata_pert_iname.y != "dmso") %>%
  arrange(-value) %>%
  group_by(Metadata_pert_iname.x) %>%
  slice(1:100) %>%
  ungroup %>%
  group_by(Metadata_pert_iname.x, Metadata_pert_iname.y, Metadata_moa.x, Metadata_moa.y) %>%
  tally() %>%
  ungroup() %>%
  arrange(-n) %>%
  group_by(Metadata_pert_iname.x) %>%
  slice(1:15) %>%
  ungroup()
  
u %>% htmlTable::htmlTable()

```
```{r}

load("../input/TA/Initial_analysis_workspace_new.RData")
Pf.ta <- Pf_org.org.collapsed
Pf.ta.all <- Pf_org.org
strong.trt <- Pf.trt.strong.collapsed$data$Treatment
data.annot <- Pf.strong %>% dplyr::filter(Treatment %in% strong.trt) %>% dplyr::select(one_of(c("Treatment", "Pathway", "Gene", "AlleleDesc"))) %>% 
  dplyr::mutate(Pathway = str_replace(Pathway, "Canonical ", "")) %>% 
  dplyr::mutate(AlleleDesc = str_sub(AlleleDesc, 1, 2)) %>%
  dplyr::filter(AlleleDesc == "WT") %>% dplyr::group_by(Gene) %>% dplyr::slice(1) %>%
  dplyr::ungroup() 
desired.ta <- data.annot$Treatment
Pf.ta.all$data <- Pf.ta.all$data %>% dplyr::filter(Treatment %in% c(as.character(desired.ta), "EMPTY_")) 
Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 

Pf.ta$data <- Pf.ta$data %>% dplyr::filter(Treatment %in% desired.ta) 
Pf.ta$data$Treatment <- lapply(Pf.ta$data$Treatment, function(x) (str_split(x, "_")[[1]][1])) %>% unlist 
Pf.gene <- Pf.ta

Pf.cmpd <- Pf.repurp

f1 <- Pf.cmpd$feat_cols
f2 <- Pf.gene$feat_cols
f <- intersect(f1, f2)

Pf.cmpd$feat_cols <- f
Pf.gene$feat_cols <- f

Pf.cmpd$data <- Pf.cmpd$data[,c(Pf.cmpd$factor_cols, Pf.cmpd$feat_cols)]
Pf.gene$data <- Pf.gene$data[,c(Pf.gene$factor_cols, Pf.gene$feat_cols)]
  
```

```{r}

corr.type <- "pearson"
cr.melt.all <- c()
cmpd.all <- Pf.cmpd$data$Metadata_pert_iname %>% unique()
cr <- outer(rep(0, length(cmpd.all)), rep(0, NROW(Pf.gene$data)), "*")
rownames(cr) <- cmpd.all
colnames(cr) <- Pf.gene$data$Treatment

for (i in 1:6) {
  d <- Pf.cmpd$data %>% dplyr::group_by(Metadata_pert_iname) %>% dplyr::slice(i) %>% dplyr::ungroup()
  
  x <- d[,Pf.cmpd$feat_cols]
  y <- Pf.gene$data[,Pf.gene$feat_cols]
  
  cri <- cor(x %>% t, y %>% t, method = corr.type) 
  rownames(cri) <- d$Metadata_pert_iname
  colnames(cri) <- Pf.gene$data$Treatment
  
  crj <- cr * NA
  crj[rownames(cri), colnames(cri)] <- cri 
  
  if (is.null(cr.melt.all)) {
    cr.melt.all <- crj %>% reshape2::melt()
  } else {
    cr.melt <- crj %>% reshape2::melt()
    cr.melt.all <- cbind(cr.melt.all, cr.melt[,3])
  }
}

v1 <- apply(cr.melt.all, 1, function(x) (max(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))
v2 <- apply(cr.melt.all, 1, function(x) (min(x[3:NCOL(cr.melt.all)] %>% as.numeric(), na.rm = T) %>% as.matrix() %>% as.vector))
v3 <- apply(cbind(abs(v1), abs(v2)), 1, function(x) max(x, na.rm = T) * c(1, -1)[which.max(x)])
cr.melt <- reshape2::melt(cr)
cr.melt[,3] <- v3
cr.melt %>% dplyr::group_by(Var1, Var2) %>% dplyr::summarise(value = mean(value)) %>% head

```
```{r}

cr.melt %>% 
  filter(Var1 %in% c("clofoctol",
                                    "disulfiram",
                                    "felbamate",
                                    "kpt-330",
                                    "mk-2206",
                                    "mozavaptan",
                                    "sta-5326",
                                    "tosedostat")) %>%
  filter(abs(value) > 0.40) %>%
  arrange(-abs(value)) %>%
  group_by(Var1) %>%
  slice(1:10) %>%
  ungroup() %>%
  htmlTable::htmlTable()

```

