
```{r setup}

rm(list = ls())
library(dplyr)
library(stringr)
library(reshape2)
library(htmlTable)
library(doParallel)
library(foreach)
doParallel::registerDoParallel(cores = 2)
source("rep.corr.func.R")
seed.moa <- 42

x <- readRDS("../input/repurp/2016_04_01_a549_48hr_batch1_normalized.rds")
x <- cbind(x, data.frame(Metadata_Treatment = paste(x$Metadata_pert_id, x$Metadata_mg_per_ml, sep = "@")))
feats <- colnames(x)
feats <- feats[which(!str_detect(feats, "Metadata"))]
metadata <- colnames(x)
metadata <- metadata[which(str_detect(metadata, "Metadata"))]
thr <- non.rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
u <- rep.cor(list(data = x, feat_col = feats, factor_col = metadata), "Metadata_Treatment", feats)
strong.trt <- u$Metadata_Treatment[which(u$cr > thr)]

x <- x %>% dplyr::filter(Metadata_Treatment %in% strong.trt)
x.collapsed <- x %>% dplyr::group_by(Metadata_pert_iname, Metadata_pert_idose, Metadata_moa, Metadata_Treatment) %>%
  dplyr::select(one_of(c(feats, "Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa", "Metadata_Treatment"))) %>% dplyr::summarise_each(funs("mean")) %>% dplyr::ungroup() %>% dplyr::filter(!is.na(Metadata_pert_iname))

Pf.cmpd <- list(data = x.collapsed, feat_cols = feats, factor_cols = c("Metadata_pert_iname", "Metadata_pert_idose", "Metadata_moa", "Metadata_Treatment"))

```

```{r computing corr}

cr <- Pf.cmpd$data %>%
  select(one_of(Pf.cmpd$feat_cols)) %>%
  t %>%
  cor

```

```{r transforming corr}

rownames(cr) <- Pf.cmpd$data$Metadata_pert_iname
colnames(cr) <- Pf.cmpd$data$Metadata_pert_iname
cr.melt <- cr %>%
  reshape2::melt()

```

```{r pre-processing corr}

cr.melt2 <- cr.melt %>%
  group_by(Var1, Var2) %>%
  summarise(mn = min(value), mx = max(value))

cr.melt2 <- cr.melt2 %>%
  mutate(value = ifelse(-mn > mx, mn, mx))

```

```{r making the plot}

moas <- Pf.cmpd$data %>%
  select(Metadata_pert_iname, Metadata_moa) %>%
  unique

cr.melt <- cr.melt2 %>% dplyr::filter(Var1 != Var2)

cr.melt %<>% dplyr::left_join(., moas, by = c("Var1" = "Metadata_pert_iname")) %>%
  dplyr::left_join(., moas, by = c("Var2" = "Metadata_pert_iname"))

k <- 5

split <- function(x) {
  str_split(x, "\\|")[[1]]
}

split <- Vectorize(split)

is.matching <- function(x) {
  l1 <- split(x[,"Metadata_moa.x"] %>% as.vector()) %>% unlist %>% as.vector()
  l2 <- split(x[,"Metadata_moa.y"] %>% as.vector()) %>% unlist %>% as.vector()
  return(any(l1 %in% l2) | any(l2 %in% l1) | any(x[,"Metadata_moa.x"] == x[,"Metadata_moa.y"]))
}

res <- cr.melt %>%
  arrange(-value) %>%
  group_by(Var1, Metadata_moa.x) %>%
  do(data.frame(has.a.match = is.matching(.[1:k,]))) %>%
  dplyr::filter(has.a.match) %>%
  dplyr::select(-has.a.match) %>%
  dplyr::arrange(Metadata_moa.x)

res %>%
  htmlTable::htmlTable()

print(sprintf("ratio of compounds with a same MOA compound being in their %d-NN : %f", k, NROW(res)/length(unique(Pf.cmpd$data$Metadata_pert_iname))))

acc <- c()
for (i in 1:100) {
  res <- cr.melt %>%
    arrange(-value) %>%
    group_by(Var1, MOA.x) %>%
    do(data.frame(has.a.match = is.matching(.[sample(1:NROW(cr), k),]))) %>%
    dplyr::filter(has.a.match) %>%
    dplyr::select(-has.a.match) %>%
    dplyr::arrange(MOA.x)

  acc <- c(acc, NROW(res)/NROW(cr))
}

print(mean(acc))
print(quantile(acc, 0.95))
print(quantile(acc, 0.99))

```

```{r, eval=T}

N <- 10
ks <- 1:40

moas <- Pf.cmpd$data %>%
  select(Metadata_pert_iname, Metadata_moa) %>%
  unique

cr.melt <- cr.melt2 %>% dplyr::filter(Var1 != Var2)

cr.melt %<>% dplyr::left_join(., moas, by = c("Var1" = "Metadata_pert_iname")) %>%
  dplyr::left_join(., moas, by = c("Var2" = "Metadata_pert_iname"))

k <- 5

split <- function(x) {
  str_split(x, "\\|")[[1]]
}

split <- Vectorize(split)

is.matching <- function(x) {
  l1 <- split(x[,"Metadata_moa.x"] %>% as.vector()) %>% unlist %>% as.vector()
  l2 <- split(x[,"Metadata_moa.y"] %>% as.vector()) %>% unlist %>% as.vector()
  return(any(l1 %in% l2) | any(l2 %in% l1) | any(x[,"Metadata_moa.x"] == x[,"Metadata_moa.y"]))
}

D <- data.frame(k = c(0, 0), meas = c(0, 0), type = c("data", "null"), ci = c(0, 0))

cr.arr.grp <- cr.melt %>%
      arrange(-value) %>%
      group_by(Var1, Metadata_moa.x)

for (k in ks) {
  res <- cr.arr.grp %>%
    do(data.frame(has.a.match = is.matching(.[1:k,]))) %>%
    dplyr::filter(has.a.match)

  D <- rbind(D, data.frame(k = k, meas = NROW(res)/length(unique(Pf.cmpd$data$Metadata_pert_iname)), type = "data", ci = 0))

  baseline <- foreach (i = 1:N) %dopar% {
    res <- cr.arr.grp %>%
      do(data.frame(has.a.match = is.matching(.[sample(1:length(unique(Pf.cmpd$data$Metadata_pert_iname)), k),]))) %>%
      dplyr::filter(has.a.match)

    NROW(res)/length(unique(Pf.cmpd$data$Metadata_pert_iname))
  }
  baseline <- unlist(baseline)
  D <- rbind(D, data.frame(k = k, meas = mean(baseline), type = "null", ci = sd(baseline)/(N^0.5)))
}

g <- ggplot(D, aes(x = k, y = meas, color = type)) +
  ggplot2::geom_line() +
  ggplot2::geom_errorbar(aes(ymin = meas - ci, ymax = meas + ci), width = 0.1) +
  ggplot2::ylab("ratio of same MOA compound pairs")

g

ggsave("CDRP_eval_MOA.pdf", g, width = 6, height = 4)
```

